import type { Metadata } from 'next';
import Link from 'next/link';
import { Compass, Sparkles, MapPin } from 'lucide-react';

export const metadata: Metadata = {
  title: 'About',
  description:
    'Tobira is a hand-curated travel guide to Japan — built by someone who lives here, not trained on influencer content.',
};

const VALUES = [
  {
    icon: Compass,
    title: 'Curated, not scraped',
    description:
      'Spots are hand-selected based on research, local knowledge, and firsthand experience — not pulled from aggregator rankings or generated by an algorithm.',
  },
  {
    icon: MapPin,
    title: 'All 47 prefectures',
    description:
      'Most Japan guides cover Tokyo, Kyoto, and Osaka — then stop. Tobira covers every prefecture, from Aomori\'s apple orchards to Okinawa\'s coral reefs.',
  },
  {
    icon: Sparkles,
    title: 'AI as a tool, not the product',
    description:
      'The AI itinerary planner exists to help you arrange what we\'ve curated — not to invent destinations or recycle generic advice.',
  },
];

export default function AboutPage() {
  return (
    <div className="bg-stone-50 min-h-screen">
      {/* Hero */}
      <section className="max-w-3xl mx-auto px-4 pt-20 pb-16 text-center">
        <p className="text-stone-400 text-sm font-medium tracking-widest uppercase mb-4">
          扉 · tobira beyond tokyo
        </p>
        <h1 className="text-4xl sm:text-5xl font-bold text-stone-900 leading-tight mb-6">
          Built for the Japan
          <br />
          most guides miss.
        </h1>
        <p className="text-stone-500 text-lg leading-relaxed max-w-xl mx-auto">
          Tobira started as a personal frustration: every travel guide in English sent
          tourists to the same dozen places, often in the wrong season, with outdated
          information. We built the guide we wished existed.
        </p>
      </section>

      {/* Story */}
      <section className="max-w-3xl mx-auto px-4 pb-16">
        <div className="bg-white rounded-2xl p-8 sm:p-12 border border-stone-200 space-y-5 text-stone-600 leading-relaxed">
          <p>
            Japan has 47 prefectures. The overwhelming majority of foreign visitors see
            fewer than five. Not because the rest aren&apos;t worth visiting — quite the
            opposite — but because reliable, English-language information simply
            doesn&apos;t exist for them.
          </p>
          <p>
            Tobira is an attempt to fix that. The name (扉) means &ldquo;door&rdquo; in
            Japanese — a door to the Japan that exists beyond the guidebooks, beyond the
            Instagram hotspots, beyond the Golden Route.
          </p>
          <p>
            Every spot in our database has been selected because it offers something
            genuine: a landscape that takes your breath away, a town that feels untouched,
            a meal that you couldn&apos;t have found without a local pointing the way.
          </p>
          <p className="text-stone-900 font-medium">
            Tobira is an independent project — not a media company, not a startup.
            Just one person living in Japan, trying to share it honestly.
          </p>
        </div>
      </section>

      {/* Values */}
      <section className="max-w-6xl mx-auto px-4 pb-20">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {VALUES.map((v) => (
            <div
              key={v.title}
              className="bg-white rounded-2xl p-8 border border-stone-200"
            >
              <div className="inline-flex items-center justify-center w-11 h-11 rounded-xl bg-red-50 text-red-600 mb-4">
                <v.icon size={20} />
              </div>
              <h3 className="font-semibold text-stone-900 text-lg mb-2">{v.title}</h3>
              <p className="text-stone-500 text-sm leading-relaxed">{v.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="max-w-3xl mx-auto px-4 pb-24 text-center">
        <h2 className="text-2xl font-bold text-stone-900 mb-3">
          Questions or feedback?
        </h2>
        <p className="text-stone-500 mb-6">
          We read every message. Seriously.
        </p>
        <Link
          href="/contact"
          className="inline-flex items-center gap-2 bg-red-600 hover:bg-red-700 text-white font-semibold px-8 py-3.5 rounded-full transition-colors"
        >
          Get in touch
        </Link>
      </section>
    </div>
  );
}
