import type { Metadata } from 'next';
import Link from 'next/link';
import Image from 'next/image';
import { Check, Lock, MapPin, Sparkles } from 'lucide-react';
import { createClient } from '@/lib/supabase/server';
import PricingCTA from '@/components/PricingCTA';

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'Tobira Pro — Unlock All of Japan',
  description: 'Get full access to premium spots across all 47 prefectures. Insider tips, hidden highlights, and unlimited AI trip plans for $4.99/month.',
};

const FEATURES = [
  'Access all premium spots across Japan',
  'Hidden local tips & insider timing',
  'Full location maps for every spot',
  'Access & duration details',
  'Highlights from locals who know',
  'All future premium spots included',
];

const FAQ_ITEMS = [
  {
    q: 'Is there really a free plan?',
    a: 'Yes. The free plan gives you full access to all regions and spot browsing across Japan, plus one AI-generated trip itinerary. No credit card required.',
  },
  {
    q: 'Can I cancel anytime?',
    a: 'Yes — cancel anytime from your account settings. Your Pro access continues until the end of your current billing period, and you won\'t be charged again.',
  },
  {
    q: 'What exactly is a "premium spot"?',
    a: 'Premium spots include insider tips, hidden highlights, best-time-to-visit advice, and detailed access notes that go beyond what\'s in standard guidebooks. Every one has been hand-picked and verified.',
  },
  {
    q: 'How does the AI trip planner work?',
    a: 'Tell the planner your dates, interests, and travel pace. It generates a day-by-day itinerary using Tobira\'s curated spot database. Free users get one plan; Pro users get unlimited plans.',
  },
  {
    q: 'Is this really curated by a local?',
    a: 'Yes. Tobira is run by one person living in Japan. Every spot has been personally visited or carefully verified — nothing is scraped from review sites or generated by AI.',
  },
  {
    q: 'How often is content updated?',
    a: 'New spots and tips are added monthly. Pro members automatically get access to new premium spots as soon as they\'re published.',
  },
];

const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: FAQ_ITEMS.map(({ q, a }) => ({
    '@type': 'Question',
    name: q,
    acceptedAnswer: { '@type': 'Answer', text: a },
  })),
};

export default async function PricingPage({
  searchParams,
}: {
  searchParams: Promise<{ success?: string }>;
}) {
  const { success } = await searchParams;

  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  let isPro = false;
  if (user) {
    const { data: sub } = await supabase
      .from('subscriptions')
      .select('status')
      .eq('user_id', user.id)
      .single();
    isPro = sub?.status === 'active';
  }

  // Fetch a sample of premium spots for the preview grid
  const { data: premiumSpots, count: premiumCount } = await supabase
    .from('spots')
    .select('id, name, prefecture, image_url', { count: 'exact' })
    .eq('is_premium', true)
    .limit(8);

  return (
    <div className="max-w-2xl mx-auto px-4 py-16">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      {/* Success banner */}
      {success && (
        <div className="mb-8 bg-emerald-50 border border-emerald-200 rounded-xl px-4 py-3 text-emerald-700 text-sm font-medium text-center">
          Welcome to Tobira Pro! Your subscription is active.
        </div>
      )}

      {/* Header */}
      <div className="text-center mb-10">
        <div className="inline-flex items-center gap-2 bg-red-50 text-red-600 text-sm font-medium px-4 py-2 rounded-full mb-4">
          <Lock size={14} />
          Tobira Pro
        </div>
        <h1 className="text-4xl font-bold text-stone-900 mb-3">
          Unlock Japan&apos;s Hidden Gems
        </h1>
        <p className="text-stone-500 text-lg">
          Go beyond the guidebook. Get access to handpicked secret spots across all 47 prefectures — curated by locals who have actually been there.
        </p>
      </div>

      {/* Premium spots preview */}
      {premiumSpots && premiumSpots.length > 0 && (
        <div className="mb-10">
          <p className="text-center text-sm font-semibold text-stone-500 uppercase tracking-wider mb-4">
            What Pro unlocks
          </p>
          <div className="grid grid-cols-4 gap-2 mb-3">
            {premiumSpots.map((spot) => (
              <div key={spot.id} className="relative aspect-square rounded-xl overflow-hidden bg-stone-100">
                {spot.image_url && (
                  <Image
                    src={spot.image_url}
                    alt={spot.name}
                    fill
                    unoptimized
                    className="object-cover"
                    sizes="160px"
                  />
                )}
                <div className="absolute inset-0 bg-gradient-to-t from-stone-900/70 to-transparent" />
                <div className="absolute bottom-1.5 left-1.5 right-1.5">
                  <p className="text-white text-xs font-semibold leading-tight line-clamp-2">{spot.name}</p>
                  <p className="text-white/60 text-[10px]">{spot.prefecture}</p>
                </div>
                <div className="absolute top-1.5 right-1.5 bg-amber-400 text-stone-900 text-[10px] font-bold px-1.5 py-0.5 rounded-full flex items-center gap-0.5">
                  <Lock size={8} />
                  Pro
                </div>
              </div>
            ))}
          </div>
          <p className="text-center text-xs text-stone-400">
            {premiumCount && premiumCount > 8 ? `+ ${premiumCount - 8} more premium spots across all 47 prefectures` : 'Premium spots across all 47 prefectures'}
          </p>
        </div>
      )}

      {/* Pricing card */}
      <div className="bg-white border border-stone-200 rounded-2xl p-8 mb-6">
        {/* Price */}
        <div className="text-center mb-8">
          <div className="flex items-baseline justify-center gap-1">
            <span className="text-5xl font-bold text-stone-900">$4.99</span>
            <span className="text-stone-400 text-lg">/ month</span>
          </div>
          <p className="text-stone-400 text-sm mt-1">Cancel anytime</p>
        </div>

        {/* Features */}
        <ul className="space-y-3 mb-8">
          {FEATURES.map((f) => (
            <li key={f} className="flex items-start gap-3">
              <div className="w-5 h-5 rounded-full bg-red-50 text-red-500 flex items-center justify-center shrink-0 mt-0.5">
                <Check size={12} strokeWidth={3} />
              </div>
              <span className="text-stone-700 text-sm">{f}</span>
            </li>
          ))}
        </ul>

        <PricingCTA isLoggedIn={!!user} isPro={isPro} />
      </div>

      {/* FAQ */}
      <div className="mb-6">
        <h2 className="text-lg font-semibold text-stone-900 mb-4">Common questions</h2>
        <div>
          {FAQ_ITEMS.map(({ q, a }) => (
            <details key={q} className="group border-t border-stone-100">
              <summary className="flex items-center justify-between gap-4 py-4 cursor-pointer list-none">
                <span className="font-medium text-stone-800 text-sm">{q}</span>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  className="shrink-0 text-stone-400 transition-transform duration-200 group-open:rotate-180"
                  aria-hidden="true"
                >
                  <path d="m6 9 6 6 6-6" />
                </svg>
              </summary>
              <p className="pb-4 text-stone-500 text-sm leading-relaxed">{a}</p>
            </details>
          ))}
          <div className="border-t border-stone-100" />
        </div>
      </div>

      {/* Preview links */}
      <div className="bg-stone-50 rounded-xl p-5 text-center">
        <p className="text-stone-500 text-sm mb-3">Want to see what's inside first?</p>
        <div className="flex items-center justify-center gap-4 text-sm">
          <Link
            href="/spots"
            className="flex items-center gap-1.5 text-stone-600 hover:text-red-600 transition-colors"
          >
            <MapPin size={13} />
            Browse all spots
          </Link>
          <span className="text-stone-300">·</span>
          <Link
            href="/plan"
            className="flex items-center gap-1.5 text-stone-600 hover:text-red-600 transition-colors"
          >
            <Sparkles size={13} />
            Try AI planner
          </Link>
        </div>
      </div>
    </div>
  );
}
