import type { ThemeSpec } from '@/types/instagram'

export const THEMES: ThemeSpec[] = [
  // Regional
  {
    theme_key: 'hokkaido-best',
    theme_title_ja: '北海道の絶景スポット5選',
    theme_title_en: 'Beyond Sapporo: 5 Scenic Spots Worth the Detour',
    tagline: 'For those who want Hokkaido beyond the postcard.',
    type: 'regional',
    region: 'hokkaido',
    requireCategories: ['nature'],
    maxCount: 5,
  },
  {
    theme_key: 'tohoku-nature',
    theme_title_ja: '東北の自然スポット5選',
    theme_title_en: '5 Tohoku Views Beyond the Tourist Trail',
    tagline: 'Tohoku, seen without a tour bus.',
    type: 'regional',
    region: 'tohoku',
    spotIds: [
      'zao-okama-crater',
      'oirase-gorge',
      'goshikinuma-lakes',
      'matsushima-bay',
      'naruko-gorge',
    ],
    maxCount: 5,
  },
  {
    theme_key: 'kanto-hidden',
    theme_title_ja: '関東の穴場スポット5選',
    theme_title_en: '5 Kanto Spots Most Visitors Miss',
    tagline: 'The Kanto spots that most itineraries skip.',
    type: 'regional',
    region: 'kanto',
    spotIds: [
      'hitachi-seaside-park',
      'ashikaga-flower-park',
      'oarai-isosaki-shrine',
      'nagatoro-gorge',
      'fukuroda-falls',
    ],
    maxCount: 5,
  },
  {
    theme_key: 'kansai-history',
    theme_title_ja: '関西の歴史スポット5選',
    theme_title_en: 'Beyond Kyoto: 5 Historic Gems in Kansai',
    tagline: 'Kansai history beyond the Kyoto crowds.',
    type: 'regional',
    region: 'kinki',
    spotIds: [
      'himeji-castle',
      'koyasan',
      'takeda-castle-ruins',
      'hikone-castle',
      'ise-jingu',
    ],
    maxCount: 5,
  },
  {
    theme_key: 'kyushu-best',
    theme_title_ja: '九州の絶景スポット5選',
    theme_title_en: '5 Kyushu Landscapes Worth Leaving Tokyo For',
    tagline: 'Kyushu, for travellers who stayed curious.',
    type: 'regional',
    region: 'kyushu',
    spotIds: [
      'takachiho-gorge',
      'yakushima-island',
      'aso-caldera',
      'yufuin-valley',
      'kokonoe-dream-bridge',
    ],
    maxCount: 5,
  },
  {
    theme_key: 'okinawa-ocean-views',
    theme_title_ja: '沖縄の海の絶景5選',
    theme_title_en: "5 Ocean Views That Show Okinawa's Real Colour",
    tagline: 'The ocean Okinawa is famous for — seen properly.',
    type: 'regional',
    region: 'okinawa',
    spotIds: [
      'kabira-bay',
      'cape-manzamo',
      'sunayama-beach',
      'east-hennazaki-cape',
      'irabu-bridge',
    ],
    maxCount: 5,
  },
  {
    theme_key: 'chugoku-gems',
    theme_title_ja: '中国地方の隠れた名所5選',
    theme_title_en: 'Top 5 Hidden Gems in Chugoku',
    tagline: 'A slower Japan, still waiting to be found.',
    type: 'regional',
    region: 'chugoku',
    spotIds: [
      'motonosumi-shrine',
      'tottori-sand-dunes',
      'shimanami-kaido',
      'tsunoshima-bridge',
      'adachi-museum',
    ],
    maxCount: 5,
  },
  {
    theme_key: 'shikoku-spiritual',
    theme_title_ja: '四国のパワースポット5選',
    theme_title_en: 'Top 5 Spiritual Spots in Shikoku',
    tagline: 'Where pilgrims walk and tourists rarely follow.',
    type: 'regional',
    region: 'shikoku',
    requireCategories: ['spiritual'],
    maxCount: 5,
  },

  // Seasonal
  {
    theme_key: 'spring-nature',
    theme_title_ja: '春に行きたい絶景スポット5選',
    theme_title_en: 'Top 5 Scenic Spots to Visit in Spring',
    tagline: 'Spring in Japan, beyond the cherry blossom forecast.',
    type: 'seasonal',
    season: 'spring',
    spotIds: [
      'yoshino-cherry',
      'hanamiyama-park',
      'ashikaga-flower-park',
      'philosophers-path',
      'hirosaki-castle',
    ],
    maxCount: 5,
  },
  {
    theme_key: 'summer-nature',
    theme_title_ja: '夏に行きたい絶景スポット5選',
    theme_title_en: 'Top 5 Scenic Spots to Visit in Summer',
    tagline: 'Where to be in Japan when summer actually hits.',
    type: 'seasonal',
    season: 'summer',
    spotIds: [
      'furano-lavender-farm',
      'yonaha-maehama',
      'fujisan-world-heritage',
      'niyodo-river',
      'nikko-national-park-hiking',
    ],
    maxCount: 5,
  },
  {
    theme_key: 'autumn-foliage',
    theme_title_ja: '秋の紅葉スポット5選',
    theme_title_en: 'Top 5 Autumn Foliage Spots',
    tagline: 'Autumn colour, away from the photo crowds.',
    type: 'seasonal',
    season: 'autumn',
    spotIds: [
      'naruko-gorge',
      'oirase-gorge',
      'takeda-castle-ruins',
      'metasequoia-avenue',
      'yufuin-valley',
    ],
    maxCount: 5,
  },
  {
    theme_key: 'winter-onsen',
    theme_title_ja: '冬の秘湯5選',
    theme_title_en: '5 Winter Onsen Worth Braving the Cold For',
    tagline: 'Japan in winter — the version worth braving the cold for.',
    type: 'seasonal',
    season: 'winter',
    spotIds: [
      'ginzan-onsen',
      'noboribetsu-jigokudani',
      'beppu-hells',
      'jigokudani-monkey-park',
      'myoko-kogen',
    ],
    maxCount: 5,
  },

  // Category
  {
    theme_key: 'best-onsen',
    theme_title_ja: '日本の名湯5選',
    theme_title_en: 'Top 5 Hot Spring Resorts in Japan',
    tagline: 'Hot springs that justify the journey.',
    type: 'category',
    category: 'onsen',
    spotIds: [
      'ginzan-onsen',
      'beppu-hells',
      'kusatsu-onsen',
      'arima-onsen',
      'yamanaka-onsen',
    ],
    maxCount: 5,
  },
  {
    theme_key: 'spiritual-gems',
    theme_title_ja: '日本の秘境パワースポット5選',
    theme_title_en: 'Top 5 Mystical Power Spots in Japan',
    tagline: "Japan's power spots — the ones guidebooks don't index.",
    type: 'category',
    category: 'spiritual',
    spotIds: [
      'osorezan',
      'dewa-sanzan',
      'kumano-kodo',
      'eiheiji-temple',
      'nachi-falls',
    ],
    maxCount: 5,
  },
  {
    theme_key: 'food-adventures',
    theme_title_ja: '食で旅する日本5選',
    theme_title_en: 'Top 5 Food Destinations in Japan',
    tagline: 'Eating through Japan, region by region.',
    type: 'category',
    category: 'food',
    maxCount: 5,
  },
  {
    theme_key: 'history-journey',
    theme_title_ja: '日本の歴史スポット5選',
    theme_title_en: 'Top 5 Historical Sites in Japan',
    tagline: "Japan's history, beyond the obvious stops.",
    type: 'category',
    category: 'history',
    spotIds: [
      'hiroshima-peace-memorial',
      'himeji-castle',
      'shirakawa-go',
      'nikko-toshogu',
      'hashima-island',
    ],
    maxCount: 5,
  },

  // Access
  {
    theme_key: 'car-free-spots',
    theme_title_ja: '車なしで行ける絶景5選',
    theme_title_en: '5 Stunning Spots You Can Reach Without a Car',
    tagline: "Japan's most scenic spots — no car needed.",
    type: 'access',
    accessKeywords: ['JR', '電車', 'バス', 'train', 'bus', '徒歩', 'walk'],
    maxCount: 5,
  },

  // New themes
  {
    theme_key: 'shikoku-gems',
    theme_title_ja: '5 hidden gems in Shikoku',
    theme_title_en: '5 hidden gems in Shikoku',
    tagline: 'Shikoku beyond the usual',
    type: 'regional',
    region: 'shikoku',
    spotIds: ['dogo-onsen', 'niyodo-river', 'shimanto-river', 'naruto-whirlpools', 'naoshima-island'],
    maxCount: 5,
  },
  {
    theme_key: 'chugoku-visits',
    theme_title_ja: '5 places worth visiting in Chugoku',
    theme_title_en: '5 places worth visiting in Chugoku',
    tagline: 'Chugoku highlights',
    type: 'regional',
    region: 'chugoku',
    spotIds: ['itsukushima-shrine', 'tsunoshima-bridge', 'tottori-sand-dunes', 'izumo-taisha', 'kurashiki-bikan'],
    maxCount: 5,
  },
  {
    theme_key: 'train-friendly-japan',
    theme_title_ja: 'Best train-friendly trips in Japan',
    theme_title_en: 'Best train-friendly trips in Japan',
    tagline: 'Accessible by train',
    type: 'access',
    accessKeywords: ['train', 'JR', 'railway'],
    spotIds: ['himeji-castle', 'hitachi-seaside-park', 'itsukushima-shrine', 'matsumoto-castle', 'nikko-toshogu'],
    maxCount: 5,
  },
  {
    theme_key: 'summer-japan',
    theme_title_ja: 'Summer in Japan: 5 places actually worth it',
    theme_title_en: 'Summer in Japan: 5 places actually worth it',
    tagline: 'Beat the summer heat',
    type: 'seasonal',
    season: 'summer',
    spotIds: ['yonaha-maehama', 'furano-lavender-farm', 'fujisan-world-heritage', 'karuizawa', 'shimanto-river'],
    maxCount: 5,
  },
  {
    theme_key: 'autumn-tohoku',
    theme_title_ja: 'Autumn in Tohoku: 5 places beyond the usual',
    theme_title_en: 'Autumn in Tohoku: 5 places beyond the usual',
    tagline: 'Autumn foliage in Tohoku',
    type: 'seasonal',
    season: 'autumn',
    spotIds: ['naruko-gorge', 'hirosaki-castle', 'oirase-gorge', 'zao-okama-crater', 'goshikinuma-lakes'],
    maxCount: 5,
  },
  {
    theme_key: 'food-towns-japan',
    theme_title_ja: '5 food towns in Japan beyond Osaka',
    theme_title_en: '5 food towns in Japan beyond Osaka',
    tagline: 'Culinary destinations',
    type: 'category',
    category: 'food',
    spotIds: ['otaru-canal', 'matsusaka-beef-town', 'noto-peninsula', 'hotaruika-firefly-squid', 'nagasaki-chinatown'],
    maxCount: 5,
  },
  {
    theme_key: 'rainy-day-japan',
    theme_title_ja: 'Rainy-day-friendly places in Japan',
    theme_title_en: 'Rainy-day-friendly places in Japan',
    tagline: 'Indoor & covered attractions',
    type: 'category',
    spotIds: ['akiyoshido-cave', 'churaumi-aquarium', 'ryusendo-cave', 'fukui-dinosaur-museum', 'sapporo-beer-garden'],
    maxCount: 5,
  },
  {
    theme_key: 'underrated-nature',
    theme_title_ja: 'Underrated regions in Japan for nature lovers',
    theme_title_en: 'Underrated regions in Japan for nature lovers',
    tagline: 'Off the beaten path',
    type: 'category',
    category: 'nature',
    spotIds: ['taketomi-island', 'tateyama-murodo', 'sado-island', 'oze-marshland', 'kushiro-wetlands'],
    maxCount: 5,
  },
  {
    theme_key: 'island-trips-japan',
    theme_title_ja: 'Best island trips in Japan beyond Okinawa',
    theme_title_en: 'Best island trips in Japan beyond Okinawa',
    tagline: 'Island adventures',
    type: 'regional',
    spotIds: ['yakushima-island', 'shiretoko-peninsula', 'naoshima-island', 'shodoshima-island', 'goto-islands'],
    maxCount: 5,
  },
  {
    theme_key: 'second-trip-japan',
    theme_title_ja: 'Where to go in Japan for a second trip',
    theme_title_en: 'Where to go in Japan for a second trip',
    tagline: 'Beyond the usual first-trip destinations',
    type: 'regional',
    spotIds: ['kanazawa-21-museum', 'itsukushima-shrine', 'kokusai-dori', 'hakodate-mountain-night-view', 'ise-jingu'],
    maxCount: 5,
  },
]

export function getThemeByKey(key: string): ThemeSpec | undefined {
  return THEMES.find(t => t.theme_key === key)
}
