-- 全スポット 営業時間・tips ファクトチェック結果 一括適用
-- 参照: spot-factcheck-hours-tips-*.md（地域別報告書）
-- 対象: opening_hours, tips のみ（admission/access は別適用済み）

UPDATE spots SET opening_hours = 'Shrine grounds: 24 hours; inner shrine: 5:00–19:00; Treasure Hall: 9:00–16:30, closed last Wed–Thu of each month and Dec 25–31' WHERE id = 'atsuta-jingu';
UPDATE spots SET opening_hours = 'Town always accessible; Tokoname Pottery Walking Trail: daylight hours; Tokoname Toki-no-Mori (pottery museum): 9:00–17:00, closed Mon' WHERE id = 'tokoname-pottery-town';
UPDATE spots SET opening_hours = 'Castle: 9:00–17:00 (Mar–May, Sep–Oct), 8:00–18:00 (Jun–Aug), 9:00–16:30 (Nov–Feb); closed Dec 20–Jan 10; town always accessible' WHERE id = 'gujo-hachiman';
UPDATE spots SET opening_hours = '9:00–17:00 (last entry 16:30); closed Tue (open if holiday), day after holidays, Dec 29–Jan 3' WHERE id = 'ogaki-castle';
UPDATE spots SET opening_hours = 'Seki Cutlery Hall (Seki Hamono Kaikan): 9:00–17:00; closed Dec 29–Jan 1 only' WHERE id = 'seki-blade-town';
UPDATE spots SET opening_hours = 'Mikimoto Pearl Island: 9:00–17:00 (hours vary by season; 3-day closure from 2nd Tue in Dec); boat tours Apr–Oct' WHERE id = 'ago-bay';
UPDATE spots SET opening_hours = 'Summer (mid-Mar–Nov 30): 8:30–17:00; winter: 9:00–16:30; closed Thu (Jan–mid-Mar) and Dec 29–31' WHERE id = 'akame-waterfalls';
UPDATE spots SET opening_hours = '9:30–17:00 (last entry 16:00) normally; 9:00–17:30 during GW and summer; open year-round' WHERE id = 'toba-aquarium';
UPDATE spots SET opening_hours = 'Apr–Oct: 8:30–17:00; Nov–Mar: 9:00–16:00; last entry 30 min before close; access may be restricted in heavy snow Dec–Feb' WHERE id = 'jigokudani-monkey-park';
UPDATE spots SET opening_hours = 'Boat tours: 10:00–16:00 (weather permitting); may close in rough weather' WHERE id = 'dogashima-caves';
UPDATE spots SET opening_hours = '7:30–19:00 (Mar–Jul, Sep–Nov); 7:30–20:00 (Aug, until 21:00 Aug 5–6); 7:30–18:00 (Dec–Feb). Closed Dec 30–31 and mid-Feb. Extended hours may require online reservation; check official site.' WHERE id = 'hiroshima-peace-museum';
UPDATE spots SET opening_hours = '9:00–18:00 (Apr–Sep); 9:00–17:00 (Oct–Mar). Closed Dec 29–Jan 3.' WHERE id = 'shukkei-en';
UPDATE spots SET opening_hours = 'Sunayu open-air bath: 24 hours (free, mixed; closed Wed morning for cleaning). Ryokan baths 24 hrs for guests.' WHERE id = 'yubara-onsen';
UPDATE spots SET opening_hours = 'Town always accessible. Ryugenji Mabu tunnel: 9:00–17:00 (Mar–Nov, last entry 16:50), 9:00–16:00 (Dec–Feb, last entry 15:50); closed Jan 1.' WHERE id = 'iwami-ginzan';
UPDATE spots SET opening_hours = 'Open year-round. Main approach 6:00–19:00 (same in all seasons). Check official site for any temporary changes.' WHERE id = 'izumo-taisha';
UPDATE spots SET opening_hours = '8:30–18:00 (Apr–Sep, last entry 17:30); 8:30–17:00 (Oct–Mar, last entry 16:30).' WHERE id = 'matsue-castle';
UPDATE spots SET opening_hours = '10:00–17:00 (weekdays); 10:00–20:00 (Fri/Sat/Sun/hols). Extended during peony and illumination events. Admission varies by season (from ¥1,000); check official site.' WHERE id = 'yuushien-garden';
UPDATE spots SET opening_hours = 'Summer (late Apr–mid-Oct): 9:30–17:15; Winter (mid-Nov–early Apr): 10:30–15:30; closed 8–25 Apr, 4–10 Nov, and 30 Dec–1 Jan.' WHERE id = 'asahiyama-zoo';
UPDATE spots SET opening_hours = 'Tower: 9:00–18:00 (ticket sales until 17:50); park always open.' WHERE id = 'goryokaku-fort';
UPDATE spots SET opening_hours = 'Lake: always accessible; Marimo Exhibition Center: 6:30–18:00 (Apr 29–Nov 30, hours vary by season); sightseeing cruise: late Apr–Nov.' WHERE id = 'akan-lake';
UPDATE spots SET opening_hours = 'Hell Valley: always open; Dai-ichi Takimotokan day onsen: 9:00–18:00 (reception), exit by 21:00.' WHERE id = 'noboribetsu-jigokudani';
UPDATE spots SET opening_hours = 'Open 24 hours (park); TV Tower 9:00–22:00 (last entry 21:50).' WHERE id = 'sapporo-odori-park';
UPDATE spots SET opening_hours = 'Ferries from Wakkanai: e.g. 6:30, 10:30, 14:50 (Jun–Sep, 3 sailings); fewer in other months; limited winter service.' WHERE id = 'rebun-island';
UPDATE spots SET opening_hours = 'Beer Garden restaurants: 11:30–22:00 (last order 21:30); closed 31 Dec; check website for other closures.' WHERE id = 'sapporo-beer-garden';
UPDATE spots SET opening_hours = 'Day bathing: typically 16:00–20:00 at Seifuso (varies by ryokan); call ahead to confirm.' WHERE id = 'awara-onsen';
UPDATE spots SET opening_hours = 'Udatsu no Kogeikan (paper museum): 9:30–17:00 (last entry 16:30), closed Tue; papermaking workshops on-site (advance reservation).' WHERE id = 'echizen-washi-paper';
UPDATE spots SET opening_hours = '8:30–16:30 (last entry 16:00) year-round; earlier access for zazen participants.' WHERE id = 'eiheiji-temple';
UPDATE spots SET opening_hours = '9:00–17:00 (last entry 16:30); closed 2nd and 4th Wed (open in summer holidays and when Wed is a holiday).' WHERE id = 'fukui-dinosaur-museum';
UPDATE spots SET opening_hours = 'Restored town: 9:00–17:00 (last entry 16:30), closed New Year; museum closed Mon. Grounds accessible free year-round.' WHERE id = 'ichijodani-ruins';
UPDATE spots SET tips = 'About 50,000 azalea bushes (including 31,400 Hirado azaleas) covering a hillside in the castle park — almost entirely unknown outside of Fukui. The variety of colours (white, pink, red, purple) at full bloom is extraordinary. Combine with Maruoka Castle (20 min by car) and Eiheiji Temple for a full Fukui day.' WHERE id = 'nishiyama-park-azalea';
UPDATE spots SET opening_hours = 'City always accessible; Wakasa Fureai Market: 9:00–18:00 (17:00 in winter); Ukanoya: check locally (typically Tue–Sun).' WHERE id = 'wakasa-obama-food';
UPDATE spots SET opening_hours = 'Cliffs: always accessible; sightseeing boats: Apr–Oct 9:00–16:00, Nov–Mar 9:00–15:30 (closed Wed, late Dec–late Jan; weather permitting).' WHERE id = 'tojinbo-cliffs';
UPDATE spots SET opening_hours = 'District always accessible; Shima teahouse: 9:30–17:30 (9:30–17:00 Dec–Feb).' WHERE id = 'higashi-chaya-district';
UPDATE spots SET opening_hours = 'Free Public Zone: 9:00–22:00; Exhibition Zone: 10:00–18:00 (Fri–Sat until 20:00), closed Mon.' WHERE id = 'kanazawa-21-museum';
UPDATE spots SET opening_hours = 'Tours: 9:00–16:30 (9:00–16:00 late Nov–early Mar); advance reservation required by phone.' WHERE id = 'myoryuji-ninja-temple';
UPDATE spots SET opening_hours = 'Most stalls: 9:00–17:00 (some earlier); many closed Wed (market holiday); some also closed Sun/holidays.' WHERE id = 'omicho-market';
UPDATE spots SET opening_hours = 'Shrine: 9:00–16:00 (extended hours New Year); mountain trails year-round (best May–Nov).' WHERE id = 'shirayama-hime-shrine';
UPDATE spots SET opening_hours = 'Main bathhouse (Kiku no Yu): 6:45–22:00, closed 2nd and 4th Tue; shops about 10:00–18:00.' WHERE id = 'yamanaka-onsen';
UPDATE spots SET opening_hours = '9:00–16:30 (closed 17:00); closed New Year and Mon (Dec–Feb only; open daily Mar–Nov).' WHERE id = 'joetsu-dinosaur-museum';
UPDATE spots SET opening_hours = 'Tasting rooms: typically 9:00–17:00; Ponshukan at Niigata Station: shop 9:00–21:00, tasting 9:30–20:30.' WHERE id = 'niigata-sake-breweries';
UPDATE spots SET opening_hours = 'Nishikigoi no Sato (Koi museum): 9:00–17:00 (9:00–17:00 Dec–Feb); closed New Year only; koi farms viewable from roads.' WHERE id = 'ojiya-koi-city';
UPDATE spots SET opening_hours = 'Village always accessible; Ainokura Folklore Museum: 8:30–17:00 when open (currently under temporary closure; check for 2026 reopening).' WHERE id = 'gokayama-village';
UPDATE spots SET opening_hours = 'Market: 8:30–18:00; restaurants: 11:00–18:00 (some until 20:00).' WHERE id = 'ikejiri-fish-market';
UPDATE spots SET opening_hours = '9:30–18:00 (Fri–Sat until 20:00, last entry 30 min before close); closed 1st and 3rd Wed and New Year.' WHERE id = 'toyama-glass-art';
UPDATE spots SET opening_hours = '9:00–16:30 (9:00–16:00 Dec 10–Jan 31); open daily; admission ¥500.' WHERE id = 'zuiryuji-temple';
UPDATE spots SET opening_hours = 'Island accessible year-round; Naruto whirlpool boat tours run year-round (departures roughly hourly; check tide table for best viewing).' WHERE id = 'awaji-island';
UPDATE spots SET opening_hours = 'Mountain: year-round; Rokko Cable: 7:00–21:00 (approx. every 20–40 min); Arima Ropeway: connects to Arima Onsen.' WHERE id = 'rokko-mountain';
UPDATE spots SET opening_hours = 'Spring (Mar–May): 8:00–18:00; Summer/Autumn (Jun–early Dec): 5:00–17:00; Winter (early Dec–3 Jan): 10:00–15:00; closed 4 Jan–end Feb.' WHERE id = 'takeda-castle-ruins';
UPDATE spots SET opening_hours = 'Area always accessible; breweries: typically 9:30–16:30 (varies); Gekkeikan Okura Sake Museum: 9:30–16:30 (last entry 16:00), closed Obon and year-end / New Year.' WHERE id = 'fushimi-sake-district';
UPDATE spots SET opening_hours = 'Garden (Honbo): 9:00–16:00 (Dec 8–Mar 31: 9:00–15:30); temple grounds: check separate hours for Tennon-kyo and other areas.' WHERE id = 'tofukuji-garden';
UPDATE spots SET opening_hours = '6:30–17:30 (Mar–Oct); 7:00–17:00 (Nov–Feb); inner sanctuary (special visit): 9:00–16:00.' WHERE id = 'kasuga-taisha';
UPDATE spots SET opening_hours = '8:30–16:30 (Apr–Sep), 8:30–16:00 (Oct–Mar); last entry 30 min before close; outer grounds: always accessible.' WHERE id = 'shitennoji-temple';
UPDATE spots SET opening_hours = 'Falls: always visible; Seiganto-ji Pagoda viewpoint: 9:00–16:00 (last entry 15:40); Kumano Nachi Taisha: 6:00–18:00 for general visit; formal visit / treasure hall: 8:30–16:30 (check official site).' WHERE id = 'nachi-falls';
UPDATE spots SET opening_hours = 'Beach: always open; Saki-no-Yu (cliff-top public bath): seasonal hours, e.g. Oct–Mar 8:00–17:00, Apr–Jun & Sep 8:00–18:00, Jul–Aug 7:00–19:00; no regular weekly closing (check for maintenance).' WHERE id = 'shirahama-beach';
UPDATE spots SET opening_hours = 'Day bath: typically 8:00–22:00 (varies by facility); Kinsen (Kin-no-Yu): 8:00–22:00, closed 2nd & 4th Tue; Ginsen (Gin-no-Yu): 9:00–21:00, closed 1st & 3rd Tue.' WHERE id = 'arima-onsen';
UPDATE spots SET opening_hours = 'Village always accessible; 7 public bathhouses: 7:00–23:00 or 13:00–21:00 / 15:00–23:00 depending on sotoyu; each has a different weekly closing day — check the official schedule.' WHERE id = 'kinosaki-onsen';
UPDATE spots SET opening_hours = 'District always accessible; individual ijinkan: e.g. Weathercock House 9:00–17:00 (closed 3rd Tue); hours vary by house.' WHERE id = 'kobe-kitano';
UPDATE spots SET opening_hours = 'Lighthouse: 8:30–16:00 (no regular closing day); fish market open from early morning' WHERE id = 'boso-fureai-trail';
UPDATE spots SET opening_hours = 'Open 24 hours; lifeguard stations Jul–Aug 9:00–16:00 (hours may vary on weekends/holidays)' WHERE id = 'kujukurihama-beach';
UPDATE spots SET opening_hours = '9:30–16:30 weekdays, 9:00–17:00 weekends/holidays (Feb–Nov); shorter hours Dec–Jan; seasonal events year-round' WHERE id = 'mother-farm';
UPDATE spots SET opening_hours = 'Village and Yubatake always accessible; Netsunoyu show: 6 performances daily (9:30, 10:00, 10:30, 15:30, 16:00, 16:30), closed Wed for experience only' WHERE id = 'kusatsu-onsen';
UPDATE spots SET opening_hours = 'Ropeway: 9:00–17:00 (9:00–16:00 Nov 16–Feb 15); Nihonji Temple: 9:00–16:00 (last entry 15:00)' WHERE id = 'nokogiriyama-ropeway';
UPDATE spots SET opening_hours = 'Park: always open; National Museum of Japanese History (in park): 9:30–17:00, closed Mon' WHERE id = 'sakura-castle-ruins';
UPDATE spots SET opening_hours = '9:00–17:00 (last entry 16:00); shorter hours some winter weekdays; Saturday night event 18:00–20:00; open year-round (maintenance closures in Jun and Dec)' WHERE id = 'ibaraki-aqua-world';
UPDATE spots SET opening_hours = '8:00–18:00 (May–Oct); 8:00–17:00 (Nov); 9:00–17:00 (Dec–Apr); evening illumination on some autumn nights' WHERE id = 'fukuroda-falls';
UPDATE spots SET opening_hours = '9:30–17:00 (Mar–mid-Jul, Sep–Oct); 9:30–18:00 (mid-Jul–Aug); 9:30–16:30 (Nov–Feb); closed Tue (or following weekday when Tue is national holiday); daily opening during peak seasons' WHERE id = 'hitachi-seaside-park';
UPDATE spots SET opening_hours = 'Great Buddha: 8:00–17:30 (Apr–Sep), 8:00–17:00 (Oct–Mar); Hase-dera: 8:00–17:00, close 17:30 (Apr–Jun), 8:00–16:30, close 17:00 (Jul–Mar)' WHERE id = 'kamakura-great-buddha';
UPDATE spots SET opening_hours = '9:00–17:00 (last entry 16:30); 9:00–18:00 weekends/holidays Jun–Aug (last entry 17:30); park always open' WHERE id = 'odawara-castle';
UPDATE spots SET opening_hours = '9:30–17:00 (Mar–Oct); 9:30–16:30 (Nov); 9:30–16:00 (Dec–Feb); closed Mon from early Jan to end Feb and New Year''s Day' WHERE id = 'higashi-matsuyama-hike';
UPDATE spots SET opening_hours = '10:00–17:00 (last entry 16:30); closed Tue and year-end' WHERE id = 'saitama-railway-museum';
UPDATE spots SET opening_hours = '8:30–17:00 (last entry 16:30); open daily; entry ¥300' WHERE id = 'yoshimi-caves';
UPDATE spots SET opening_hours = '10:00–17:00 normally; extended during wisteria (e.g. 8:00–20:30) and illumination (e.g. 15:30–21:00); seasonal closures — check website' WHERE id = 'ashikaga-flower-park';
UPDATE spots SET opening_hours = '9:00–17:00 (Apr–Oct); 9:00–16:00 (Nov–Mar); last entry 30 min before closing' WHERE id = 'nikko-toshogu';
UPDATE spots SET opening_hours = '9:30–17:00 weekdays, 9:30–17:30 weekends/holidays (Mar–Sep); 9:30–16:30 (Oct–Feb); last entry 45 min before closing (set ticket); extended during illumination events' WHERE id = 'ushiku-daibutsu';
UPDATE spots SET opening_hours = '6:00–17:00; azalea garden: 1–30 Apr, 9:00–17:30, ¥500–1,000 depending on bloom' WHERE id = 'nezu-shrine';
UPDATE spots SET opening_hours = '6:00 or 6:30–18:30 (Dec–Mar), 19:00 (Apr, May, Sep–Nov), 19:30 (Jun–Aug); grounds effectively always accessible. Check official site for exact dates.' WHERE id = 'dazaifu-tenmangu';
UPDATE spots SET opening_hours = 'Park: always open; Fukuoka Castle Museum (Mukashi Tanboukan) and Korokan Site Museum: 9:00–17:00, closed year-end and New Year (Dec 29–Jan 3).' WHERE id = 'fukuoka-castle-ruins';
UPDATE spots SET opening_hours = '10:00–18:00 (last entry 17:30); closed 4th Monday of each month (or next weekday if that Monday is a holiday), and Dec 29–31.' WHERE id = 'hakata-machiya-museum';
UPDATE spots SET opening_hours = 'Boat tours: Apr–Nov, 9:00–16:30 (weather permitting); cancellations frequent in rough weather.' WHERE id = 'keya-no-oto-cave';
UPDATE spots SET opening_hours = 'Reclining Buddha (main attraction): 9:00–17:00 (last entry 16:30); main hall and pilgrimage stamp office: 24 hours. Grounds accessible during daylight.' WHERE id = 'nanzoin-temple';
UPDATE spots SET opening_hours = '9:30–17:30 (Mar–Oct, last entry 1 hr before close); 9:30–17:00 (Nov–Feb). Closed Tuesdays in many periods (and some other days); check official calendar.' WHERE id = 'uminonakamichi-park';
UPDATE spots SET opening_hours = 'Mon–Sat approx. 8:00–18:00 (many shops close by 15:00); most stalls closed Sun and holidays. Visit early morning for best atmosphere.' WHERE id = 'yanagibashi-market';
UPDATE spots SET opening_hours = '9:00–17:00 (last entry 16:30); closed 1st Sun of Mar (Kagoshima Marathon).' WHERE id = 'sengan-en-garden';
UPDATE spots SET opening_hours = 'Saraku (sand bath facility): 8:30–21:00 (last entry 20:30) on weekends/holidays; weekdays 8:30–12:00 and 13:00–21:00. Open year-round; check for occasional maintenance closures (Jul, Dec).' WHERE id = 'ibusuki-sand-bath';
UPDATE spots SET opening_hours = 'Grounds: 24 hours. Offering counter (amulets, goshuin): 8:00–17:00.' WHERE id = 'kirishima-shrine';
UPDATE spots SET opening_hours = '8:30–17:00; staffed and full access Apr 1–Nov 30; Dec–Mar entry at own risk (no staff).' WHERE id = 'kikuchi-gorge';
UPDATE spots SET opening_hours = '9:00–17:00 (last entry 16:00; summer extended hours apply Jul–Aug); closed Dec 29. Restoration ongoing.' WHERE id = 'kumamoto-castle';
UPDATE spots SET opening_hours = 'Village accessible year-round; day-visitor rotenburo with nyuto tegata: 8:30–21:00 (varies by ryokan).' WHERE id = 'kurokawa-onsen';
UPDATE spots SET opening_hours = '9:00–17:00 (last entry 16:30); advance online reservation required. Closed Dec 28–Jan 3.' WHERE id = 'nabegataki-falls';
UPDATE spots SET opening_hours = 'Always open; facility and parking: 8:00–20:00 (Mar–Oct), 8:00–19:00 (Nov–Feb). Admission to viewing area ¥100.' WHERE id = 'cape-manzamo';
UPDATE spots SET opening_hours = 'Peninsula always open; lighthouse interior: 9:30–12:00 and 13:00–16:30 or 17:00 (afternoon varies by season and day; last entry 15 min before closing).' WHERE id = 'east-hennazaki-cape';
UPDATE spots SET opening_hours = '9:00–17:30 (last entry 16:00); open year-round.' WHERE id = 'gyokusendo-cave';
UPDATE spots SET opening_hours = '9:00–17:25 (last entry 17:00); open year-round.' WHERE id = 'himeyuri-museum';
UPDATE spots SET opening_hours = '8:00–22:00 (varies by stall); closed 4th Sun of each month (open daily in Dec). 2F restaurant last order 20:00.' WHERE id = 'makishi-market';
UPDATE spots SET opening_hours = '10:00–18:00 (last entry 17:30); open year-round.' WHERE id = 'nago-pineapple-park';
UPDATE spots SET opening_hours = '8:00–19:00 (May–Aug, last entry 18:30); 8:00–18:00 (Sep–Apr, last entry 17:30).' WHERE id = 'nakijin-castle';
UPDATE spots SET opening_hours = '8:30–18:30 (last entry 17:30). Extended hours in GW and summer; check official site. No regular closure until Mar 2027 (Dec closure under review).' WHERE id = 'churaumi-aquarium';
UPDATE spots SET opening_hours = 'Park and Cornerstone of Peace: always accessible. Museum: 9:00–17:00 (exhibition room entry until 16:30); closed 29 Dec–3 Jan and on designated closed days.' WHERE id = 'okinawa-peace-memorial-park';
UPDATE spots SET opening_hours = '9:00–18:00 (Apr–Sep, last entry 17:30); 9:00–17:30 (Oct–Mar, last entry 17:00); closed Wed (or following day if Wed is holiday/23 Jun).' WHERE id = 'shikinaen-garden';
UPDATE spots SET opening_hours = 'Free area: 8:00–19:30 (Apr–Jun, Oct–Nov), 8:00–20:30 (Jul–Sep), 8:00–18:30 (Dec–Mar). Paid area: 8:30–19:00 / 8:30–20:00 / 8:30–18:00 (last entry 30 min before closing).' WHERE id = 'shuri-castle';
UPDATE spots SET opening_hours = 'Ruins: open 24 hours, free. Yuntanza Museum: 9:00–18:00 (last entry 17:30); closed Wed and year-end.' WHERE id = 'zakimi-castle';
UPDATE spots SET opening_hours = 'Cape and lighthouse area always accessible on foot (about 20–25 min from car park); lighthouse interior not open to the public.' WHERE id = 'cape-sada';
UPDATE spots SET tips = 'The cape is the westernmost point of Shikoku. The clifftop path to the lighthouse offers strong views of the Seto Inland Sea and Kyushu on clear days. Sunset is ideal; the lighthouse can be viewed from outside only.' WHERE id = 'cape-sada';
UPDATE spots SET opening_hours = 'Honkan: 6:00–23:00 (last entry 22:30). Asuka-no-yu (annex): 6:00–23:00 (last entry 22:30).' WHERE id = 'dogo-onsen';
UPDATE spots SET tips = 'The Honkan is one of Japan''s oldest public bathhouses and said to be the inspiration for Spirited Away. It reopened fully after restoration (completed Dec 2024). Soak in the first-floor communal bath for the authentic experience; arriving at 6am lets you bathe with locals before tour groups. Confirm current facilities on the official site.' WHERE id = 'dogo-onsen';
UPDATE spots SET opening_hours = '9:00–17:00 (16:30 Dec–Jan, 17:30 Aug); ropeway 8:30–17:30 (17:00 Dec–Jan, 18:00 Aug); lift 8:30–17:00. Closed 3rd Wed Dec.' WHERE id = 'matsuyama-castle';
UPDATE spots SET opening_hours = 'Oyamazumi Shrine: sunrise–17:00; treasure hall: 9:00–16:30 (last entry 16:00). Island accessible year-round.' WHERE id = 'omishima-island';
UPDATE spots SET opening_hours = '9:00–17:00 (9:00–16:00 Nov–Feb); last entry 30 min before closing.' WHERE id = 'uwajima-castle';
UPDATE spots SET opening_hours = 'Grounds: 6:00–18:00; main hall (top of 785 steps): 7:00–17:00; inner shrine (Okusha): 9:00–16:30.' WHERE id = 'kotohiragu-shrine';
UPDATE spots SET opening_hours = 'Chichu Museum: 10:00–17:00 (10:00–18:00 Mar–Sep), closed Mon; Benesse Museum: 10:00–18:00, closed Mon; Art House Project: 10:00–16:30, closed Mon.' WHERE id = 'naoshima-island';
UPDATE spots SET opening_hours = 'Park (West Gate): seasonal, e.g. 5:30–19:00 Jun–Aug, 7:00–17:00 Dec–Jan; East Gate 7:00–18:00 (Apr–Sep), 8:30–17:00 (Oct–Mar). Castle turrets/gates: 8:30–17:00. Boat: 9:00–16:30. Closed Dec 29–31.' WHERE id = 'takamatsu-castle';
UPDATE spots SET opening_hours = 'Main hall (Kondo): 7:00–17:00. Dharma hall & treasure museum: 8:00–17:00 (last entry 16:30), ¥500.' WHERE id = 'zentsuji-temple';
UPDATE spots SET opening_hours = 'Cape and lighthouse exterior always accessible; lighthouse interior not regularly open to the public (occasional event-only access).' WHERE id = 'cape-ashizuri';
UPDATE spots SET opening_hours = 'Cape always open; lighthouse exterior only (interior open only during annual lighthouse festival, e.g. around Nov).' WHERE id = 'cape-muroto';
UPDATE spots SET opening_hours = 'Hall: 9:00–20:00 (9:00–18:00 Dec 21–27, Jan 2–11). Dance shows: 11:00, 14:00, 15:00, 16:00 (day), 20:00 (night). Museum: 9:00–17:00 (last entry 16:45). Closed 2nd Wed Feb/Jun/Sep/Dec, Dec 28–Jan 1.' WHERE id = 'awa-odori-hall';
UPDATE spots SET opening_hours = '9:30–17:00 (last entry 16:30). Closed 4th Mon (next day if holiday), Dec 28–31.' WHERE id = 'naruto-german-house';
UPDATE spots SET opening_hours = 'Uzu no Michi (walkway): 9:00–18:00 Mar–Sep (entry by 17:30), 9:00–17:00 Oct–Feb (entry by 16:30); extended in GW and summer. Boat tours by tide table. Closed 2nd Mon Mar/Jun/Sep/Dec.' WHERE id = 'naruto-whirlpools';
UPDATE spots SET opening_hours = '8:30–17:00 (8:30–16:30 Nov–Jan), last entry 30 min before closing; adventure course by advance booking.' WHERE id = 'ryugado-cave';
UPDATE spots SET opening_hours = 'Valley always accessible; vine bridge: 8:00–18:00 (Apr–Nov), 8:00–17:00 in winter (confirm locally).' WHERE id = 'iya-valley';
UPDATE spots SET opening_hours = '8:00–18:00 (approx. Apr–Nov), 8:00–17:00 in winter; last entry 30 min before closing.' WHERE id = 'kazurabashi-bridge';
UPDATE spots SET opening_hours = 'Gondola: 9:00–16:00 (last ascent 15:00) in winter tree-ice season (approx. Jan–early Mar); summer hiking Jul–Oct; gondola may run on weekends in summer.' WHERE id = 'moriyoshi-mountain';
UPDATE spots SET opening_hours = 'Peninsula: always accessible; Namahagekan Museum: 8:30–17:00; Shinzan Shrine: open during daylight.' WHERE id = 'oga-peninsula-namahage';
UPDATE spots SET opening_hours = 'Festival: 2nd Friday–Saturday of February (e.g. 13–14 Feb 2026); snow huts open 18:00–21:00.' WHERE id = 'yokote-kamakura';
UPDATE spots SET opening_hours = '9:00–17:00 (Apr 1–Nov 23); 7:00–21:00 during cherry festival (late Apr–early May); park free and open in winter (Nov 24–Mar 31).' WHERE id = 'hirosaki-castle';
UPDATE spots SET opening_hours = '9:00–19:00 (May–Aug, last entry 18:30); 9:00–18:00 (Sep–Apr, last entry 17:30). Closed 9–10 Aug (display change) and 31 Dec–1 Jan.' WHERE id = 'nebuta-museum-warasse';
UPDATE spots SET opening_hours = '9:00–17:00 (Oct–May); 9:00–18:00 (GW and Jun–Sep). Closed 4th Mon each month (next day if holiday), 30 Dec–1 Jan, and facility maintenance days.' WHERE id = 'sannai-maruyama';
UPDATE spots SET opening_hours = 'Typically 9:30–21:30 (weekends/holidays) or 10:00–21:30 (weekdays); last entry 1 hour before closing. Closed on occasional facility-wide closure days — check official calendar.' WHERE id = 'spa-resort-hawaiians';
UPDATE spots SET opening_hours = '8:30–17:00 (Oct–Apr); 8:30–18:00 (May–Sep). Last entry 30 min before closing. Closed during heavy rain.' WHERE id = 'ryusendo-cave';
UPDATE spots SET opening_hours = '8:00–17:00 (Feb–Nov); 8:30–15:30 (Dec–Jan, last entry 15:00).' WHERE id = 'zuiganji-temple';
UPDATE spots SET opening_hours = 'Mt Haguro pagoda area: 9:00–16:00; Mt Gassan: Jul–mid-Sep only (snow); Mt Yudono: Jun–early Nov.' WHERE id = 'dewa-sanzan';
