/**
 * AI Article Generator for tobira.app
 *
 * Usage:
 *   npx ts-node --project tsconfig.scripts.json scripts/generate-article.ts \
 *     --title "Best Ryokan in Tohoku" \
 *     --slug  "best-ryokan-tohoku" \
 *     --region "tohoku" \
 *     --brief "ターゲット: 2回目訪日者。独自視点: 東北の隠れた温泉宿。必須情報: ベストシーズン・アクセス・価格帯。"
 *
 * Required env vars (add to .env.local):
 *   ANTHROPIC_API_KEY
 *   NEXT_PUBLIC_SUPABASE_URL
 *   SUPABASE_SERVICE_ROLE_KEY
 *
 * After generation, review the draft in Supabase Studio, then publish with:
 *   curl -X POST https://tobira.app/api/blog/publish \
 *     -H "Content-Type: application/json" \
 *     -d '{"slug":"<slug>","secret":"<BLOG_PUBLISH_SECRET>"}'
 */

import Anthropic from '@anthropic-ai/sdk';
import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../.env.local') });

// --- CLI args ---
const args = process.argv.slice(2);
function getArg(name: string): string {
  const i = args.indexOf(`--${name}`);
  if (i === -1 || !args[i + 1]) throw new Error(`Missing --${name}`);
  return args[i + 1];
}

function getOptionalArg(name: string): string | undefined {
  const i = args.indexOf(`--${name}`);
  return (i !== -1 && args[i + 1]) ? args[i + 1] : undefined;
}

const title = getArg('title');
const slug = getArg('slug');
const region = getOptionalArg('region');
const brief = getOptionalArg('brief');

// --- Sample article for few-shot context ---
const SAMPLE_ARTICLE = {
  title: 'Best Places in Japan Beyond Tokyo',
  intro: 'Most first-time visitors to Japan spend their entire trip in Tokyo, Kyoto, and Osaka. Those cities are worth visiting — but they represent a tiny fraction of what Japan has to offer. The country has 47 prefectures, each with its own food, dialect, landscape, and character. Here are the destinations that reward the effort of going further.',
  sections: [
    {
      heading: 'Kanazawa — The Kyoto Nobody Told You About',
      body: 'On the Sea of Japan coast, Kanazawa was one of the few major cities never bombed during World War II. The result is an intact old quarter of samurai residences, geisha districts, and teahouses that feels genuinely lived-in rather than preserved for tourism.\n\nKenroku-en, one of Japan\'s three great gardens, is worth the visit alone — but the real draw is wandering the Higashi Chaya district at dusk, or finding a counter seat in the Omicho market fish hall for a bowl of fresh seafood on rice.',
    },
  ],
  ctaHeading: 'Find the Japan that fits you',
  ctaBody: 'Answer a few questions about what draws you to Japan — nature, history, food, or onsen — and we\'ll match you with the spots that fit your style.',
};

const SYSTEM_PROMPT = `You are writing for tobira.app — a Japan travel guide for independent travellers who want to go beyond the tourist trail. The tone is:
- Confident and editorial, not listicle-generic
- Specific: real place names, actual details, honest about what makes a place worth visiting
- British/international English spelling (travelling, colour, favour)
- No filler phrases like "nestled", "breathtaking", "must-visit", "hidden gem"
- Each section heading should be evocative, not just a place name

Write content that would make a seasoned Japan traveller think "yes, exactly" — not content that reads like it was generated by AI.`;

interface ArticleOutput {
  description: string;
  read_minutes: number;
  cover_image: string;
  intro: string;
  sections: { heading: string; body: string }[];
  cta_heading: string;
  cta_body: string;
}

async function main() {
  const anthropicKey = process.env.ANTHROPIC_API_KEY;
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!anthropicKey) throw new Error('ANTHROPIC_API_KEY not set in .env.local');
  if (!supabaseUrl || !supabaseKey) throw new Error('Supabase env vars not set in .env.local');

  console.log(`\nGenerating article: "${title}" (${slug})\n`);

  const anthropic = new Anthropic({ apiKey: anthropicKey });

  const message = await anthropic.messages.create({
    model: 'claude-opus-4-6',
    max_tokens: 4096,
    system: SYSTEM_PROMPT,
    messages: [
      {
        role: 'user',
        content: `Here is a sample article showing the tone and structure we use:

TITLE: ${SAMPLE_ARTICLE.title}
INTRO: ${SAMPLE_ARTICLE.intro}
SECTION 1 HEADING: ${SAMPLE_ARTICLE.sections[0].heading}
SECTION 1 BODY: ${SAMPLE_ARTICLE.sections[0].body}
CTA HEADING: ${SAMPLE_ARTICLE.ctaHeading}
CTA BODY: ${SAMPLE_ARTICLE.ctaBody}

---

${brief ? `Article brief — follow this closely:\n${brief}\n\n` : ''}Now write a full article for: "${title}"
${region ? `Region focus: ${region}` : ''}

Return ONLY valid JSON matching this exact schema (no markdown, no explanation):
{
  "description": "SEO meta description, 140-160 chars",
  "read_minutes": <integer 5-10>,
  "cover_image": "https://images.unsplash.com/photo-XXXXXXXXXXXXXXXXX?w=1200&q=80",
  "intro": "2-3 sentence lead paragraph",
  "sections": [
    {
      "heading": "Section heading",
      "body": "2-3 paragraphs separated by \\n\\n",
      "spot_query": { "address_contains": "CityName", "limit": 3 },
      "section_link": { "text": "Explore CityName", "href": "/guides/prefecture-lowercase" }
    }
  ],
  "cta_heading": "Short CTA headline",
  "cta_body": "1-2 sentence CTA description"
}

Rules for sections:
- Write 7-9 sections. Each body should be 200-350 words across 2-3 paragraphs.
- For cover_image: pick a real Unsplash photo ID that matches the topic (use format photo-XXXXXXXXXXXXXXXXX).
- For each section that focuses on a specific city or area (e.g. "Beppu", "Kanazawa", "Nikko"), add:
  - "spot_query": { "address_contains": "<city name in English>", "limit": 3 }
  - "section_link": { "text": "Explore <city or prefecture>", "href": "/guides/<prefecture-lowercase>" }
  Prefecture names for href: hokkaido, aomori, iwate, miyagi, akita, yamagata, fukushima, ibaraki, tochigi, gunma, saitama, chiba, tokyo, kanagawa, niigata, toyama, ishikawa, fukui, yamanashi, nagano, shizuoka, aichi, mie, shiga, kyoto, osaka, hyogo, nara, wakayama, tottori, shimane, okayama, hiroshima, yamaguchi, tokushima, kagawa, ehime, kochi, fukuoka, saga, nagasaki, kumamoto, oita, miyazaki, kagoshima, okinawa
- Omit "spot_query" and "section_link" for summary or closing sections (e.g. "How to Get There", "Final Thoughts").`,
      },
    ],
  });

  const rawText = message.content[0].type === 'text' ? message.content[0].text : '';

  let articleData: ArticleOutput;
  try {
    // Strip possible markdown code fences
    const jsonText = rawText.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '').trim();
    articleData = JSON.parse(jsonText);
  } catch {
    console.error('Failed to parse Claude response as JSON:\n', rawText);
    process.exit(1);
  }

  // Insert into Supabase as draft
  const supabase = createClient(supabaseUrl, supabaseKey);
  const { data, error } = await supabase
    .from('blog_posts')
    .insert({
      slug,
      title,
      description: articleData.description,
      read_minutes: articleData.read_minutes,
      cover_image: articleData.cover_image,
      intro: articleData.intro,
      sections: articleData.sections,
      cta_heading: articleData.cta_heading,
      cta_body: articleData.cta_body,
      related_region: region ?? null,
      status: 'draft',
    })
    .select('slug')
    .single();

  if (error) {
    console.error('Supabase insert failed:', error.message);
    process.exit(1);
  }

  console.log(`✓ Draft saved to Supabase: ${data.slug}`);
  console.log(`\nReview in Supabase Studio, then publish with:`);
  console.log(`  curl -X POST https://tobira.app/api/blog/publish \\`);
  console.log(`    -H "Content-Type: application/json" \\`);
  console.log(`    -d '{"slug":"${slug}","secret":"<BLOG_PUBLISH_SECRET>"}'\n`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
