INSERT INTO spots (
  id, name, prefecture, region, categories, description,
  address, lat, lng, image_url, tags, is_premium,
  highlights, best_season, access, admission, duration,
  opening_hours, tips
) VALUES
(
  'otsuka-museum-of-art',
  'Otsuka Museum of Art',
  'Tokushima',
  'shikoku',
  ARRAY['activity'],
  'One of Tokushima''s best-known indoor attractions, this major museum displays more than 1,000 full-size ceramic reproductions of Western masterpieces. Its scale, name recognition, and direct bus access make it a standard first-trip stop in Naruto.',
  '65-1 Fukuike, Tosadomariura, Naruto-cho, Naruto, Tokushima 772-0053, Japan',
  34.236944, 134.633889,
  'https://images.unsplash.com/photo-1577720643272-265e434b3f1f?w=800&auto=format&fit=crop&q=80',
  ARRAY['museum', 'art', 'ceramics', 'Tokushima', 'Naruto', 'cultural', 'indoor'],
  false,
  ARRAY['Full-size ceramic art reproductions', 'World masterpieces collection', 'Large-scale indoor museum', 'Year-round accessibility'],
  'Year-round; especially useful in summer and rainy weather',
  'Direct highway buses to Otsuka Kokusai Bijutsukan-mae stop. From JR Naruto Station, take Naruto City Bus to Naruto Kameura-guchi and walk. About 3 minutes by car from Naruto-kita IC.',
  '¥3,300 (adults)',
  '2.5–4 hours',
  '9:00–17:00 (closed Mondays)',
  'One of Tokushima''s most recognizable cultural attractions and well worth the time. Plan at least 2.5 hours for a comprehensive tour of the main galleries.'
),
(
  'oasahiko-shrine',
  'Oasahiko Shrine',
  'Tokushima',
  'shikoku',
  ARRAY['spiritual'],
  'Widely regarded as Tokushima''s leading shrine, Oasahiko Shrine is a classic visit known for its long lantern-lined approach, huge torii, and old-growth trees. It is a fundamental spiritual landmark in the prefecture.',
  '13 Aza Hirozuka, Bando, Oasa-cho, Naruto, Tokushima 779-0230, Japan',
  34.170694, 134.502611,
  'https://images.unsplash.com/photo-1578896049097-cd90476a1dba?w=800&auto=format&fit=crop&q=80',
  ARRAY['shrine', 'spiritual', 'torii', 'lanterns', 'Tokushima', 'pilgrimage', 'trees'],
  false,
  ARRAY['Historic lantern-lined approach', 'Large torii gate', 'Ancient old-growth trees', 'Tokushima''s principal shrine'],
  'Year-round; spring greenery and autumn foliage are especially appealing',
  'About 25 minutes on foot from JR Bando Station. About 10–15 minutes by car from Itano IC or Aizumi IC.',
  'Free',
  '1–1.5 hours',
  'Open year-round',
  'One of Tokushima''s most important spiritual landmarks. Wear comfortable walking shoes for the long lantern-lined approach to the main hall.'
),
(
  'udatsu-townscape',
  'Udatsu Townscape',
  'Tokushima',
  'shikoku',
  ARRAY['history'],
  'This preserved merchant district in Wakimachi is one of Tokushima''s signature historic streets, lined with white-walled houses that reflect the wealth of the Awa indigo trade. It is the prefecture''s most established walking destination for atmospheric old-town exploration.',
  'Wakimachi Minamimachi, Mima, Tokushima 779-3610, Japan',
  34.068053, 134.146592,
  'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&auto=format&fit=crop&q=80',
  ARRAY['historic-street', 'townscape', 'indigo', 'merchant', 'Tokushima', 'Wakimachi', 'cultural'],
  false,
  ARRAY['Preserved white-walled merchant houses', 'Awa indigo trade heritage', 'Historic townscape street', 'Atmospheric walking district'],
  'Spring and autumn, when strolling the preserved townscape is most comfortable',
  'About 10 minutes by car from Wakimachi IC. By public transport: Tokushima Seibu Kotsu bus from JR Anabuki Station to Wakimachi Michi-no-eki, then walk about 10 minutes.',
  'Free',
  '1.5–2.5 hours',
  'Open year-round (daytime)',
  'Walk slowly through the merchant district to appreciate the architectural details and indigo dye history. Several small shops and cafes are scattered throughout the town.'
),
(
  'awa-jurobe-yashiki',
  'Awa Jurobe Yashiki',
  'Tokushima',
  'shikoku',
  ARRAY['history', 'activity'],
  'This former residence and puppet-theater complex is one of Tokushima''s flagship places to experience Awa ningyo joruri, the prefecture''s signature traditional performing art. Daily performances and strong cultural recognition make it a long-established sightseeing stop.',
  '184 Miyajima Motoura, Kawauchi-cho, Tokushima, Tokushima 770-0114, Japan',
  34.091500, 134.584050,
  'https://images.unsplash.com/photo-1531635220925-be10e86f14b4?w=800&auto=format&fit=crop&q=80',
  ARRAY['puppet-theater', 'ningyo-joruri', 'Tokushima', 'traditional-art', 'performance', 'cultural', 'history'],
  false,
  ARRAY['Traditional Awa ningyo joruri puppet theater', 'Daily performances', 'Historic residence complex', 'Living cultural tradition'],
  'Year-round; spring and autumn are easiest for combining with wider Tokushima City sightseeing',
  'From JR Tokushima Station, take Kawauchi Loop or Tokushima City Bus (terminals B7 or B14) for 20–25 minutes to Awajurobe Yashiki-mae. About 5 minutes by car from Tokushima IC.',
  '¥410 (adults)',
  '1–1.5 hours',
  '9:30–17:00 (closed Mondays)',
  'Awa ningyo joruri performances are held daily. Check the official schedule before visiting to see performance times and combined-ticket options with nearby attractions.'
),
(
  'tairyuji-temple',
  'Tairyuji Temple',
  'Tokushima',
  'shikoku',
  ARRAY['spiritual', 'nature'],
  'Temple 21 of the Shikoku Pilgrimage, Tairyuji is one of Tokushima''s most famous mountain temples, known for its dramatic setting high above the forest and its reputation as "Western Koya". The ropeway approach and mountain location give it strong destination appeal.',
  '2 Ryuzan, Kamo-cho, Anan, Tokushima 771-5173, Japan',
  33.882528, 134.521889,
  'https://images.unsplash.com/photo-1548013146-72aaf735b5ef?w=800&auto=format&fit=crop&q=80',
  ARRAY['temple', 'pilgrimage', 'mountain', 'Tokushima', 'ropeway', 'spiritual', 'Shikoku-88'],
  false,
  ARRAY['Mountain temple high above forest setting', 'Shikoku Pilgrimage stop 21', 'Historic ropeway access', '"Western Koya" landmark'],
  'Spring and autumn, especially for mountain scenery, fresh greenery, and fall foliage',
  'Take Tokushima Bus from JR Tokushima Station to Wajikihigashi, walk about 15 minutes to Tairyuji Ropeway base, then ride about 10 minutes to upper station. Driving from Tokushima City takes 50–60 minutes to the ropeway base.',
  'Free for temple grounds; Tairyuji Ropeway round trip ¥2,470 (adults)',
  '2–3 hours',
  '9:00–17:00 (ropeway hours)',
  'The ropeway ride and mountain walk are integral to the Tairyuji experience. Bring comfortable walking shoes and check weather conditions before visiting, especially in mountain fog season.'
);
