-- ============================================================
-- Spot Expansion: Saga +8, Kagoshima +8, Nagasaki +7,
--                 Fukuoka +6, Okinawa +6  (35 spots total)
-- Run in Supabase SQL Editor
-- ============================================================

INSERT INTO spots (id, name, prefecture, region, categories, description, address, lat, lng, image_url, tags, is_premium, highlights, best_season, access, admission, duration, website_url) VALUES

-- ════════════════════════════════════════════════════════════
-- SAGA  (+8 → total 12)
-- ════════════════════════════════════════════════════════════

(
  'takeo-onsen',
  'Takeo Onsen',
  'Saga', 'kyushu',
  ARRAY['onsen','history'],
  'One of Japan''s oldest hot spring towns with a 1,300-year history, anchored by a magnificent vermilion gate (romon) that has become the symbol of Saga Prefecture. The spring water is a smooth, skin-softening alkaline type beloved by locals for centuries.',
  '9222-43 Takeo-machi, Takeo, Saga 843-0023',
  33.1791, 130.0309,
  'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=1200&auto=format&fit=crop&q=80',
  ARRAY['onsen','hot spring','historic gate','skin-softening','Saga'],
  false,
  ARRAY['The 1914 Meiji-era gate was designed by the same architect as Tokyo Station — spot the similarities','The oldest public bath, Motoyuukan, has been operating for over 400 years and costs just ¥400','Combine with a visit to Takeo City Library — a stunning Tsutaya-designed space with 200,000 books and a Starbucks inside'],
  'Year-round; autumn for foliage around the gate',
  'JR Nagasaki Line to Takeo-Onsen Station (from Hakata ~1 hr by limited express)',
  'Public baths from ¥400',
  '1–2 hours',
  'https://www.takeo-kk.net/spa/'
),

(
  'mifuneyama-rakuen',
  'Mifuneyama Rakuen Garden',
  'Saga', 'kyushu',
  ARRAY['nature'],
  'A 500,000 sq metre garden carved into the cliffs of a 235-meter granite mountain, created by the lord of Takeo Domain in 1845. Famous for 200,000 azalea bushes in spring and fiery maple foliage in autumn — one of Kyushu''s great seasonal spectacles.',
  '4100 Takeo-machi, Takeo, Saga 843-0022',
  33.1847, 130.0154,
  'https://images.unsplash.com/photo-1540979388789-6cee28a1cdc9?w=1200&auto=format&fit=crop&q=80',
  ARRAY['azalea','maple','garden','cliff','teamLab'],
  false,
  ARRAY['Late April: the entire cliff turns pink-purple with 200,000 azaleas blooming simultaneously','teamLab has an annual light art installation in the garden from August to November — ethereal after dark','The 300-year-old wisteria tree near the pond is one of the largest in Kyushu'],
  'Late April (azalea) or October–November (autumn leaves)',
  '5 min taxi from Takeo-Onsen Station or free shuttle during peak season',
  '¥600 adults (light show ¥1,800)',
  '1.5–2 hours',
  'https://www.mifuneyama.co.jp'
),

(
  'karatsu-niji-matsubara',
  'Niji-no-Matsubara Beach',
  'Saga', 'kyushu',
  ARRAY['nature'],
  'One of Japan''s Three Great Pine Groves — a 5 km arc of white sand beach backed by half a million pine trees. The trees were planted 400 years ago to protect the town from sea winds, and today the combination of turquoise water, white sand, and dark pines is simply extraordinary.',
  'Niji-no-Matsubara, Karatsu, Saga',
  33.4580, 129.9502,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
  ARRAY['beach','pine grove','white sand','swimming','Three Great Pine Groves'],
  false,
  ARRAY['Walk or cycle through the pine forest on paths used by generations of Karatsu fishermen','The beach is swimmable June–September; the sea is calm and clear on most days','Combine with a visit to Karatsu Castle (15 min walk) to see the pine grove from above'],
  'June–September (swimming) or year-round (walking)',
  '20 min walk from Karatsu Station along the coast',
  'Free',
  '1–3 hours',
  ''
),

(
  'nanatsugama-caves',
  'Nanatsugama Sea Caves',
  'Saga', 'kyushu',
  ARRAY['nature','activity'],
  'Seven sea caves (nana = seven, kama = pot) carved into volcanic basalt cliffs on the Genkai coast. The largest cave reaches 110 metres deep with a 16-metre ceiling. Access by sightseeing boat lets you glide right inside the cave chambers as waves echo around you.',
  'Yobuko-cho, Karatsu, Saga',
  33.5022, 129.8688,
  'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=1200&auto=format&fit=crop&q=80',
  ARRAY['sea cave','boat tour','basalt','coastal','Genkai'],
  false,
  ARRAY['The boat tour departs from Yobuko Port — combine with the famous Yobuko morning market for fresh squid','The caves glow blue-green when sunlight reflects off the water inside','Yobuko''s ika (live squid sashimi) is a Saga bucket-list experience — eat it in the harbor restaurants'],
  'April–October (boat tours operate in calm weather)',
  'Bus from Karatsu Station to Yobuko (~30 min), then 10 min walk to port',
  'Boat tour ¥1,500 adults',
  '1.5 hours (boat + sightseeing)',
  ''
),

(
  'saga-balloon-museum',
  'Saga International Balloon Fiesta Museum',
  'Saga', 'kyushu',
  ARRAY['activity'],
  'Saga hosts Asia''s largest hot air balloon festival each autumn, attracting 100+ balloons from 20+ countries. The year-round museum lets you experience a balloon gondola simulator, see the engineering behind it, and understand why Saga''s flat terrain and calm dawn winds make it the world''s best balloon location.',
  '2-23 Jonai, Saga 840-0041',
  33.2575, 130.3024,
  'https://images.unsplash.com/photo-1507608616759-54f48f0af0ee?w=1200&auto=format&fit=crop&q=80',
  ARRAY['balloon','festival','simulator','family','Saga City'],
  false,
  ARRAY['The balloon fiesta runs for 8 days in late October/early November — book hotels 6 months ahead','The gondola simulator lets you "fly" over Saga plain — unexpectedly exhilarating','The museum shop sells balloon-shaped nikuman (steamed pork buns) — only in Saga'],
  'Late October–early November (festival) or year-round (museum)',
  '15 min walk from Saga Station',
  '¥500 adults',
  '1 hour',
  'https://www.sibf.jp'
),

(
  'imari-okawachiyama',
  'Imari Okawachi-yama Kiln Village',
  'Saga', 'kyushu',
  ARRAY['history'],
  'A hidden valley where the Nabeshima clan''s secret kilns produced porcelain exclusively for the Edo shogunate and European royalty. Today 30+ kilns still operate in this quiet mountain valley — you can watch master potters at work and buy directly from the kilns that supplied Versailles.',
  'Okawachi-yama, Imari, Saga',
  33.2628, 129.9027,
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&auto=format&fit=crop&q=80',
  ARRAY['pottery','kiln','Nabeshima ware','craft','porcelain'],
  true,
  ARRAY['The valley is accessed via a bridge — a guardian deity watches over the secret kilns at the entrance','Nabeshima ware is among the most technically perfect porcelain ever made — prices at source are 30% below Tokyo galleries','The annual pottery market in early November brings bargain pieces from all 30 kilns'],
  'Year-round; early November for the kiln market',
  'Bus from Imari Station (~20 min) or taxi',
  'Free to enter; pottery from ¥1,000',
  '1.5–2 hours',
  ''
),

(
  'saga-castle-ruins',
  'Saga Castle & History Museum',
  'Saga', 'kyushu',
  ARRAY['history'],
  'Saga Castle was the seat of the Nabeshima clan for 270 years, and its partial reconstruction now houses one of Japan''s best-designed samurai history museums. The moat, stone walls, and the magnificent Tamon Yagura gate tower are original — some of the finest surviving examples of Edo-period castle architecture in Kyushu.',
  '2-18-1 Jonai, Saga 840-0041',
  33.2506, 130.3086,
  'https://images.unsplash.com/photo-1502863029862-5f2a8f22f24e?w=1200&auto=format&fit=crop&q=80',
  ARRAY['castle','samurai','Nabeshima','museum','Meiji Restoration'],
  false,
  ARRAY['The Saga Rebellion of 1874 — a key early Meiji revolt — is explained through vivid dioramas','The Tamon Yagura is the only part of the original castle to survive; it''s one of Kyushu''s finest examples','The museum shop sells high-quality Saga-made crafts including Nabeshima porcelain reproductions'],
  'Year-round',
  '15 min walk from Saga Station',
  'Museum ¥500 adults; castle grounds free',
  '1.5 hours',
  'https://saga-museum.jp'
),

(
  'higashiyoka-tidal-flat',
  'Higashiyoka Tidal Flat',
  'Saga', 'kyushu',
  ARRAY['nature'],
  'A Ramsar Convention wetland on Ariake Sea — one of Japan''s most biodiverse tidal flats, home to 140 species of migratory birds and the spectacle of mudskippers and fiddler crabs at low tide. In autumn, the shichimenso (salicornia) turns the mudflat a vivid red, creating an otherworldly landscape.',
  'Higashiyoka, Saga 840-0206',
  33.3619, 130.3338,
  'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&auto=format&fit=crop&q=80',
  ARRAY['tidal flat','birdwatching','Ramsar','mudskippers','crimson autumn'],
  false,
  ARRAY['October is the red season — shichimenso plants covering the flat turn deep crimson simultaneously','Mudskippers (mutsugoro) are the local symbol — these fish walk on land and are unique to Ariake Sea','The adjacent road runs right along the flat — photograph at sunset when light turns everything golden'],
  'October (crimson shichimenso) or March–April (migratory birds)',
  'Car recommended (40 min from Saga Station); limited bus service',
  'Free',
  '45 min',
  ''
),

-- ════════════════════════════════════════════════════════════
-- KAGOSHIMA  (+8 → total 12)
-- ════════════════════════════════════════════════════════════

(
  'yakushima-island',
  'Yakushima Island',
  'Kagoshima', 'kyushu',
  ARRAY['nature','activity'],
  'A UNESCO World Heritage island of ancient cedar forests where trees live for thousands of years. The iconic Jomon Sugi cedar — estimated at 2,170 to 7,200 years old — is the oldest living thing in Japan. About 35% of the island is national park, with more rainfall than almost anywhere else in Japan feeding waterfalls that cascade through mossy old-growth.',
  'Yakushima, Kumage-gun, Kagoshima 891-4205',
  30.2877, 130.4989,
  'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&auto=format&fit=crop&q=80',
  ARRAY['ancient cedar','UNESCO','Jomon Sugi','old-growth forest','hiking','Princess Mononoke'],
  true,
  ARRAY['The Jomon Sugi hike is 22 km round trip — start by 5 AM to avoid afternoon rain and crowds','The forest inspired Studio Ghibli''s Princess Mononoke — the ancient, mossy atmosphere is exactly as depicted','Bring full rain gear regardless of forecast — Yakushima receives up to 10,000 mm annually in the mountains'],
  'March–June or September–November (avoiding summer typhoons)',
  'Ferry from Kagoshima Takachiho Port: high-speed jet foil ~2 hrs (¥8,900) or overnight car ferry (~10 hrs)',
  'Island free; Jomon Sugi trail ¥1,000 trail maintenance fee',
  'Full day (Jomon Sugi) or 2–3 day stay',
  'https://www.yakushima.or.jp/en/'
),

(
  'chiran-samurai-district',
  'Chiran Samurai Residence District',
  'Kagoshima', 'kyushu',
  ARRAY['history'],
  'Seven perfectly preserved samurai residences with stone-walled gardens in the "Little Kyoto of Satsuma." Each garden is a distinct masterwork of Japanese landscape design — rock arrangements, clipped hedges, and borrowed scenery using Chiran''s forested mountains. The moss-covered stone walls along the approach lane are among the most photogenic in all of Japan.',
  '6454 Chiran-cho, Minamikyushu, Kagoshima 897-0302',
  31.3718, 130.4499,
  'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&auto=format&fit=crop&q=80',
  ARRAY['samurai','garden','stone wall','Satsuma','Little Kyoto'],
  false,
  ARRAY['The main lane (Bukeyashiki-dori) is most beautiful at 7 AM before tour buses arrive','Garden #4 (Hirayama Residence) is considered the finest — look for the Mt. Fuji-shaped clipped pine','Walk 10 minutes beyond the samurai district to the tea fields — Chiran is one of Japan''s major green tea producers'],
  'March–April (cherry blossoms) or year-round',
  'Bus from Kagoshima-Chuo Station (~1 hr) or rental car',
  '¥530 adults (all 7 gardens)',
  '1.5–2 hours',
  ''
),

(
  'chiran-peace-museum',
  'Chiran Peace Museum for Kamikaze Pilots',
  'Kagoshima', 'kyushu',
  ARRAY['history'],
  'The most humanizing war museum in Japan. Chiran was a major kamikaze base — 1,036 young pilots departed from here for their final missions in 1945. The museum preserves their handwritten farewell letters (many expressing love for family, not ideology), personal photographs, and the Zero fighters they flew. Profoundly moving regardless of background.',
  '17881 Chiran-cho, Minamikyushu, Kagoshima 897-0302',
  31.3739, 130.4488,
  'https://images.unsplash.com/photo-1513883049090-d0b7439799bf?w=1200&auto=format&fit=crop&q=80',
  ARRAY['kamikaze','WWII','peace','farewell letters','Zero fighter'],
  false,
  ARRAY['Allow 2+ hours — rushing through diminishes the weight of what you are witnessing','The farewell letters — many written the night before departure — reveal 20-year-olds thinking about their mothers and younger siblings','A Zero fighter and a restored Hayabusa are preserved outdoors and can be viewed up close'],
  'Year-round',
  'Bus from Kagoshima-Chuo Station to Chiran (~1 hr), then 5 min walk',
  '¥500 adults',
  '2 hours',
  'https://www.chiran-tokkou.jp'
),

(
  'amami-oshima',
  'Amami Oshima',
  'Kagoshima', 'kyushu',
  ARRAY['nature','activity'],
  'A subtropical island midway between Kyushu and Okinawa with UNESCO World Heritage rainforest, mangrove kayaking, and some of the clearest sea in Japan. Amami has its own distinct culture — different music, food, and weaving tradition (Oshima Tsumugi silk) — and far fewer foreign visitors than Okinawa.',
  'Amami City, Oshima-gun, Kagoshima 894-0036',
  28.3706, 129.4943,
  'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&auto=format&fit=crop&q=80',
  ARRAY['subtropical','mangrove','UNESCO','kayaking','Oshima Tsumugi','sea turtle'],
  true,
  ARRAY['Rent a kayak in住用 (Sumiyou) and paddle through the largest mangrove forest in Japan north of Okinawa','The Kinsakubaru Primary Forest at night: guided tours to spot Amami black rabbits (found nowhere else on Earth)','Oshima Tsumugi silk weaving workshops take you from raw silk to shuttle — one of Japan''s most complex textile traditions'],
  'March–June or September–November',
  'Flight from Kagoshima airport (~45 min); ferry from Kagoshima port (~11 hrs)',
  'Island free; mangrove kayak rental from ¥2,500',
  '2–3 day stay recommended',
  ''
),

(
  'kaimondake-volcano',
  'Kaimondake Volcano',
  'Kagoshima', 'kyushu',
  ARRAY['nature','activity'],
  'A near-perfect conical stratovolcano nicknamed "Satsuma Fuji," rising 924m from the Satsuma Peninsula coast. The 3-hour circular hiking trail offers panoramic views of the Satsuma Peninsula, distant Yakushima and Kuchierabu islands, and Ibusuki''s sand bath coast — one of the finest volcano summits in Kyushu.',
  'Kaimondake, Ibusuki, Kagoshima 891-0603',
  31.1899, 130.5249,
  'https://images.unsplash.com/photo-1455156218388-5e61b526818b?w=1200&auto=format&fit=crop&q=80',
  ARRAY['volcano','hiking','Satsuma Fuji','panorama','Kyushu'],
  false,
  ARRAY['The summit crater is accessible — look down into the bowl from the rim on a clear day','Start at the 5th station (accessible by car) to cut the hike to 2 hours up and 1.5 hours down','Combine with Ibusuki sand baths (20 min drive) for a volcano + hot spring day'],
  'October–May (avoiding summer heat and typhoons)',
  'JR Ibusuki-Makurazaki Line to Kaimon Station (from Kagoshima-Chuo ~1 hr), then 30 min walk to trailhead',
  'Free',
  '3–4 hours (full circuit)',
  ''
),

(
  'shiroyama-observatory',
  'Shiroyama Observatory',
  'Kagoshima', 'kyushu',
  ARRAY['nature'],
  'A forested hilltop rising 107m behind Kagoshima city center — the site of the last stand of the Satsuma Rebellion in 1877, where Saigo Takamori died. Today the observation deck gives the city''s definitive view: the entire bay, the active Sakurajima volcano perfectly framed, and on clear days, the Kirishima mountain range beyond.',
  'Shiroyama-cho, Kagoshima 892-0853',
  31.5978, 130.5524,
  'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&auto=format&fit=crop&q=80',
  ARRAY['observatory','Sakurajima view','Satsuma Rebellion','Saigo Takamori','sunset'],
  false,
  ARRAY['At sunset, Sakurajima turns orange-red and steam from the crater catches the evening light','The forest trail up to the observation deck passes the cave where Saigo Takamori hid his final days','A hotel at the summit has a rooftop terrace open to non-guests — the best sunset viewing spot in Kagoshima'],
  'Year-round; best at sunrise or sunset',
  'City bus #1 from Kagoshima-Chuo Station (~20 min) or 40 min walk',
  'Free',
  '30–45 min',
  ''
),

(
  'kagoshima-foot-onsen',
  'Iso Nagisa Foot Onsen',
  'Kagoshima', 'kyushu',
  ARRAY['onsen'],
  'A free outdoor foot bath set directly in volcanic lava rock on the shore of Kagoshima Bay, just steps from Sengan-en Garden. The naturally hot spring water flows through channels carved into the ancient lava, and you sit with your feet in the water looking directly at Sakurajima across the bay — a view and experience you will not find anywhere else.',
  '9700-1 Yoshino, Kagoshima 892-0871',
  31.6345, 130.5978,
  'https://images.unsplash.com/photo-1576675784201-0e142b423952?w=1200&auto=format&fit=crop&q=80',
  ARRAY['foot onsen','Sakurajima view','free','volcanic rock','Sengan-en'],
  false,
  ARRAY['Bring a small towel — no facilities provided, but a convenience store is nearby','The lava rock you''re sitting on is from the 1779 Sakurajima eruption — it flowed into the sea and formed this shoreline','Combine with Sengan-en Garden (2-minute walk) for a full morning: garden → tea house → foot bath by the sea'],
  'Year-round',
  'City bus #1 from Kagoshima-Chuo Station (~25 min)',
  'Free',
  '20–30 min',
  ''
),

(
  'tenmonkan-district',
  'Tenmonkan Food District',
  'Kagoshima', 'kyushu',
  ARRAY['food'],
  'Kagoshima''s central covered shopping arcade and the heart of its food culture. This is where to find all of the prefecture''s signature dishes: shirokuma (polar bear) shaved ice, Berkshire black pork (kurobuta) shabu-shabu, chicken-sashimi (tori no tataki), and shochu distilleries offering samples. The covered arcade stays active until midnight.',
  'Tenmonkan-dori, Kagoshima 892-0842',
  31.5883, 130.5490,
  'https://images.unsplash.com/photo-1547592180-85f173990554?w=1200&auto=format&fit=crop&q=80',
  ARRAY['shirokuma','kurobuta','black pork','food street','shochu','Kagoshima city'],
  false,
  ARRAY['Shirokuma at Mujioka — a mound of shaved ice with condensed milk, azuki beans, and fruit — is the Kagoshima food pilgrimage','Black pork shabu-shabu is richer than regular pork; the collagen content keeps the broth silky','The shochu (sweet potato spirit) tasting at local liquor stores is free and enthusiastic — Kagoshima produces 200+ varieties'],
  'Year-round',
  '10 min walk from Kagoshima-Chuo Station or tram to Tenmonkan-dori stop',
  'Free entry; food from ¥700',
  '2–3 hours',
  ''
),

-- ════════════════════════════════════════════════════════════
-- NAGASAKI  (+7 → total 12)
-- ════════════════════════════════════════════════════════════

(
  'dejima',
  'Dejima Dutch Trading Post',
  'Nagasaki', 'kyushu',
  ARRAY['history'],
  'For 200 years during Japan''s isolation period, this tiny fan-shaped artificial island was the only point of contact between Japan and the Western world. Dutch traders lived here under strict conditions; their books, clocks, and scientific instruments slowly changed Japan. The island has been meticulously reconstructed to its 1820s appearance, complete with furnished warehouses, a VOC flag, and Dutch gardens.',
  '6-1 Dejimamachi, Nagasaki 850-0862',
  32.7448, 129.8718,
  'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&auto=format&fit=crop&q=80',
  ARRAY['Dutch trading post','isolation period','Edo Japan','VOC','reconstruction'],
  false,
  ARRAY['The scale model in Building 3 shows exactly what Dejima looked like in the 1800s — use it to orient yourself','Dutch texts brought through Dejima eventually launched Japanese Western medicine, astronomy, and painting','The mini-Dejima replica model shop sells surprisingly affordable hand-crafted souvenirs made by local artisans'],
  'Year-round',
  '10 min walk from Nagasaki Station or tram to Dejima stop',
  '¥510 adults',
  '1–1.5 hours',
  'https://www.nagasaki-dejima.jp'
),

(
  'oura-cathedral',
  'Oura Cathedral',
  'Nagasaki', 'kyushu',
  ARRAY['history','spiritual'],
  'Japan''s only National Treasure cathedral — a Gothic limestone church consecrated in 1865, built to memorialize the 26 Christians martyred in Nagasaki in 1597. Shortly after opening, the discovery of thousands of "hidden Christians" who had secretly practiced their faith for 250 years astonished the world and was called the "miracle of Oura." Now a UNESCO World Heritage site.',
  '5-3 Minamiyamate, Nagasaki 850-0931',
  32.7232, 129.8715,
  'https://images.unsplash.com/photo-1573074617613-fc8ef27e6a9a?w=1200&auto=format&fit=crop&q=80',
  ARRAY['cathedral','Gothic','National Treasure','hidden Christians','UNESCO','martyrs'],
  false,
  ARRAY['The stained glass windows were imported from France and have survived two centuries intact','From the cathedral steps, look down toward the harbor — the same view the original hidden Christians would have had','The adjacent museum has the kakure kirishitan''s (hidden Christian) objects: crosses hidden inside Buddhist figures, a Madonna disguised as Kannon'],
  'Year-round',
  'Tram to Oura Tenshudo-Shita stop, 5 min walk',
  '¥1,000 adults (cathedral + museum)',
  '45 min–1 hour',
  'https://www.oura-cathedral.jp'
),

(
  'meganebashi-bridge',
  'Meganebashi (Spectacles Bridge)',
  'Nagasaki', 'kyushu',
  ARRAY['history'],
  'Japan''s oldest stone arch bridge, built in 1634 by a Chinese Zen monk. When the Nakashima River is calm, the twin arches reflect perfectly in the water below, creating the "spectacles" (megane) shape that gave the bridge its name. The bridge survived the 1945 atomic bombing intact and remains the heart of Nagasaki''s historic riverside quarter.',
  '2-chome Kajiya-machi, Nagasaki 850-0874',
  32.7494, 129.8783,
  'https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=1200&auto=format&fit=crop&q=80',
  ARRAY['stone arch bridge','reflection','Edo era','Nakashima River','historic bridge'],
  false,
  ARRAY['Best photographed at dawn before tour groups arrive — the reflection requires still water and soft light','Look for the heart-shaped stones embedded in the riverside walls — said to bring love luck if you find them','The riverside path has seven historic bridges in total — walk all of them for a 45-minute architectural tour'],
  'Year-round; spring for cherry blossoms over the river',
  '10 min walk from Nagasaki Station',
  'Free',
  '20–30 min',
  ''
),

(
  'huis-ten-bosch',
  'Huis Ten Bosch',
  'Nagasaki', 'kyushu',
  ARRAY['activity'],
  'A meticulously built 152-hectare recreation of a Dutch town on the shores of Omura Bay — canals, windmills, gabled buildings, and tulip fields transplanted to Kyushu. Japan''s most elaborate theme park runs some of the country''s most ambitious light shows, including a 13-million-bulb winter illumination that has won the Guinness World Record for largest.',
  '1-1 Huis Ten Bosch-cho, Sasebo, Nagasaki 859-3243',
  33.0934, 129.7761,
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&auto=format&fit=crop&q=80',
  ARRAY['theme park','Dutch','windmill','illumination','Guinness record','tulips'],
  false,
  ARRAY['The winter illumination (November–March) is the main draw: 13 million lights covering the entire park after dark','A canal boat ride around the park shows the scale — the replica Dutch buildings are full-size, not miniatures','The Kingdom of Robots zone is unexpectedly excellent: live robot performances and a hotel staffed entirely by robots'],
  'March–May (tulips) or November–March (illumination)',
  'JR Huis Ten Bosch Station from Hakata (~2 hrs direct) or Nagasaki (~1.5 hrs)',
  '¥4,000 adults (all areas)',
  'Half day to full day',
  'https://www.huistenbosch.co.jp/english/'
),

(
  'goto-islands',
  'Goto Islands',
  'Nagasaki', 'kyushu',
  ARRAY['nature','spiritual'],
  'An archipelago of 140 islands where 30,000 "hidden Christians" (kakure kirishitan) secretly maintained their faith for 250 years under the death penalty. The UNESCO-listed churches, set in fishing villages against a backdrop of spectacularly clear emerald sea, represent one of the world''s most extraordinary stories of religious perseverance.',
  'Goto City, Nagasaki 853-0007',
  32.6969, 128.8350,
  'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1200&auto=format&fit=crop&q=80',
  ARRAY['hidden Christians','UNESCO','church','emerald sea','fishing village','island'],
  true,
  ARRAY['Mizunoura Church on Naru Island is the most remote and atmospheric — 45 min from Fukue by ferry, then a steep walk','The sea between the islands is some of the clearest in Japan — kayak tours from Fukue Island reveal underwater visibility of 15+ metres','Visit the Christian Heritage Museum in Fukue to understand the 250 years of concealment before exploring the churches'],
  'April–June or September–November',
  'Ferry from Nagasaki port (~3 hrs to Fukue Island) or flight (~30 min)',
  'Islands free; ferry from ¥3,000',
  '1–2 day stay recommended',
  ''
),

(
  'nagasaki-shinchi-lantern',
  'Nagasaki Shinchi & Lantern Festival Area',
  'Nagasaki', 'kyushu',
  ARRAY['food','history'],
  'Japan''s oldest and most atmospheric Chinatown, where the annual Lantern Festival (Nagasaki Lantern Festival) transforms the city every Chinese New Year with 15,000 lanterns hanging over the streets. The event is Nagasaki''s biggest celebration — lion dances, Chinese opera, and emperor processions fill the harbor area for 15 days.',
  '10 Shinchi-machi, Nagasaki 850-0842',
  32.7460, 129.8771,
  'https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=1200&auto=format&fit=crop&q=80',
  ARRAY['Chinatown','lantern festival','Chinese New Year','chanpon','Sara-udon'],
  false,
  ARRAY['Shikairou (四海楼) — founded in 1899 — claims to have invented chanpon noodles; the 5th-floor restaurant has harbor views','The Lantern Festival (late Jan / early Feb) is best at 6–9 PM when the lanterns are lit and crowds are manageable','The narrow Hamano-machi covered arcade behind Shinchi has Nagasaki''s best street food: kakuni manju (braised pork buns)'],
  'Year-round; late January–February for the Lantern Festival',
  '5 min walk from Nagasaki Station or tram to Tsuki-machi',
  'Free; chanpon from ¥900',
  '1–2 hours',
  ''
),

(
  'mount-inasa-observatory',
  'Mount Inasa Night View Observatory',
  'Nagasaki', 'kyushu',
  ARRAY['nature'],
  'One of Japan''s three great night views — Nagasaki''s harbor, peninsula, and islands create a "million-dollar night view" when seen from 333m. The city''s geography (built on hills around a narrow bay) produces a more complex, layered nightscape than flat cities like Kobe or Hakodate, making this arguably the finest of the three.',
  '1-3 Fuchi-machi, Nagasaki 852-8104',
  32.7669, 129.8497,
  'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=1200&auto=format&fit=crop&q=80',
  ARRAY['night view','observatory','ropeway','Nagasaki harbor','Japan three great views'],
  false,
  ARRAY['The ropeway takes just 5 minutes — sunset is the best time to arrive, watching the city transition from day to night','In winter, the air is crisp and visibility extends to the islands 20 km away','The observatory has a heated viewing room for rainy nights — the rain on the glass creates a dreamy soft-focus effect'],
  'Year-round; clearest winter nights October–March',
  'Tram to Fuchi Station, then 10 min walk to ropeway base',
  'Ropeway ¥1,250 round trip',
  '1 hour',
  'https://www.nagasaki-ropeway.jp'
),

-- ════════════════════════════════════════════════════════════
-- FUKUOKA  (+6 → total 12)
-- ════════════════════════════════════════════════════════════

(
  'fukuoka-castle-ruins',
  'Fukuoka Castle Ruins & Maizuru Park',
  'Fukuoka', 'kyushu',
  ARRAY['history','nature'],
  'The remains of one of Kyushu''s largest castles, built in 1607 for the powerful Kuroda clan. The stone walls, moats, and surviving turrets still impress despite the main tower''s disappearance. In spring, 1,300 cherry trees turn the castle grounds into one of Fukuoka''s best hanami (cherry blossom viewing) spots — and it''s completely free.',
  '1-1 Jonai, Chuo-ku, Fukuoka 810-0043',
  33.5869, 130.3852,
  'https://images.unsplash.com/photo-1502863029862-5f2a8f22f24e?w=1200&auto=format&fit=crop&q=80',
  ARRAY['castle ruins','cherry blossoms','hanami','Kuroda clan','Ohori Park'],
  false,
  ARRAY['Combine with adjacent Ohori Park — a lake park modeled on West Lake in Hangzhou, perfect for morning runs','The Fukuoka Castle Museum has a scale model showing how the full castle looked — it was larger than Osaka Castle','The Tamon Yagura turret (one of two survivors) can be entered on weekends for the best stone wall views'],
  'Late March–early April (cherry blossoms) or autumn',
  '15 min walk from Akasaka subway station or Tenjin',
  'Grounds free; museum ¥200',
  '1–1.5 hours',
  ''
),

(
  'keya-no-oto-cave',
  'Keya no Oto Sea Cave',
  'Fukuoka', 'kyushu',
  ARRAY['nature'],
  'The largest sea cave in Japan, carved 64 metres high and 10 metres wide into the volcanic basalt coast of the Itoshima Peninsula. At high tide, waves boom against the walls with a sound like thunder (oto means sound). A 1-km clifftop trail leads to the cave entrance where you can stand at the lip and look straight down into crashing surf.',
  'Keya, Itoshima, Fukuoka',
  33.5399, 130.1258,
  'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=1200&auto=format&fit=crop&q=80',
  ARRAY['sea cave','basalt','cliffside','Itoshima','surf','dramatic'],
  false,
  ARRAY['Visit at high tide for the full thunder effect — the timing varies daily, check a tide chart','The clifftop trail (easy, 20 min walk) gives views over the Genkai Sea toward the islands','Combine with Itoshima''s oyster shacks in winter (same peninsula, 30 min drive)'],
  'Year-round; most dramatic in winter storms (stay safely on the path)',
  'Showa Bus from Maebaru Station (~30 min) or drive',
  'Free',
  '45 min',
  ''
),

(
  'hakata-machiya-museum',
  'Hakata Machiya Folk Museum',
  'Fukuoka', 'kyushu',
  ARRAY['history'],
  'Three authentic Meiji and Taisho-era Hakata townhouses relocated and meticulously preserved to show how merchant life looked in old Hakata. The museum also houses the city''s finest collection of Gion Yamakasa festival artifacts — the giant festival floats (kazariyama) that are displayed year-round.',
  '6-10 Reisen-machi, Hakata-ku, Fukuoka 812-0039',
  33.5887, 130.4167,
  'https://images.unsplash.com/photo-1513407030348-c983a97b98d8?w=1200&auto=format&fit=crop&q=80',
  ARRAY['townhouse','Meiji era','Gion Yamakasa','festival float','Hakata culture'],
  false,
  ARRAY['The Gion Yamakasa float on display weighs over 1 ton and took 100 craftsmen weeks to build — it''s replaced every year','A craftsman demonstrates Hakata-ori weaving (the stiff silk used for obi) on traditional looms on weekday afternoons','The second floor of the main machiya lets you sit on tatami and look out through sliding screens over the old district'],
  'Year-round',
  '5 min walk from Gion subway station',
  '¥200 adults',
  '1 hour',
  'https://www.hakatamachiya.com'
),

(
  'uminonakamichi-park',
  'Uminonakamichi Seaside Park',
  'Fukuoka', 'kyushu',
  ARRAY['nature','activity'],
  'A national seaside park on the narrow peninsula enclosing Hakata Bay. 350 hectares of flower gardens, cycling paths, animal park, and amusement zone — different flower species bloom each month, from tulips and poppies in spring to cosmos and dahlias in autumn. The cycling paths run along the bay with views back toward Fukuoka city.',
  '18 Uminonakamichi, Higashi-ku, Fukuoka 811-0321',
  33.6422, 130.4358,
  'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200&auto=format&fit=crop&q=80',
  ARRAY['flower park','cycling','family','Hakata Bay view','seasonal flowers'],
  false,
  ARRAY['Late April–early May: the nemophila (baby blue eyes) field — 530,000 plants creating a blue carpet — is Fukuoka''s biggest seasonal event','Rent a bike at the park entrance for ¥400 — it''s the best way to cover the full 350 hectares','The marine world aquarium within the park has dolphin shows at 11 AM, 1 PM, and 3 PM daily'],
  'April–May (spring flowers) or October–November (cosmos)',
  'JR Kagoshima Line to Uminonakamichi Station (from Hakata ~30 min)',
  '¥450 adults',
  '2–3 hours',
  ''
),

(
  'yanagibashi-market',
  'Yanagibashi Rengo Market',
  'Fukuoka', 'kyushu',
  ARRAY['food'],
  'Hakata''s "kitchen" — a covered market of 35 specialist shops that has supplied the city''s restaurants and home cooks since 1910. Fishmongers, vegetable sellers, tofu makers, pickle shops, and ready-to-eat food stalls pack the narrow aisles. The morning energy is extraordinary: chefs negotiating with fishmongers over the overnight Genkai Sea catch.',
  '2-1-29 Haruyoshi, Chuo-ku, Fukuoka 810-0003',
  33.5866, 130.3974,
  'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=1200&auto=format&fit=crop&q=80',
  ARRAY['market','fish market','morning market','Hakata','local food','fresh seafood'],
  false,
  ARRAY['Arrive before 9 AM when the fish and vegetable selection is at its peak — many stalls sell out by noon','The mentaiko (spicy pollock roe) shops here have the best quality in Fukuoka — ask which one the chefs buy from','The prepared food stalls in the back make excellent onigiri and tamagoyaki for a market breakfast from ¥200'],
  'Year-round; mornings (7–11 AM) are essential',
  'Watanabe-dori subway station, 5 min walk',
  'Free entry; food from ¥200',
  '45 min',
  ''
),

(
  'aburayama-forest-park',
  'Aburayama Forest Park',
  'Fukuoka', 'kyushu',
  ARRAY['nature','activity'],
  'Fukuoka''s green lung — a forested mountain park just 30 minutes from the city center with mountain biking trails, a kids'' forest museum, scenic viewpoints, and glamping facilities. On weekends it attracts Fukuoka''s athletic community for trail running and mountain biking; on weekdays it''s blissfully quiet.',
  '1442 Aburayama, Jonan-ku, Fukuoka 814-0153',
  33.5254, 130.3677,
  'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&auto=format&fit=crop&q=80',
  ARRAY['mountain biking','hiking','forest','family','glamping','trail running'],
  false,
  ARRAY['The MTB trails range from beginner to expert — bike rental available at the Forest Science Museum','The observation deck at the summit (597 m) overlooks all of Fukuoka city from downtown to Hakata Bay','The Forest Science Museum is brilliantly designed for children: exhibits on insects, trees, and forest ecology with hands-on activities'],
  'Year-round; spring (azaleas) and autumn (foliage) are most scenic',
  'Bus from Hakata or Tenjin (~30 min)',
  'Free (parking ¥500)',
  '2–4 hours',
  ''
),

-- ════════════════════════════════════════════════════════════
-- OKINAWA  (+6 → total 12)
-- ════════════════════════════════════════════════════════════

(
  'nakijin-castle',
  'Nakijin Castle Ruins',
  'Okinawa', 'kyushu',
  ARRAY['history','spiritual'],
  'The largest castle ruin in Okinawa, built in the 14th century as the seat of the Northern Kingdom (Hokuzan) before the Ryukyu unification. The walls stretch for 1.5 km along a ridge 100m above the sea — far more dramatic than Shuri Castle — and they shelter 200 cherry trees that bloom in January, the earliest cherry blossoms in Japan.',
  '5101 Nakijin, Nakijin-son, Kunigami-gun, Okinawa 905-0406',
  26.6882, 127.9104,
  'https://images.unsplash.com/photo-1492571350019-22de08371fd3?w=1200&auto=format&fit=crop&q=80',
  ARRAY['castle ruins','UNESCO','cherry blossoms','January','Northern Kingdom','ridge'],
  false,
  ARRAY['January cherry blossoms here are the first in Japan — visit for a surreal winter sakura experience','The view from the top of the wall looks over the East China Sea to Ie Island — on clear days you can see Amami Oshima','The site is far less crowded than Shuri Castle and more atmospheric — moss-covered limestone walls in a working forest'],
  'January (earliest cherry blossoms in Japan) or March–June',
  'Car recommended (1 hr from Naha) or bus from Naha to Nakijin (~2 hrs)',
  '¥400 adults',
  '1 hour',
  'https://nakijin-castle.jp'
),

(
  'kouri-island',
  'Kouri Island & Heart Rock',
  'Okinawa', 'kyushu',
  ARRAY['nature','activity'],
  'A small island connected to Okinawa''s main island by a 1.9 km bridge with clear turquoise water on both sides. The island is famous for Heart Rock — two naturally heart-shaped coral rocks on Tinu Beach, framed by the East China Sea. The beach requires a 5-minute hike down from the bridge, which keeps crowds manageable.',
  'Kouri, Nakijin-son, Kunigami-gun, Okinawa 905-0406',
  26.7189, 127.9975,
  'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=1200&auto=format&fit=crop&q=80',
  ARRAY['heart rock','coral beach','bridge drive','East China Sea','snorkeling'],
  false,
  ARRAY['Tinu Beach (Heart Rock) requires a 5-min walk down a steep path — go at low tide for the best view of the heart shapes','Drive slowly over the bridge at sunset — the light on the water turns gold and the heart-shaped bay curves perfectly','The island has a small beach with good snorkeling directly below the bridge — easier access than Tinu'],
  'May–September (swimming) or year-round (scenery)',
  'Car essential (1.5 hrs from Naha via highway)',
  'Island free; parking ¥200',
  '1–2 hours',
  ''
),

(
  'okinawa-peace-memorial-park',
  'Okinawa Peace Memorial Park',
  'Okinawa', 'kyushu',
  ARRAY['history'],
  'The most important memorial to the Battle of Okinawa (1945), which killed 200,000 people — more than the atomic bombs combined, including 1 in 4 Okinawan civilians. The "Cornerstone of Peace" lists all 241,000 names of everyone who died, regardless of nationality. The adjacent Peace Memorial Museum is one of the most carefully designed war history museums in Japan.',
  '444 Mabuni, Itoman, Okinawa 901-0333',
  26.0762, 127.7088,
  'https://images.unsplash.com/photo-1513883049090-d0b7439799bf?w=1200&auto=format&fit=crop&q=80',
  ARRAY['WWII','Battle of Okinawa','Cornerstone of Peace','memorial','240,000 names'],
  false,
  ARRAY['The Cornerstone of Peace has over 241,000 names inscribed — searching for specific nationalities (US, UK, Korean) reveals the war''s international scale','The museum''s final room, a survivor testimony video booth, requires a separate 20 minutes — do not skip it','June 23 (Okinawa Memorial Day) draws thousands; otherwise the park is peaceful and largely crowd-free'],
  'Year-round (avoid Obon weekend in August)',
  'Bus from Naha (~1 hr) or rental car',
  'Park free; museum ¥300 adults',
  '2–2.5 hours',
  'https://www.peace-museum.pref.okinawa.jp/english/'
),

(
  'yanbaru-national-park',
  'Yanbaru National Park',
  'Okinawa', 'kyushu',
  ARRAY['nature'],
  'The ancient subtropical rainforest covering northern Okinawa — a UNESCO World Heritage site and the last refuge of species found nowhere else on Earth. The Okinawa Rail (Yambaru Kuina), the Okinawa woodpecker, and the Okinawa spiny rat all evolved here in isolation. The forest is dense, dark, and extraordinarily alive.',
  'Kunigami Village, Kunigami-gun, Okinawa 905-1412',
  26.7600, 128.2100,
  'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&auto=format&fit=crop&q=80',
  ARRAY['UNESCO','Okinawa Rail','endemic species','subtropical rainforest','birdwatching'],
  false,
  ARRAY['Night tours with a local guide are the best way to see the Okinawa Rail — it''s nocturnal and rarely seen in daylight','The Daisekirinzan rock formation at the park''s northern tip: 80 million-year-old limestone karst towers draped in jungle','The park visitor center in Kunigami has free telescopes for birdwatching — Yambaru Kuina is most active at dawn'],
  'November–May (dry season, best wildlife viewing)',
  'Car recommended (2 hrs from Naha)',
  'Park free; some trails ¥300',
  'Half day',
  ''
),

(
  'nago-pineapple-park',
  'Nago Pineapple Park',
  'Okinawa', 'kyushu',
  ARRAY['food','activity'],
  'A quirky and beloved Okinawan attraction where autonomous pineapple-shaped carts carry you through a real pineapple plantation while a recorded guide explains cultivation. The destination is the enormous food hall: pineapple wine, pineapple vinegar, pineapple beer, pineapple jam, pineapple ice cream — and surprisingly, all of it is excellent.',
  '1195 Biimata, Nago, Okinawa 905-0005',
  26.5850, 127.9700,
  'https://images.unsplash.com/photo-1546630392-db5b1f04874a?w=1200&auto=format&fit=crop&q=80',
  ARRAY['pineapple','family','tropical fruit','wine tasting','Okinawa food'],
  false,
  ARRAY['The autonomous cart tour is amusingly earnest — pineapple history narrated with total seriousness by a cartoon pineapple character','The pineapple soft serve (¥380) is genuinely excellent — fresh pineapple, not artificial flavor','Pineapple wine sampling is free and generous — visitors consistently leave buying more than planned'],
  'Year-round',
  'Car (40 min from Naha, stop en route to Churaumi Aquarium) or bus to Nago',
  '¥850 adults (includes cart tour)',
  '1–1.5 hours',
  'https://www.pineapple-park.com'
),

(
  'shikinaen-garden',
  'Shikinaen Royal Garden',
  'Okinawa', 'kyushu',
  ARRAY['history'],
  'The secondary royal residence of the Ryukyu Kingdom — a pond-centered garden that blends Chinese, Japanese, and indigenous Ryukyuan design in a way found nowhere else. UNESCO World Heritage. Far quieter than Shuri Castle, with the same ochre-painted wooden pavilions reflected in a lotus pond surrounded by Ryukyuan limestone walls.',
  '421-7 Shikina, Naha, Okinawa 902-0072',
  26.2085, 127.7304,
  'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&auto=format&fit=crop&q=80',
  ARRAY['UNESCO','Ryukyu Kingdom','royal garden','pond garden','lotus','quiet'],
  false,
  ARRAY['Visit in the morning — the garden sees very few visitors before 10 AM even in high season','The main pavilion (Udun) overlooks the lotus pond and has a veranda for sitting — unlike most Japanese garden buildings, you can actually enter','The garden''s water system is ingeniously designed: fresh water flows in from the north and exits to the south via limestone channels'],
  'Year-round; June–July for lotus flowers in the pond',
  'Bus #33 from Naha bus terminal (~15 min) or 20 min walk from Shuri Station',
  '¥400 adults',
  '45 min–1 hour',
  ''
);
