import { config } from 'dotenv';
import { createClient } from '@supabase/supabase-js';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
config({ path: join(__dirname, '../.env.local') });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

const spots = [
  // ── OKINAWA Main Island ──
  { id: 'cape-manzamo', name: 'Cape Manzamo', prefecture: 'Okinawa', region: 'kyushu', categories: ['nature'], description: "A dramatic clifftop overlooking the East China Sea, named after a grassy plateau wide enough for 10,000 people to sit. The elephant-trunk-shaped rock arch is one of Okinawa's most iconic views.", address: '恩納村恩納, Onna-son, Okinawa', lat: 26.4997, lng: 127.7341, image_url: 'https://images.unsplash.com/photo-1580648214776-adadea2bccea?w=1200&auto=format&fit=crop&q=80', tags: ['cliffs', 'ocean view', 'sunset', 'free entry'], is_premium: false, highlights: ['Elephant-trunk rock arch at ocean edge', 'Sunsets over the East China Sea', 'Accessible by public bus from Naha', 'Free entry — least crowded on weekday mornings'], best_season: 'year-round', access: 'Bus from Naha (Route 120) to Manzamo stop, ~1.5 hours', admission: 'Free', duration: '30–60 min', website_url: null },
  { id: 'zakimi-castle', name: 'Zakimi Castle Ruins', prefecture: 'Okinawa', region: 'kyushu', categories: ['history', 'spiritual'], description: "One of the finest examples of Ryukyu castle architecture, Zakimi Castle is a UNESCO World Heritage Site known for its graceful double-arched gates — unusually sophisticated for their 15th-century construction.", address: '座喜味, Yomitan-son, Okinawa', lat: 26.4282, lng: 127.7157, image_url: 'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=1200&auto=format&fit=crop&q=80', tags: ['UNESCO', 'castle ruins', 'Ryukyu', 'hilltop'], is_premium: false, highlights: ['UNESCO World Heritage Site', 'Double-arched gate — rarest surviving in Ryukyu', 'Hilltop panoramas to the East China Sea', 'Illuminated at night on weekends'], best_season: 'year-round', access: 'By car from Naha ~45 min; limited bus access', admission: 'Free', duration: '30–60 min', website_url: null },
  { id: 'katsuren-castle', name: 'Katsuren Castle Ruins', prefecture: 'Okinawa', region: 'kyushu', categories: ['history'], description: "Perched dramatically on a hill overlooking Katsuren Peninsula and the Pacific, this UNESCO-listed castle is linked to Amawari — one of Ryukyu's most celebrated warrior lords. Views from the upper ramparts are extraordinary.", address: '勝連城, Uruma City, Okinawa', lat: 26.3220, lng: 127.8660, image_url: 'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=1200&auto=format&fit=crop&q=80', tags: ['UNESCO', 'castle', 'ocean view', 'Amawari'], is_premium: false, highlights: ['UNESCO World Heritage Site', 'Ocean views on three sides from the summit', 'Story of Amawari, the rebel lord of Ryukyu', 'Less-visited than Shuri — often nearly empty'], best_season: 'year-round', access: 'By car from Naha ~50 min; bus to Katsuren', admission: 'Free', duration: '45–90 min', website_url: null },
  { id: 'kokusai-dori', name: 'Kokusai-dori Street', prefecture: 'Okinawa', region: 'kyushu', categories: ['food'], description: "Naha's 1.6km International Street is Okinawa's culinary heartland — awamori distilleries, soki soba counters, shisa pottery shops, and izakayas serving champuru and Okinawa sausage. Come hungry.", address: '国際通り, Naha City, Okinawa', lat: 26.2170, lng: 127.6870, image_url: 'https://images.unsplash.com/photo-1509909756405-be0199881695?w=1200&auto=format&fit=crop&q=80', tags: ['food street', 'awamori', 'shopping', 'soba'], is_premium: false, highlights: ['Okinawa soba and champuru stalls', 'Awamori (local rice liquor) tasting shops', 'Side streets lead to Makishi public market', 'Live sanshin (Okinawan shamisen) performances evenings'], best_season: 'year-round', access: '10 min walk from Naha Airport via monorail (Kencho-mae station)', admission: 'Free', duration: '2–3 hours', website_url: null },
  { id: 'himeyuri-museum', name: 'Himeyuri Peace Museum', prefecture: 'Okinawa', region: 'kyushu', categories: ['history'], description: "A devastating and essential memorial to the 136 young Okinawan schoolgirls who served as field nurses in the final Battle of Okinawa. Their diaries, photos, and testimonies make this one of Japan's most moving wartime museums.", address: '糸満市伊原, Itoman City, Okinawa', lat: 26.1020, lng: 127.6860, image_url: 'https://images.unsplash.com/photo-1563212958-3f8d35e69b3f?w=1200&auto=format&fit=crop&q=80', tags: ['WWII', 'memorial', 'Okinawa battle', 'student nurses'], is_premium: false, highlights: ['Voices of student nurses who died in 1945', 'Personal diaries and photographs on display', 'Located near the actual cave where many perished', 'Essential context for understanding Okinawan identity'], best_season: 'year-round', access: 'By bus from Naha (Route 82) ~1 hour, or taxi from Naha ~30 min', admission: '¥310', duration: '1–2 hours', website_url: 'https://www.himeyuri.or.jp/EN/info.html' },
  { id: 'cape-hedo', name: 'Cape Hedo', prefecture: 'Okinawa', region: 'kyushu', categories: ['nature'], description: "The wild, windswept northernmost tip of Okinawa main island, where the Pacific Ocean and East China Sea visibly meet in churning swells. A monument commemorates Okinawa's return to Japan in 1972.", address: '国頭村辺戸, Kunigami-son, Okinawa', lat: 26.8710, lng: 128.2540, image_url: 'https://images.unsplash.com/photo-1580648214776-adadea2bccea?w=1200&auto=format&fit=crop&q=80', tags: ['northernmost point', 'ocean', 'scenic', 'Yanbaru'], is_premium: false, highlights: ['Northernmost point of Okinawa main island', 'Two oceans meeting in visible currents', 'Yanbaru jungle surrounds the approach road', 'Stone monument marking Okinawan reversion to Japan'], best_season: 'year-round', access: 'By car from Naha ~2 hours north; no bus service', admission: 'Free', duration: '30–60 min', website_url: null },
  { id: 'tsuboya-pottery', name: 'Tsuboya Pottery District', prefecture: 'Okinawa', region: 'kyushu', categories: ['history', 'food'], description: "A cobblestone lane in Naha where Okinawan pottery (yachimun) has been crafted since the 17th century. Around 20 active kilns and galleries sell shisa guardian lions, sake cups, and coral-patterned bowls.", address: '壺屋, Naha City, Okinawa', lat: 26.2147, lng: 127.6914, image_url: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=1200&auto=format&fit=crop&q=80', tags: ['pottery', 'yachimun', 'shisa', 'craft'], is_premium: false, highlights: ['Over 300 years of unbroken pottery tradition', 'Living workshops alongside retail galleries', 'Traditional shisa lion-dog sculptures', 'Yachimun-no-Sato village in Yomitan for larger selections'], best_season: 'year-round', access: '10 min walk from Makishi monorail station', admission: 'Free', duration: '1–2 hours', website_url: null },
  { id: 'makishi-market', name: 'Makishi Public Market', prefecture: 'Okinawa', region: 'kyushu', categories: ['food'], description: "The beating heart of Naha street food culture. Buy fish, pork, or sea snake from vendors below, carry it to the 2F restaurants, and have it cooked while you eat. Rebuilt 2023 — modern building, same local energy.", address: '牧志3丁目, Naha City, Okinawa', lat: 26.2172, lng: 127.6895, image_url: 'https://images.unsplash.com/photo-1509909756405-be0199881695?w=1200&auto=format&fit=crop&q=80', tags: ['market', 'seafood', 'Okinawa food', 'cook-your-own'], is_premium: false, highlights: ["Buy-and-cook market — take raw food upstairs to be cooked", 'Sea snake, sea grapes, and pork everything', "One of Japan's most famous public markets", 'Rebuilt 2023 — modern building, same local character'], best_season: 'year-round', access: '2 min walk from Makishi monorail station', admission: 'Free (food costs extra)', duration: '1–2 hours', website_url: null },
  // ── OKINAWA Miyako ──
  { id: 'irabu-bridge', name: 'Irabu Bridge', prefecture: 'Okinawa', region: 'kyushu', categories: ['nature', 'activity'], description: "Japan's longest toll-free bridge at 3.54km, connecting Miyako Island to Irabu Island over waters so turquoise they look computer-generated. Driving or cycling across at sunset is one of the great drives in Japan.", address: '伊良部大橋, Miyakojima City, Okinawa', lat: 24.8040, lng: 125.2000, image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80', tags: ['bridge', 'turquoise water', 'cycling', 'sunset'], is_premium: false, highlights: ["Longest toll-free bridge in Japan at 3.54km", 'Waters visible in 5 shades of blue from the bridge', 'Sunset cycling is a Miyako Island staple', 'Connects to quiet beaches and caves on Irabu Island'], best_season: 'year-round', access: 'Bicycle rental from central Miyako city, 15 min ride to bridge entrance', admission: 'Free', duration: '30 min–2 hours', website_url: null },
  { id: 'yonaha-maehama', name: 'Yonaha Maehama Beach', prefecture: 'Okinawa', region: 'kyushu', categories: ['nature', 'activity'], description: "A 7km arc of powdered white sand ranked by Michelin as one of Japan's finest beaches. The water graduates from pale jade to deep cobalt — this is what Japanese beach paradise actually looks like.", address: '与那覇, Miyakojima City, Okinawa', lat: 24.7450, lng: 125.2740, image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80', tags: ['beach', 'white sand', 'Michelin', 'Miyako'], is_premium: false, highlights: ['7km of unbroken white sand — longest in Okinawa', 'Michelin Green Guide starred beach', 'Shallow, calm water — safe for families', 'Adjacent luxury hotels with beach access'], best_season: 'spring,summer,autumn', access: 'By rental car from Miyako city, 20 min; taxi available', admission: 'Free', duration: 'Half day or full day', website_url: null },
  { id: 'sunayama-beach', name: 'Sunayama Beach', prefecture: 'Okinawa', region: 'kyushu', categories: ['nature'], description: "Down a steep sand dune path, Sunayama reveals a natural rock arch framing a private cove of crystalline water. One of the most photographed spots in Miyako — arrive early to have the arch to yourself.", address: '砂山, Miyakojima City, Okinawa', lat: 24.8030, lng: 125.2700, image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80', tags: ['rock arch', 'hidden cove', 'Miyako', 'snorkeling'], is_premium: false, highlights: ["Natural stone arch framing the sea — Miyako's icon", 'Sand dune entrance adds to the discovery feeling', 'Snorkeling around the arch base', 'Small and secluded — best before 10am'], best_season: 'spring,summer,autumn', access: 'By rental car from Miyako city, 10 min; walk down dune path', admission: 'Free', duration: '1–3 hours', website_url: null },
  { id: 'east-hennazaki-cape', name: 'East Hennazaki Cape', prefecture: 'Okinawa', region: 'kyushu', categories: ['nature'], description: "A narrow 2km peninsula jutting into the Pacific with a lighthouse at the tip, flanked by lily fields in spring. A National Scenic Beauty — the walk out feels like being on the prow of a ship sailing into open ocean.", address: '城辺東平安名崎, Miyakojima City, Okinawa', lat: 24.9160, lng: 125.4290, image_url: 'https://images.unsplash.com/photo-1580648214776-adadea2bccea?w=1200&auto=format&fit=crop&q=80', tags: ['cape', 'lighthouse', 'lily fields', 'Pacific'], is_premium: false, highlights: ['National Scenic Beauty designation', 'Ocean on both sides the entire 2km walk', 'Wild lily fields in bloom February–April', 'Lighthouse with 360° Pacific views at the tip'], best_season: 'spring,summer,autumn', access: 'By rental car from Miyako city, 30 min east', admission: 'Free (lighthouse interior ¥150)', duration: '1–2 hours', website_url: null },
  // ── OKINAWA Yaeyama ──
  { id: 'kabira-bay', name: 'Kabira Bay', prefecture: 'Okinawa', region: 'kyushu', categories: ['nature'], description: "Ishigaki Island's most famous view — tiny forested islands floating in water so clear you can count the coral heads from a glass-bottomed boat. Swimming is prohibited to protect the black pearl oyster farms, keeping it pristine.", address: '川平, Ishigaki City, Okinawa', lat: 24.4570, lng: 124.1530, image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80', tags: ['bay', 'glass-bottom boat', 'black pearl', 'Ishigaki'], is_premium: false, highlights: ['Glass-bottom boat tours over living coral', 'Black pearl farming area visible below', 'No swimming allowed — preserves extraordinary clarity', "One of Japan's top-100 scenic spots"], best_season: 'year-round', access: 'Bus from Ishigaki city center ~35 min; boat tours ¥1,100', admission: '¥1,100 (boat tour)', duration: '1–2 hours', website_url: null },
  { id: 'taketomi-island', name: 'Taketomi Island', prefecture: 'Okinawa', region: 'kyushu', categories: ['history', 'nature'], description: "A 10-minute ferry from Ishigaki, Taketomi preserves a living Ryukyu village: white-walled homes topped with red clay roof tiles and guardian shisa, unpaved lanes edged with coral walls, and water buffalo carts at walking pace.", address: '竹富町竹富, Taketomi-cho, Okinawa', lat: 24.3260, lng: 124.0750, image_url: 'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=1200&auto=format&fit=crop&q=80', tags: ['Ryukyu village', 'water buffalo', 'star sand', 'car-free'], is_premium: false, highlights: ['Water buffalo cart rides through preserved Ryukyu lanes', 'No cars on the island — rent a bicycle', 'Star Sand Beach (Kondoi) with tiny star-shaped grains', 'Traditional houses maintained exactly as they were'], best_season: 'year-round', access: 'Ferry from Ishigaki port, 10 min, ¥1,000 round trip', admission: '¥1,000 (ferry)', duration: 'Half day or full day', website_url: null },
  { id: 'iriomote-island', name: 'Iriomote Island', prefecture: 'Okinawa', region: 'kyushu', categories: ['nature', 'activity'], description: "Over 90% primary jungle and UNESCO World Heritage listed, Iriomote is home to the critically endangered Iriomote wildcat. Dense mangrove river kayaking, remote waterfall trekking, and some of Japan's clearest coral waters.", address: '竹富町西表, Taketomi-cho, Okinawa', lat: 24.3690, lng: 123.8040, image_url: 'https://images.unsplash.com/photo-1552083375-1447ce886485?w=1200&auto=format&fit=crop&q=80', tags: ['UNESCO', 'jungle', 'wildcat', 'kayaking', 'mangrove'], is_premium: false, highlights: ["UNESCO World Heritage jungle — most isolated in Japan", 'Iriomote wildcat — critically endangered, ~100 remain', 'Mangrove kayaking on Urauchi River to Mariyudu Falls', 'Snorkeling at Barasu Island — beach made entirely of coral fragments'], best_season: 'year-round', access: 'Ferry from Ishigaki port ~40 min; guided tours recommended', admission: 'Tours from ¥5,000', duration: 'Full day or overnight', website_url: null },
  { id: 'yonaguni-island', name: 'Yonaguni Island', prefecture: 'Okinawa', region: 'kyushu', categories: ['nature', 'activity'], description: "Japan's westernmost island — closer to Taiwan than to Tokyo. Famous for massive schools of hammerhead sharks in winter, mysterious underwater rock formations, and wild Yonaguni horses that roam the cliffs freely.", address: '与那国町, Yonaguni-cho, Okinawa', lat: 24.4672, lng: 123.0139, image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80', tags: ['westernmost Japan', 'hammerhead sharks', 'underwater ruins', 'wild horses'], is_premium: false, highlights: ["Japan's westernmost point — Taiwan visible on clear days", 'Hammerhead shark diving (December–March) — dozens at once', 'Yonaguni Monument — mysterious underwater stepped structure', 'Wild Yonaguni horses roaming free along clifftops'], best_season: 'year-round', access: 'Flight from Naha or Ishigaki (~1 hr); accommodation limited', admission: 'Varies by activity', duration: 'Full day or overnight stay', website_url: null },

  // ── FUKUOKA ──
  { id: 'itoshima-peninsula', name: 'Itoshima Peninsula', prefecture: 'Fukuoka', region: 'kyushu', categories: ['nature', 'food'], description: "Fukuoka's weekend escape: a rugged peninsula 30 minutes from the city with sea-cave shrines, oyster shacks serving winter harvests direct from the water, bohemian farm-to-table cafés, and beaches facing the Genkai Sea.", address: '糸島市, Itoshima City, Fukuoka', lat: 33.5550, lng: 130.1960, image_url: 'https://images.unsplash.com/photo-1542640244-7e672d6cef4e?w=1200&auto=format&fit=crop&q=80', tags: ['oysters', 'beach cafés', 'cycling', 'twin torii'], is_premium: false, highlights: ['Sakurai Futamigaura — twin torii standing in the sea', 'Oyster huts (Nov–Mar) — grill your own from the farm', 'Road cyclist paradise — 80km coastal circuit', 'DIY ceramics workshops and farm cafés'], best_season: 'year-round', access: 'JR Chikuhi Line from Hakata ~35 min; car recommended to explore', admission: 'Free (oysters from ~¥1,000)', duration: 'Half day or full day', website_url: null },
  { id: 'munakata-taisha', name: 'Munakata Taisha', prefecture: 'Fukuoka', region: 'kyushu', categories: ['spiritual'], description: "A UNESCO World Heritage shrine complex of three separate shrines dedicated to three goddesses of the sea. The outermost island, Okinoshima, is so sacred no women have ever set foot on it and visiting men must ritually bathe before landing.", address: '宗像市田島, Munakata City, Fukuoka', lat: 33.8110, lng: 130.5330, image_url: 'https://images.unsplash.com/photo-1542640244-7e672d6cef4e?w=1200&auto=format&fit=crop&q=80', tags: ['UNESCO', 'sea goddesses', 'Okinoshima', 'sacred island'], is_premium: false, highlights: ['UNESCO World Heritage Site', 'Okinoshima island — only 200 men allowed to visit once per year', 'Ancient sea-route shrine connecting Japan and the continent', 'Shimpokan museum holds priceless votive treasures from the island'], best_season: 'year-round', access: 'Nishitetsu Bus from Tenjin ~45 min; JR Munakata-Tamashima station', admission: 'Free', duration: '1–2 hours', website_url: 'https://munakata-taisha.or.jp/' },
  { id: 'nanzoin-temple', name: 'Nanzoin Temple', prefecture: 'Fukuoka', region: 'kyushu', categories: ['spiritual'], description: "Home to the world's largest bronze reclining Buddha at 41 meters long and 11 meters tall — yet almost no tourists outside Fukuoka know it exists. The grounds also hold over 350 statues of Buddha's disciples, each with a different expression.", address: '篠栗町篠栗1035, Sasaguri-cho, Fukuoka', lat: 33.6440, lng: 130.5290, image_url: 'https://images.unsplash.com/photo-1542640244-7e672d6cef4e?w=1200&auto=format&fit=crop&q=80', tags: ['reclining Buddha', 'bronze', 'pilgrimage', 'Sasaguri'], is_premium: false, highlights: ["World's largest bronze reclining Buddha (41m long)", "Unknown to international tourism — never crowded", "Enter the Buddha's interior chamber", '350 Rakan statues with uniquely individual faces'], best_season: 'year-round', access: 'Fukuhoku-Yutaka Line to Kido-Nanzoin-Mae station, 30 min from Hakata', admission: 'Free (main grounds)', duration: '1–2 hours', website_url: null },
  { id: 'mojiko-retro', name: 'Mojiko Retro District', prefecture: 'Fukuoka', region: 'kyushu', categories: ['history', 'food'], description: "A preserved Meiji-era port district at the narrow strait between Honshu and Kyushu. Art Deco customs halls, banana wharf markets, and yakitori stalls draw weekend visitors. The suspension bridge to Shimonoseki is spectacular at night.", address: '門司区東港町, Kitakyushu City, Fukuoka', lat: 33.9440, lng: 130.9600, image_url: 'https://images.unsplash.com/photo-1542640244-7e672d6cef4e?w=1200&auto=format&fit=crop&q=80', tags: ['retro architecture', 'port', 'banana', 'Kanmon Straits'], is_premium: false, highlights: ['Meiji and Taisho-era architecture — rare surviving port town', "Yakikaree — Moji's unique fried curry specialty", 'Kanmon Straits — watch massive cargo ships from centimeters away', 'Nightly illumination of the Kanmon Bridge'], best_season: 'year-round', access: 'JR Kagoshima Line to Mojiko Station, 1h from Hakata direct', admission: 'Free (area)', duration: '2–4 hours', website_url: null },
  { id: 'kushida-shrine', name: 'Kushida Shrine', prefecture: 'Fukuoka', region: 'kyushu', categories: ['spiritual'], description: "Hakata's guardian shrine and birthplace of the Gion Yamakasa festival — every July, enormous float-mountains weighing over 1 tonne are raced through city streets at 4am. Outside festival season, a peaceful enclave in downtown Hakata.", address: '博多区上川端町, Hakata Ward, Fukuoka', lat: 33.6060, lng: 130.4100, image_url: 'https://images.unsplash.com/photo-1542640244-7e672d6cef4e?w=1200&auto=format&fit=crop&q=80', tags: ['Yamakasa festival', 'float', 'shrine', 'Hakata'], is_premium: false, highlights: ['Sacred birthplace of Gion Yamakasa festival (UNESCO Intangible Heritage)', 'Full-size Yamakasa float on permanent display inside', 'Illuminated ginkgo tree at entrance in autumn', 'Annual July festival draws 1 million spectators'], best_season: 'year-round', access: '5 min walk from Nakasu-Kawabata subway station', admission: 'Free', duration: '30–60 min', website_url: null },
  { id: 'akizuki-castle-ruins', name: 'Akizuki Castle Ruins', prefecture: 'Fukuoka', region: 'kyushu', categories: ['history', 'nature'], description: "A serene castle-town deep in the mountains 60km from Fukuoka, preserved by accident of geography — the Kuroda clan seat that never had to modernize. The approach road lined with 200-year-old cherry trees is among Kyushu's most beautiful.", address: '朝倉市秋月, Asakura City, Fukuoka', lat: 33.5310, lng: 130.6890, image_url: 'https://images.unsplash.com/photo-1542640244-7e672d6cef4e?w=1200&auto=format&fit=crop&q=80', tags: ['castle town', 'cherry blossoms', 'Edo period', 'Kuroda clan'], is_premium: false, highlights: ['Megane-bashi bridge and Sugi-no-baba cedar avenue', '200-year-old cherry trees in full bloom (late March)', 'Near-complete Edo-period castle town layout survives', 'Virtually unknown outside Fukuoka — no tourist queues'], best_season: 'spring,autumn', access: 'Bus from Amagase station (JR Kyudai Line) ~20 min; 90 min total from Fukuoka', admission: 'Free (castle ruins)', duration: '2–3 hours', website_url: null },

  // ── HIROSHIMA ──
  { id: 'hiroshima-peace-memorial', name: 'Hiroshima Peace Memorial (A-Bomb Dome)', prefecture: 'Hiroshima', region: 'chugoku', categories: ['history'], description: "The only structure left standing near the epicenter of the world's first atomic bomb attack on August 6, 1945. Left deliberately unrestored as a permanent witness and a plea for its non-repetition. UNESCO World Heritage Site.", address: '中島町1, Naka Ward, Hiroshima', lat: 34.3955, lng: 132.4533, image_url: 'https://images.unsplash.com/photo-1535139262971-ab8d6c2ccee5?w=1200&auto=format&fit=crop&q=80', tags: ['UNESCO', 'atomic bomb', 'peace', 'WWII', 'iconic'], is_premium: false, highlights: ['UNESCO World Heritage Site — the most powerful peace symbol in Asia', 'Preserved exactly as the atomic blast left it', 'Across the river from the Peace Memorial Museum', 'The Peace Flame has burned continuously since 1964'], best_season: 'year-round', access: 'Tram Line 2 or 6 from Hiroshima Station, 15 min to Genbaku Dome-mae', admission: 'Free (exterior)', duration: '30–60 min', website_url: 'https://www.pcf.city.hiroshima.jp/virtual/VirtualMuseum_e/' },
  { id: 'itsukushima-shrine', name: 'Itsukushima Shrine', prefecture: 'Hiroshima', region: 'chugoku', categories: ['spiritual', 'history'], description: "The great floating torii gate of Miyajima is Japan's most iconic image — a vermilion gateway standing in tidal waters, framing the island's forested mountains. At high tide it appears to float. UNESCO World Heritage and National Treasure.", address: '宮島町1-1, Hatsukaichi City, Hiroshima', lat: 34.2956, lng: 132.3194, image_url: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&auto=format&fit=crop&q=80', tags: ['floating torii', 'UNESCO', 'Miyajima', 'sacred deer', 'National Treasure'], is_premium: false, highlights: ["Floating torii gate — Japan's most recognisable image", 'High tide and low tide give completely different experiences', 'Sacred deer wander freely around the shrine', 'No cars on the island — 10 min ferry from mainland'], best_season: 'year-round', access: 'JR Sanyo Line to Miyajimaguchi, then JR ferry 10 min, ¥200', admission: '¥300 (shrine interior)', duration: '3–5 hours', website_url: 'https://www.itsukushimajinja.jp/en/index.html' },
  { id: 'hiroshima-peace-museum', name: 'Hiroshima Peace Memorial Museum', prefecture: 'Hiroshima', region: 'chugoku', categories: ['history'], description: "An unflinching examination of August 6, 1945 and its aftermath — personal effects of victims, charred lunchboxes, melted glass, and shadows burned into stone. One of the world's most important museums and a transformative experience.", address: '中島町1-2, Naka Ward, Hiroshima', lat: 34.3941, lng: 132.4528, image_url: 'https://images.unsplash.com/photo-1535139262971-ab8d6c2ccee5?w=1200&auto=format&fit=crop&q=80', tags: ['atomic bomb museum', 'WWII', 'peace', 'must-see'], is_premium: false, highlights: ['Personal belongings of victims give the scale of loss a human face', "Sadako Sasaki's paper cranes on display", 'East Building: historical context of militarism and the bombing', 'Survivor testimonies available in audio and video'], best_season: 'year-round', access: 'Tram to Genbaku Dome-mae or Honkawa-cho; 5 min walk from dome', admission: '¥200', duration: '2–3 hours', website_url: 'https://hpmmuseum.jp/' },
  { id: 'onomichi', name: 'Onomichi', prefecture: 'Hiroshima', region: 'chugoku', categories: ['history', 'food'], description: "A hillside port town on the Seto Inland Sea, linked by cable car to a ridge-top temple walk through 25 historic temples. The narrow lanes, black cats, and cycling culture inspired Hayao Miyazaki. Famous for its layered shoyu ramen.", address: '尾道市, Onomichi City, Hiroshima', lat: 34.4085, lng: 133.1962, image_url: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&auto=format&fit=crop&q=80', tags: ['temple walk', 'cats', 'ramen', 'cycling', 'Miyazaki inspiration'], is_premium: false, highlights: ['Temple Walk: 25 temples connected by ridge paths — collect stamps', 'Start point of Shimanami Kaido cycling route', "Onomichi Ramen — shoyu broth with pork back fat", 'Black cats — the city embraces them as unofficial mascots'], best_season: 'year-round', access: 'JR Sanyo Shinkansen to Fukuyama, then local to Onomichi (30 min)', admission: 'Free (cable car ¥320)', duration: 'Half day to full day', website_url: null },
  { id: 'shimanami-kaido', name: 'Shimanami Kaido', prefecture: 'Hiroshima', region: 'chugoku', categories: ['activity', 'nature'], description: "A 70km cycling route connecting Honshu to Shikoku via six islands and six suspension bridges over the Seto Inland Sea — considered one of the world's top cycling routes. Views from each bridge span are extraordinary.", address: 'Connecting Onomichi (Hiroshima) to Imabari (Ehime)', lat: 34.2500, lng: 132.9890, image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&auto=format&fit=crop&q=80', tags: ['cycling', 'bridges', 'islands', 'Seto Inland Sea', 'world class'], is_premium: false, highlights: ["One of the world's top-10 cycling routes (CNN Travel)", 'Six islands, six suspension bridges with dedicated cycle lanes', 'Bicycles can be rented at one end and returned at the other', 'Lemon farms and local ramen restaurants mid-route'], best_season: 'spring,summer,autumn', access: 'Start at Onomichi Station; rental bikes available from ¥1,100/day', admission: '¥1,100/day (bicycle)', duration: '1–2 days (full route)', website_url: 'https://www.go-shimanami.jp/' },
  { id: 'tomonoura', name: 'Tomonoura', prefecture: 'Hiroshima', region: 'chugoku', categories: ['history', 'nature'], description: "An ancient port town so well preserved that Miyazaki used it as reference for Ponyo. Stone lighthouse, sake breweries fermenting tidewater-cooled sake, and a hillside temple where Sakamoto Ryoma hid during the Meiji Restoration.", address: '鞆町, Fukuyama City, Hiroshima', lat: 34.3770, lng: 133.3820, image_url: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&auto=format&fit=crop&q=80', tags: ['Ponyo', 'ancient port', 'sake', 'Miyazaki', 'Sakamoto Ryoma'], is_premium: false, highlights: ["Japan's last surviving stone lighthouse (Joya-to, 1859)", "Inspiration for Miyazaki's Ponyo on the Cliff by the Sea", 'Homeishu — medicinal sake brewed here since 1659', "Sunset reflected in the fishing harbor — Japan's most-painted view"], best_season: 'year-round', access: 'Bus from Fukuyama Station (JR Shinkansen stop), 30 min', admission: 'Free (area)', duration: '2–4 hours', website_url: null },
  { id: 'shukkei-en', name: 'Shukkei-en Garden', prefecture: 'Hiroshima', region: 'chugoku', categories: ['nature', 'history'], description: "A 400-year-old stroll garden in central Hiroshima — the name means 'garden of condensed landscapes' for its miniature mountains, streams, and stone islands. One of the few places in Hiroshima with direct atomic bomb survivor stories.", address: '上幟町2-11, Naka Ward, Hiroshima', lat: 34.3990, lng: 132.4630, image_url: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&auto=format&fit=crop&q=80', tags: ['Japanese garden', '400 years', 'atomic bomb survivors', 'cherry blossoms'], is_premium: false, highlights: ['400-year-old garden commissioned by the Asano clan', 'Atomic bomb survivors sought refuge here — memorial inside', 'Spring: cherry blossoms over the central pond', 'Autumn: maple reflections in the winding waterways'], best_season: 'spring,autumn', access: '5 min walk from Hiroshima Station; also accessible by tram', admission: '¥260', duration: '1–1.5 hours', website_url: null },
  { id: 'sandankyo-gorge', name: 'Sandankyo Gorge', prefecture: 'Hiroshima', region: 'chugoku', categories: ['nature'], description: "A 16km narrow gorge in the Nishi-Chugoku Mountains carved by the Nishiki River. Pools, cascades, and overhanging walls of moss-covered granite, accessible by rowboat and cliff-side paths. Spectacular autumn foliage.", address: '安芸太田町, Akiota-cho, Hiroshima', lat: 34.6050, lng: 132.1050, image_url: 'https://images.unsplash.com/photo-1552083375-1447ce886485?w=1200&auto=format&fit=crop&q=80', tags: ['gorge', 'rowboat', 'autumn foliage', 'mountains'], is_premium: false, highlights: ["National Scenic Beauty — among Japan's finest gorges", 'Rowboat through narrow water-level passages', 'Three-stage waterfall (Sandantaki) that names the gorge', 'Autumn foliage concentrated by canyon walls — color is intense'], best_season: 'spring,autumn', access: 'Bus from Hiroshima Station ~75 min (Hiroshima Bus)', admission: '¥500 (rowboat)', duration: '3–5 hours', website_url: null },
  { id: 'hiroshima-castle', name: 'Hiroshima Castle', prefecture: 'Hiroshima', region: 'chugoku', categories: ['history'], description: "Rebuilt in 1958 after the atomic bomb destroyed the original, Hiroshima Castle offers exhibits on samurai life and the city's reconstruction. The surrounding moat park is one of Hiroshima's best cherry blossom destinations.", address: '21-1 Motomachicho, Naka Ward, Hiroshima', lat: 34.4022, lng: 132.4561, image_url: 'https://images.unsplash.com/photo-1535139262971-ab8d6c2ccee5?w=1200&auto=format&fit=crop&q=80', tags: ['castle', 'cherry blossoms', 'samurai', 'reconstruction'], is_premium: false, highlights: ['Five-story tenshu with feudal Hiroshima history exhibits', 'Best cherry blossom spot in central Hiroshima (late March)', "Story of the castle's destruction and 13-year rebuild", 'Free moat park gardens open year-round'], best_season: 'spring,year-round', access: 'Tram to Kamiyacho, then 15 min walk; or castle-bound bus from station', admission: '¥370', duration: '1–2 hours', website_url: null },
  { id: 'takehara', name: 'Takehara Preservation District', prefecture: 'Hiroshima', region: 'chugoku', categories: ['history'], description: "A sake-brewing merchant town frozen in late Edo-period form — sake breweries, merchant houses with latticed facades, and a ridge-top shrine with sea views. Called the 'Little Kyoto of Hiroshima,' it sees a fraction of the crowds.", address: '竹原市本町, Takehara City, Hiroshima', lat: 34.3410, lng: 132.9150, image_url: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&auto=format&fit=crop&q=80', tags: ['Edo period', 'sake', 'merchant town', 'preserved district'], is_premium: false, highlights: ["Historic townscape preservation area — one of Japan's finest", 'Active sake breweries offering tours and tastings', 'Elevated shrine gives panorama over tile rooftops to the sea', 'Connection to Barefoot Gen manga — birthplace of its creator'], best_season: 'year-round', access: 'JR Kure Line to Takehara Station, 1.5h from Hiroshima', admission: 'Free (area)', duration: '2–3 hours', website_url: null },
  { id: 'miyajima-momijidani', name: 'Momijidani Park', prefecture: 'Hiroshima', region: 'chugoku', categories: ['nature'], description: "A forest valley on Miyajima Island filled with hundreds of Japanese maple trees. Best visited in November when the crimson canopy reflects in the stream below. The ropeway to Mt. Misen starts here.", address: '宮島町紅葉谷, Hatsukaichi City, Hiroshima', lat: 34.2970, lng: 132.3200, image_url: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&auto=format&fit=crop&q=80', tags: ['autumn foliage', 'maple', 'Miyajima', 'ropeway', 'Mt. Misen'], is_premium: false, highlights: ["November maple foliage rated among Japan's finest", 'Stream reflects autumn color from both banks', 'Mt. Misen ropeway departs from the valley floor', 'Momiji manjyu — maple-leaf cakes sold in over 20 flavors'], best_season: 'autumn', access: '15 min walk from Miyajima ferry terminal; free entry to park', admission: 'Free (park); ¥1,840 ropeway', duration: '1–2 hours (park only)', website_url: null },
  { id: 'hiroshima-oyster', name: 'Hiroshima Oyster Experience', prefecture: 'Hiroshima', region: 'chugoku', categories: ['food'], description: "Hiroshima produces 60% of Japan's oysters — the Seto Inland Sea's nutrient-rich currents grow them fat and briny. Hire a grill at a waterfront shack in Miyajima or Etajima, eat them charcoal-grilled with lemon, or raw over rice.", address: 'Various locations around Hiroshima Bay and Miyajima', lat: 34.3280, lng: 132.5810, image_url: 'https://images.unsplash.com/photo-1560717789-0ac7c58ac90a?w=1200&auto=format&fit=crop&q=80', tags: ['oysters', '60% of Japan', 'grill-your-own', 'okonomiyaki'], is_premium: false, highlights: ["World-class oysters — three times larger than Pacific average", 'Grill-your-own oyster huts on the waterfront (Oct–Apr)', 'Hiroshima-style oyster okonomiyaki layered with flat noodles', 'Farm boat tours show the cultivation process up close'], best_season: 'autumn,winter', access: 'Various — Miyajima island has multiple oyster restaurants reachable by ferry', admission: 'Varies by restaurant', duration: '1–3 hours', website_url: null },
];

let success = 0, skipped = 0, errors = 0;

for (const spot of spots) {
  // DB has NOT NULL on website_url — use empty string as placeholder
  if (spot.website_url === null) spot.website_url = '';
  const { error } = await supabase.from('spots').upsert(spot, { onConflict: 'id', ignoreDuplicates: true });
  if (error) {
    console.log(`❌ ${spot.id}: ${error.message}`);
    errors++;
  } else {
    console.log(`✅ ${spot.id}`);
    success++;
  }
}

console.log(`\nDone: ${success} inserted, ${skipped} skipped, ${errors} errors`);
EOF
