-- ============================================================
-- New prefecture spots: Fukuoka, Saga, Nagasaki, Kagoshima, Okinawa
-- Run this in Supabase SQL Editor
-- Images: upload prefecture header images to Supabase Storage
--   spot-images/fukuoka.jpg
--   spot-images/saga.jpg
--   spot-images/nagasaki.jpg
--   spot-images/kagoshima.jpg
--   spot-images/okinawa.jpg
-- ============================================================

INSERT INTO spots (id, name, prefecture, region, categories, description, address, lat, lng, image_url, tags, is_premium, highlights, best_season, access, admission, duration, website_url) VALUES

-- ─── FUKUOKA ────────────────────────────────────────────────
(
  'dazaifu-tenmangu',
  'Dazaifu Tenmangu',
  'Fukuoka', 'kyushu',
  ARRAY['spiritual','history'],
  'One of Japan''s most important Shinto shrines, dedicated to Sugawara no Michizane, the deity of learning. Surrounded by 6,000 plum trees that burst into bloom each February.',
  '4-7-1 Saifu, Dazaifu, Fukuoka 818-0117',
  33.5125, 130.7335,
  'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&auto=format&fit=crop&q=80',
  ARRAY['shrine','plum trees','learning deity','Dazaifu'],
  false,
  ARRAY['Walk the 2 km approach lined with shops selling umegae-mochi (plum rice cakes)','The main hall is built over a pond — look for the arched bridges','Visit Dazaifu Tenmangu Art Museum housed in a striking Kengo Kuma building'],
  'February (plum blossoms) or November (autumn leaves)',
  '5 min walk from Nishitetsu Dazaifu Station',
  'Free',
  '1–2 hours',
  'https://www.dazaifutenmangu.or.jp/en'
),
(
  'itoshima-peninsula',
  'Itoshima Peninsula',
  'Fukuoka', 'kyushu',
  ARRAY['nature','food'],
  'A laid-back coastal peninsula just 30 minutes from Fukuoka city with sweeping ocean views, oyster shacks, sunset Instagram spots, and a growing craft scene.',
  'Itoshima, Fukuoka',
  33.5582, 130.1884,
  'https://images.unsplash.com/photo-1504214208698-ea1916a2195a?w=1200&auto=format&fit=crop&q=80',
  ARRAY['beach','oysters','sunset','coastal drive'],
  false,
  ARRAY['Eat freshly grilled oysters at a winter kakigoya (oyster hut) overlooking the sea','Sakurai Futamigaura — two ritual rocks in the sea connected by a sacred rope','The "Married Couple Rocks" are best at sunset when the sun sets between them'],
  'November–March (oyster season) or June–August (beach)',
  'JR Chikuhi Line from Hakata to Chikuzen-Maebaru (~30 min), then taxi/bike',
  'Free (oysters from ¥300/3 pcs)',
  'Half day',
  ''
),
(
  'nanzoin-temple',
  'Nanzoin Temple',
  'Fukuoka', 'kyushu',
  ARRAY['spiritual'],
  'Home to the world''s largest bronze reclining Buddha statue at 41 metres long — bigger than the Statue of Liberty. Set deep in cedar forest, this temple has a deeply serene atmosphere.',
  '35 Sasaguri, Sasaguri-machi, Kasuya-gun, Fukuoka 811-2405',
  33.5547, 130.5189,
  'https://images.unsplash.com/photo-1492571350019-22de08371fd3?w=1200&auto=format&fit=crop&q=80',
  ARRAY['reclining Buddha','bronze statue','forest temple','Sasaguri'],
  false,
  ARRAY['Rub the feet of the Buddha for good fortune — locals swear by it','The temple complex has over 88 shrines mirroring the Shikoku pilgrimage','Nanzoin is said to have the highest lotto jackpot rate in Japan — buy a ticket at the gate'],
  'March–May or October–November',
  '2 min walk from JR Kido-Nanzoin Mae Station (Sasaguri Line from Hakata, ~30 min)',
  'Free',
  '1 hour',
  ''
),
(
  'mojiko-retro',
  'Mojiko Retro District',
  'Fukuoka', 'kyushu',
  ARRAY['history','food'],
  'A beautifully preserved Meiji-era port town at the northern tip of Kyushu. European-style brick buildings, a pedestrian waterfront, and Japan''s best grilled curry.',
  'Mojiko, Kitakyushu, Fukuoka',
  33.9497, 130.9632,
  'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&auto=format&fit=crop&q=80',
  ARRAY['retro','Meiji era','port','焼きカレー'],
  false,
  ARRAY['Yakicurry (grilled curry rice with melted cheese) — try it at Door or Retro Curry','The old Moji Port Building now houses exhibits on the port''s trading history','Cross to Shimonoseki, Yamaguchi by ferry for ¥400 — one of Japan''s shortest international crossings'],
  'Year-round, spring for outdoor dining',
  'JR Kagoshima Main Line to Moji Station (~1 hr from Hakata)',
  'Free (buildings have small entry fees)',
  '2–3 hours',
  ''
),
(
  'fukuoka-yatai',
  'Fukuoka Yatai Stalls',
  'Fukuoka', 'kyushu',
  ARRAY['food'],
  'Fukuoka''s iconic open-air food stalls that pack out along the Naka River and Tenjin every evening. Squeeze in for tonkotsu ramen, yakitori, and cold beer under the city lights.',
  'Nakagawa, Chuo-ku, Fukuoka (riverside between Tenjin and Nakasu)',
  33.5896, 130.4017,
  'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=1200&auto=format&fit=crop&q=80',
  ARRAY['ramen','street food','yatai','nightlife'],
  true,
  ARRAY['Go after 6 PM — most stalls open from dusk until midnight or later','Each stall seats just 8–10 people; regulars return nightly and the owner knows their order','Try Hakata-style ramen: thin straight noodles in milky pork-bone broth with a soft-boiled egg'],
  'Year-round, cooler months most comfortable',
  'Tenjin or Nakasu-Kawabata subway stations',
  'Pay per dish (ramen from ¥800)',
  '1–2 hours',
  ''
),
(
  'shofukuji-zen',
  'Shofukuji Temple',
  'Fukuoka', 'kyushu',
  ARRAY['spiritual','history'],
  'Japan''s first Zen temple, founded in 1195 by Eisai who brought tea seeds back from China — making this the birthplace of Japanese tea culture. A hidden gem in the heart of Hakata.',
  '6-1 Gokushomachi, Hakata-ku, Fukuoka 812-0037',
  33.5972, 130.4175,
  'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&auto=format&fit=crop&q=80',
  ARRAY['Zen','oldest temple','tea history','Hakata'],
  false,
  ARRAY['The temple grounds are free and rarely crowded despite their historic importance','A plaque marks where Eisai planted Japan''s first tea seeds','Combine with a walk through the nearby Sumiyoshi area and its old merchant townhouses'],
  'March–May (azaleas) or October–November',
  '10 min walk from Hakata Station',
  'Free (outer grounds)',
  '30–45 min',
  ''
),

-- ─── SAGA ───────────────────────────────────────────────────
(
  'yoshinogari-park',
  'Yoshinogari Historical Park',
  'Saga', 'kyushu',
  ARRAY['history'],
  'Japan''s largest and most complete Yayoi period (300 BC – 300 AD) village reconstruction. Walk through ancient moat-encircled settlements and watchtowers on a 98-hectare site.',
  '1843 Higashideyama, Yoshinogari-cho, Kanzaki-gun, Saga 842-0002',
  33.3405, 130.4042,
  'https://images.unsplash.com/photo-1513883049090-d0b7439799bf?w=1200&auto=format&fit=crop&q=80',
  ARRAY['Yayoi','ancient Japan','archaeology','reconstruction'],
  false,
  ARRAY['The Northern Inner Enclosure contains ceremonial burial jars that changed understanding of ancient Japan','Costumed staff demonstrate ancient crafts on weekends','The viewing platform gives a dramatic overview of the double-moated village structure'],
  'March–May or October–November',
  '3 min walk from JR Yoshinogari-Koen Station (Nagasaki Line from Hakata ~35 min)',
  '¥460 adults, free Sat & Sun for basic areas',
  '2–3 hours',
  'https://www.yoshinogari.jp/en/'
),
(
  'karatsu-castle',
  'Karatsu Castle',
  'Saga', 'kyushu',
  ARRAY['history'],
  'A beautifully restored castle perched on a pine-covered promontory over Karatsu Bay, nicknamed "Dancing Crane Castle." The view over the bay from the top floor is stunning.',
  '8-1 Higashijojo, Karatsu, Saga 847-0016',
  33.4461, 129.9693,
  'https://images.unsplash.com/photo-1502863029862-5f2a8f22f24e?w=1200&auto=format&fit=crop&q=80',
  ARRAY['castle','bay view','Karatsu','coastal'],
  false,
  ARRAY['The castle connects to the pine-covered Niji-no-Matsubara beach by a long promenade — walk it at low tide','Visit the Karatsu Kunchi float museum nearby to see the elaborate autumn festival floats year-round','Combine with lunch at the Karatsu port fish market for ultra-fresh sashimi'],
  'April (cherry blossoms around castle) or autumn',
  'JR Chikuhi Line or Karatsu Line from Fukuoka Hakata to Karatsu (~1.5 hr), then 10 min walk',
  '¥500 adults',
  '1–1.5 hours',
  ''
),
(
  'yutoku-inari',
  'Yutoku Inari Shrine',
  'Saga', 'kyushu',
  ARRAY['spiritual'],
  'One of Japan''s three greatest Inari shrines, and the most architecturally dramatic in Kyushu. The main hall is built on stilts over a forested hillside using the same method as Kyoto''s Kiyomizudera.',
  '1番地 Tashiro, Kashima, Saga 849-1321',
  33.1869, 130.1742,
  'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&auto=format&fit=crop&q=80',
  ARRAY['Inari','fox shrine','vermilion','hillside'],
  false,
  ARRAY['Climb the outer staircase for free views over the gate and forest without paying entry','The inner shrine complex is much quieter than Fushimi Inari and far less photographed','November is spectacular when autumn color frames the vermilion buildings'],
  'March–April or November',
  'Bus from JR Hizen-Kashima Station (~15 min)',
  '¥200 adults (inner area)',
  '45 min',
  ''
),
(
  'arita-pottery-town',
  'Arita Pottery Town',
  'Saga', 'kyushu',
  ARRAY['history','food'],
  'The birthplace of Japanese porcelain, where ceramic production began in 1616 after kaolin clay was discovered. The main street is lined with kilns, galleries, and manufacturers exporting worldwide.',
  'Arita, Nishi-Matsuura-gun, Saga',
  33.1876, 129.8932,
  'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=1200&auto=format&fit=crop&q=80',
  ARRAY['ceramics','porcelain','craft','Imari ware'],
  true,
  ARRAY['The Arita Porcelain Park has a replica of the Zwinger Palace built by a European buyer in the 1980s — bizarre and worth seeing','Visit a working kiln at Genemon Kiln — one of the few still hand-painting traditional blue-and-white designs','The Kyushu Ceramic Museum has a free collection spanning 400 years of Saga pottery'],
  'April–May (Grand Arita Fair) or year-round',
  'JR Sasebo Line from Hakata to Arita (~1.5 hr)',
  'Free (museum ¥300)',
  '2–3 hours',
  ''
),

-- ─── NAGASAKI ───────────────────────────────────────────────
(
  'hashima-island',
  'Hashima (Gunkanjima)',
  'Nagasaki', 'kyushu',
  ARRAY['history'],
  'The haunting abandoned island known as "Battleship Island" — a former undersea coal mine that once housed 5,000 people in the world''s highest population density. Now a UNESCO World Heritage site.',
  'Takashima-cho, Nagasaki 851-1315',
  32.6273, 129.7383,
  'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=1200&auto=format&fit=crop&q=80',
  ARRAY['ruins','abandoned','UNESCO','coal mine','island'],
  true,
  ARRAY['Tours depart from Nagasaki port; book 1–2 weeks ahead in peak season','You can only walk a designated path — guards stop you approaching crumbling buildings','The island was the inspiration for the villain''s lair in the James Bond film Skyfall'],
  'April–October (tours run when seas are calm)',
  'Guided boat tour from Nagasaki port (~40 min each way)',
  '¥4,000 (tour + entry fee)',
  '3.5 hours total',
  'https://www.gunkanjima-tour.jp/en/'
),
(
  'glover-garden',
  'Glover Garden',
  'Nagasaki', 'kyushu',
  ARRAY['history'],
  'An open-air hilltop museum of Western-style residences built by Meiji-era foreign merchants. Thomas Glover''s stone villa (1863) is Japan''s oldest surviving Western-style house, with sweeping harbor views.',
  '8-1 Minamiyamate, Nagasaki 850-0931',
  32.7263, 129.8716,
  'https://images.unsplash.com/photo-1573074617613-fc8ef27e6a9a?w=1200&auto=format&fit=crop&q=80',
  ARRAY['Meiji era','Western style','harbor view','Madame Butterfly'],
  false,
  ARRAY['The outdoor escalators up the hill are surprisingly useful and free to use','A bronze statue of Puccini''s Madame Butterfly stands in the garden — the opera was partly inspired by Nagasaki','Walk down through the Hollander Slope — a cobblestone street of historic foreign residences'],
  'Year-round, autumn colors in November',
  '15 min walk from Oura Tenshudo-Shita tram stop',
  '¥620 adults',
  '1.5–2 hours',
  'https://www.glover-garden.jp'
),
(
  'nagasaki-peace-park',
  'Nagasaki Peace Park',
  'Nagasaki', 'kyushu',
  ARRAY['history'],
  'Built near the atomic bomb hypocenter, this park pairs the hopeful Peace Statue (a 10-meter bronze figure) with the sobering Atomic Bomb Museum below. One of the most moving sites in Japan.',
  '9-6 Matsuyamachi, Nagasaki 852-8117',
  32.7742, 129.8666,
  'https://images.unsplash.com/photo-1513883049090-d0b7439799bf?w=1200&auto=format&fit=crop&q=80',
  ARRAY['atomic bomb','peace','memorial','UNESCO'],
  false,
  ARRAY['The Atomic Bomb Museum below the park is harrowing but essential — allow 90 minutes inside','August 9th at 11:02 AM: thousands gather for the annual memorial ceremony','The Hypocenter Park is a 5-minute walk from the main peace park — a simple black pillar marks ground zero'],
  'Year-round (quieter outside August 9)',
  'Tram to Matsuyamamachi stop, 5 min walk',
  'Park free; museum ¥200 adults',
  '2–3 hours',
  'https://www.city.nagasaki.lg.jp/peace/english/'
),
(
  'unzen-onsen',
  'Unzen Onsen & Hell Springs',
  'Nagasaki', 'kyushu',
  ARRAY['onsen','nature'],
  'A volcano-top hot spring resort surrounded by 30 active sulfur vents known as Unzen Jigoku (Hells). The town sits inside Unzen-Amakusa National Park with dramatic hiking trails above the clouds.',
  'Unzen, Minami-Shimabara, Nagasaki 854-0621',
  32.7389, 130.2039,
  'https://images.unsplash.com/photo-1576675784201-0e142b423952?w=1200&auto=format&fit=crop&q=80',
  ARRAY['onsen','sulfur','volcano','hiking','hell springs'],
  false,
  ARRAY['Walk the free Jigoku (Hells) boardwalk at dusk when steam glows orange in the last light','Climb Heisei Shinzan — a peak that rose 1994 after volcanic activity — for extraordinary views','Buy Unzen onsen tamago (hot spring eggs) cooked in the vents at the trailhead stalls'],
  'June (azalea season) or October–November (autumn)',
  'Bus from Nagasaki or Shimabara (~1.5 hrs)',
  'Free (hell springs boardwalk); onsen bath from ¥500',
  '2–4 hours or overnight',
  ''
),
(
  'nagasaki-chinatown',
  'Nagasaki Chinatown (Shinchi)',
  'Nagasaki', 'kyushu',
  ARRAY['food','history'],
  'Japan''s oldest and smallest Chinatown, established in the 1680s. Just two crossing streets packed with chanpon restaurants (Nagasaki''s signature noodle dish) and pork bun stalls.',
  '10-13 Shinchi, Nagasaki 850-0842',
  32.7460, 129.8771,
  'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=1200&auto=format&fit=crop&q=80',
  ARRAY['chanpon','Chinatown','pork buns','Nagasaki noodles'],
  false,
  ARRAY['Chanpon is the dish Nagasaki invented — thick noodles with seafood and vegetables in milky broth','Sara-udon (crispy noodles) is the drier variation — equally good','Visit during Chinese New Year (late Jan/early Feb) for lanterns and lion dancing'],
  'Year-round',
  '5 min walk from Nagasaki Station or tram to Tsuki-machi',
  'Free entry; chanpon from ¥800',
  '1 hour',
  ''
),

-- ─── KAGOSHIMA ──────────────────────────────────────────────
(
  'sakurajima',
  'Sakurajima',
  'Kagoshima', 'kyushu',
  ARRAY['nature','activity'],
  'Japan''s most active volcano — a brooding island connected to the mainland by a 1914 lava flow. It erupts hundreds of times a year, dusting Kagoshima city with ash and producing the world''s largest radishes.',
  'Sakurajima, Kagoshima 891-1394',
  31.5798, 130.6583,
  'https://images.unsplash.com/photo-1503803548695-c2a7b4a5b875?w=1200&auto=format&fit=crop&q=80',
  ARRAY['volcano','active','lava','island','Kagoshima Bay'],
  false,
  ARRAY['The Yunohira Observatory (373 m) gives the closest safe view of the summit craters','Sakurajima Lava Nagisa Park has a free foot onsen bath set in the volcanic rock by the sea','Check eruption alerts online before hiking — most trails close during high activity'],
  'Year-round (best views on clear winter days)',
  '15 min ferry from Kagoshima port (¥200, runs every 15 min)',
  'Free; observatory free',
  'Half day',
  ''
),
(
  'sengan-en-garden',
  'Sengan-en Garden & Shoko Shuseikan',
  'Kagoshima', 'kyushu',
  ARRAY['history','nature'],
  'A stunning 17th-century samurai garden set against Sakurajima volcano with Kagoshima Bay as its "borrowed scenery." Adjacent to Japan''s first Western-style industrial factory complex (now a museum).',
  '9700-1 Yoshino, Kagoshima 892-0871',
  31.6359, 130.5942,
  'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&auto=format&fit=crop&q=80',
  ARRAY['samurai garden','UNESCO','volcanic backdrop','Shimadzu clan'],
  true,
  ARRAY['The garden was designed so Sakurajima appears to be a perfectly placed artificial hill — borrowed landscape genius','Shoko Shuseikan next door is where the Shimadzu clan launched Japan''s industrial revolution in the 1850s','Try Kagoshima''s beloved karukan (white bean wagashi) at the garden''s tea house'],
  'Year-round, spring plum blossoms are spectacular',
  'City bus #1 from Kagoshima-Chuo Station (~25 min)',
  '¥1,000 adults (garden + factory museum)',
  '1.5–2 hours',
  'https://www.senganen.jp/en/'
),
(
  'ibusuki-sand-bath',
  'Ibusuki Sand Baths',
  'Kagoshima', 'kyushu',
  ARRAY['onsen','activity'],
  'The world''s only natural geothermal sand bath. Attendants bury you in volcanic black sand heated by underground hot springs to 50°C as the ocean laps a few metres away.',
  '5-25-18 Yunohama, Ibusuki, Kagoshima 891-0406',
  31.2571, 130.6305,
  'https://images.unsplash.com/photo-1499652848871-1527a310b13a?w=1200&auto=format&fit=crop&q=80',
  ARRAY['sand bath','onsen','geothermal','unique'],
  false,
  ARRAY['10–15 minutes buried is the standard — sweat pours out immediately','The facility provides cotton yukatas; wear nothing underneath for the full experience','Afterward soak in the adjacent indoor onsen baths to rinse off the black sand'],
  'Year-round',
  '特急 Ibusuki-no-Tamatebako from Kagoshima-Chuo (~50 min), then 10 min walk',
  '¥1,100 adults (sand bath only)',
  '1–1.5 hours',
  ''
),
(
  'kirishima-shrine',
  'Kirishima Jingu Shrine',
  'Kagoshima', 'kyushu',
  ARRAY['spiritual','nature'],
  'One of Kyushu''s oldest and most powerful shrines, dedicated to Ninigi-no-Mikoto who descended from heaven to begin the divine lineage of Japanese emperors. Set at 600m altitude in misty volcanic highlands.',
  '2459 Kirishima,霧島市 Kirishima, Kagoshima 899-4201',
  31.9292, 130.8643,
  'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&auto=format&fit=crop&q=80',
  ARRAY['ancient shrine','imperial lineage','highlands','volcanic'],
  false,
  ARRAY['The approach path through ancient cedar trees creates one of Kyushu''s most atmospheric shrine entries','Nearby Kirishima-Kinkowan National Park has hiking trails connecting several volcanic peaks','Combine with Kirishima Onsen for a mountain hot spring stay'],
  'November–December (autumn leaves) or spring',
  'Bus from JR Kirishima-Jingu Station (~20 min)',
  'Free',
  '1–1.5 hours',
  ''
),

-- ─── OKINAWA ────────────────────────────────────────────────
(
  'shuri-castle',
  'Shuri Castle',
  'Okinawa', 'kyushu',
  ARRAY['history','spiritual'],
  'The UNESCO-listed palace of the Ryukyu Kingdom, a Southeast Asian-influenced fortress unlike anything on the Japanese mainland. The vivid red-lacquer main hall (currently being restored) stands on a forested hill above Naha.',
  '1-2 Kinjocho, Shuri, Naha, Okinawa 903-0815',
  26.2170, 127.7188,
  'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&auto=format&fit=crop&q=80',
  ARRAY['Ryukyu','UNESCO','castle','restoration'],
  false,
  ARRAY['The outer gardens and stone walls are free and give a sense of the castle''s scale during the main hall restoration (through 2026)','The Enkakuji Temple ruins next door show Buddhist influence on the Ryukyu Kingdom','Visit at 8:30 AM opening time to be nearly alone on the approach path'],
  'March–May or October–November (avoiding typhoon season)',
  'Okinawa Monorail (Yui Rail) to Shuri Station, 15 min walk',
  '¥400 adults (outer area free)',
  '1–2 hours',
  'https://oki-park.jp/shurijo/en'
),
(
  'churaumi-aquarium',
  'Okinawa Churaumi Aquarium',
  'Okinawa', 'kyushu',
  ARRAY['nature','activity'],
  'One of the world''s largest aquariums, featuring a 7.5-million-litre main tank where whale sharks and manta rays glide past a 60 m acrylic viewing wall. Surrounded by Ocean Expo Park on Okinawa''s northwest coast.',
  '424 Ishikawa, Motobu, Kunigami-gun, Okinawa 905-0206',
  26.6939, 127.8775,
  'https://images.unsplash.com/photo-1504214208698-ea1916a2195a?w=1200&auto=format&fit=crop&q=80',
  ARRAY['whale shark','manta ray','aquarium','Ocean Expo Park'],
  false,
  ARRAY['Feeding time for whale sharks is 3 PM daily — arrive 15 min early for front-row viewing','The park also includes a dolphin lagoon and traditional Okinawan village (free with aquarium ticket)','The outdoor pools let you see sea turtles and dugongs up close'],
  'Year-round (avoid Golden Week and August for crowds)',
  'Bus from Naha bus terminal (~2 hrs) or rental car',
  '¥2,180 adults',
  '3–4 hours',
  'https://churaumi.okinawa/en/'
),
(
  'cape-manzamo',
  'Cape Manzamo',
  'Okinawa', 'kyushu',
  ARRAY['nature'],
  'A dramatic coral-limestone clifftop where the rock has been sculpted by the sea into an elephant trunk shape. One of Okinawa''s most iconic viewpoints, looking out over electric-blue water to the East China Sea.',
  'Manzamo, Onna Village, Kunigami-gun, Okinawa 904-0417',
  26.5211, 127.8401,
  'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=1200&auto=format&fit=crop&q=80',
  ARRAY['cliff','ocean view','limestone','East China Sea'],
  false,
  ARRAY['Come at sunset when the coral cliffs glow orange and the sea turns purple','A 600 m clifftop loop path takes about 20 minutes; bring sunscreen — no shade','The elephant rock is best seen from the southern lookout point, not the main platform'],
  'Year-round (avoid typhoon season July–September)',
  'Rental car or bus from Naha (~1 hr to Onna Village stop)',
  'Free (parking ¥100)',
  '30–45 min',
  ''
),
(
  'zamami-island',
  'Zamami Island',
  'Okinawa', 'kyushu',
  ARRAY['nature','activity'],
  'A tiny island in the Kerama archipelago with some of Japan''s clearest water — visibility exceeds 40 metres. Furuzamami beach is consistently ranked among Japan''s best beaches; humpback whales pass offshore in winter.',
  'Zamami, Zamami-son, Shimajiri-gun, Okinawa 901-3311',
  26.2288, 127.3014,
  'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1200&auto=format&fit=crop&q=80',
  ARRAY['snorkeling','diving','whale watching','Kerama','beach'],
  true,
  ARRAY['Rent a snorkel from the beach shop for ¥500 — the coral garden starts at wading depth','January–March: whale-watching boat tours from Zamami port (reserve ahead)','The island has almost no cars — rent a bicycle to explore the hilltop viewpoints'],
  'May–September (swimming), January–March (whales)',
  'High-speed ferry from Naha Tomari port (~50 min, ¥3,130)',
  'Ferry + beach free; snorkel rental from ¥500',
  'Full day or overnight',
  ''
),
(
  'kokusai-dori',
  'Naha Kokusai Dori',
  'Okinawa', 'kyushu',
  ARRAY['food'],
  'The "Miracle Mile" — Naha''s 1.6 km main street lined with Okinawan craft shops, sanshin music stores, shisa lion statues, and restaurants serving goya champuru and Ryukyu soba.',
  'Kokusai Dori, Naha, Okinawa',
  26.2178, 127.6859,
  'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=1200&auto=format&fit=crop&q=80',
  ARRAY['shopping','Okinawan food','craft','Naha','goya champuru'],
  false,
  ARRAY['Turn into the covered Makishi Public Market for fresh fish and the best champuru upstairs (vendors cook what you buy below)','Buy a Okinawan "Blue Seal" ice cream at one of the shops — ube (purple yam) flavor is locally beloved','The narrower Heiwa Dori side street is where locals shop — less touristy, better prices'],
  'Year-round',
  'Okinawa Monorail to Kencho-mae or Makishi Station',
  'Free entry; food from ¥700',
  '2–3 hours',
  ''
),
(
  'gyokusendo-cave',
  'Gyokusendo Cave',
  'Okinawa', 'kyushu',
  ARRAY['nature','activity'],
  'The longest limestone cave system in East Asia, stretching over 5 km. The 890 m public route passes through cathedral chambers with 30,000-year-old stalactites and an underground river.',
  '1336 Tamagusuku, Nanjo, Okinawa 901-0616',
  26.1099, 127.7474,
  'https://images.unsplash.com/photo-1499652848871-1527a310b13a?w=1200&auto=format&fit=crop&q=80',
  ARRAY['cave','stalactites','limestone','underground'],
  false,
  ARRAY['900,000 stalactites in just the public section — look for the 30,000-year "King" stalactite','The adjacent Okinawa World park includes a traditional Ryukyu village and habu snake show','Temperature inside is 21°C year-round — bring a layer in summer'],
  'Year-round',
  'Bus #54 from Naha Bus Terminal (~1 hr) or rental car',
  '¥1,650 adults (cave + village park)',
  '2–3 hours',
  'https://www.gyokusendo.co.jp/okinawaworld/en/'
);
