INSERT INTO spots (
  id, name, prefecture, region, categories, description,
  address, lat, lng, image_url, tags, is_premium,
  highlights, best_season, access, admission, duration,
  opening_hours, tips
) VALUES
(
  'chikurin-ji-temple',
  'Chikurin-ji Temple',
  'Kochi',
  'shikoku',
  ARRAY['spiritual', 'history'],
  'One of Kochi''s most famous temples and the 31st stop on the Shikoku 88 Temple Pilgrimage, Chikurin-ji is widely visited for its peaceful mossy grounds, five-storied pagoda, and historic garden. A mainstream spiritual landmark for travelers seeking major cultural heritage close to the city.',
  '3577 Godaisan, Kochi, Kochi 781-8125, Japan',
  33.5466, 133.5775,
  'https://images.unsplash.com/photo-1493784012405-a8a97ec1de9f?w=800&auto=format&fit=crop&q=80',
  ARRAY['temple', 'pilgrimage', 'moss', 'pagoda', 'garden', 'Kochi', 'spiritual', 'historic'],
  false,
  ARRAY['Five-storied pagoda', 'Mossy temple grounds', 'Historic garden', 'Pilgrimage site'],
  'Spring and autumn, especially for fresh greenery and fall foliage',
  'About 20 minutes by car from Kochi IC. By public transport: take the MY-YU Bus from Kochi Station and get off at Chikurinji Temple.',
  'Free for temple grounds; ¥800 (adults) for garden, treasure hall, and study hall access',
  '1.5–2 hours',
  '9:00–17:00 (varies seasonally)',
  'The temple is especially beautiful in autumn foliage season. Wear comfortable shoes for walking the grounds. The garden and treasure hall offer excellent views of the pagoda.'
),
(
  'makino-botanical-garden',
  'Kochi Prefectural Makino Botanical Garden',
  'Kochi',
  'shikoku',
  ARRAY['nature'],
  'Kochi''s flagship botanical garden combines panoramic Mt. Godai scenery with extensive seasonal plant displays and a modern greenhouse. Renowned for its connection to botanist Tomitaro Makino, it is one of Kochi''s most visited cultural-nature attractions with strong national recognition.',
  '4200-6 Godaisan, Kochi, Kochi 781-8125, Japan',
  33.5467, 133.5778,
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&auto=format&fit=crop&q=80',
  ARRAY['botanical-garden', 'plants', 'flowers', 'Mt. Godai', 'seasonal', 'nature', 'Makino', 'Kochi'],
  false,
  ARRAY['Seasonal flower displays', 'Mt. Godai panoramic views', 'Modern greenhouse facility', 'Tomitaro Makino heritage'],
  'Year-round; spring to early summer and autumn are especially rewarding',
  'About 20 minutes by car from central Kochi. By public transport: about 30 minutes from Kochi Station by MY-YU Bus.',
  '¥850 (adults); discount for seniors and students',
  '2–3 hours',
  '9:00–17:00 (closed on Mondays unless Monday is a national holiday)',
  'The garden features different seasonal highlights throughout the year. Spring offers cherry blossoms and fresh greenery; autumn brings vibrant foliage. Allow extra time to explore the greenhouse.'
),
(
  'noichi-zoo',
  'Noichi Zoological Park of Kochi Prefecture',
  'Kochi',
  'shikoku',
  ARRAY['activity'],
  'One of Kochi''s biggest family attractions, Noichi Zoo is known for spacious habitat-style exhibits where animals are shown in naturalistic environments. An established, high-appeal half-day destination for families and travelers around Kochi City.',
  '738 Otani, Noichi-cho, Konan, Kochi 781-5233, Japan',
  33.5711, 133.7058,
  'https://images.unsplash.com/photo-1551316679-9c6ae9dec224?w=800&auto=format&fit=crop&q=80',
  ARRAY['zoo', 'animals', 'wildlife', 'family-friendly', 'habitat', 'Kochi', 'activity', 'education'],
  false,
  ARRAY['Spacious habitat exhibits', 'Diverse animal collection', 'Family-friendly facilities', 'Natural-setting enclosures'],
  'Spring and autumn for comfortable walking weather',
  'About 20 minutes by car from Nankoku IC. By public transport: about 20 minutes on foot from Noichi Station on the Gomen-Nahari Line.',
  '¥470 (adults); free for high school students and younger',
  '2–3 hours',
  '9:00–17:00 (closed Mondays unless a national holiday)',
  'The zoo features space-efficient habitat designs that let visitors observe animals in near-natural settings. Bring comfortable walking shoes and sun protection. Lunch facilities are available on-site.'
),
(
  'anpanman-museum',
  'Kami City Yanase Takashi Memorial Hall Anpanman Museum',
  'Kochi',
  'shikoku',
  ARRAY['activity'],
  'Dedicated to Kochi-born creator Takashi Yanase, this museum is one of the prefecture''s most recognizable family destinations and a pilgrimage stop for Anpanman fans nationwide. A firmly established sightseeing draw in eastern Kochi.',
  '1224-2 Birafu, Kahoku-cho, Kami, Kochi 781-4212, Japan',
  33.6477, 133.7838,
  'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800&auto=format&fit=crop&q=80',
  ARRAY['Anpanman', 'museum', 'Yanase', 'Kochi', 'character', 'family-friendly', 'animation', 'creator'],
  false,
  ARRAY['Anpanman character exhibits', 'Creator Takashi Yanase gallery', 'Interactive displays', 'Gift shop and café'],
  'Year-round',
  'About 35 minutes by car from Nankoku IC. By public transport: JR Dosan Line to Tosa-Yamada Station, then transfer to the JR Bus Odochi Line for about 25 minutes to Anpanman Museum Mae stop.',
  '¥1,200 (adults) for the combined memorial hall ticket',
  '1.5–2.5 hours',
  '9:30–17:00 (closed Tuesdays)',
  'Anpanman fans of all ages will find dedicated exhibits. The museum includes interactive displays and a café. Merchandise and character goods are available in the gift shop.'
),
(
  'sakamoto-ryoma-museum',
  'Sakamoto Ryoma Memorial Museum',
  'Kochi',
  'shikoku',
  ARRAY['history'],
  'One of Kochi''s signature museums, this hilltop memorial museum above Katsurahama presents the life and legacy of Sakamoto Ryoma, one of Japan''s most beloved historical figures. A standard stop for first-time visitors seeking a major Kochi attraction tied to the prefecture''s most famous local hero.',
  '830 Urado-shiroyama, Kochi, Kochi 781-0262, Japan',
  33.4964, 133.5718,
  'https://images.unsplash.com/photo-1578925078519-cfb6c192c40b?w=800&auto=format&fit=crop&q=80',
  ARRAY['museum', 'history', 'Sakamoto Ryoma', 'Kochi', 'heritage', 'Katsurahama', 'biography', 'historical'],
  false,
  ARRAY['Sakamoto Ryoma biography', 'Hilltop museum location', 'Historical artifacts and documents', 'Katsurahama sea views'],
  'Year-round; spring and autumn are pleasant for combining with the Katsurahama area',
  'About 2 minutes on foot from Ryoma Kinenkan Mae bus stop on Tosaden Kotsu Bus or MY-YU Bus. About 30 minutes by car from Kochi IC.',
  '¥500 (adults, regular periods); ¥900 (adults, during planned exhibitions)',
  '1.5–2 hours',
  '9:00–17:00 (closed Mondays)',
  'The museum provides comprehensive coverage of Ryoma''s life from childhood through his role in Japan''s modernization. Combine with a visit to nearby Katsurahama Beach for a fuller experience of the area.'
);
