INSERT INTO spots (
  id, name, prefecture, region, categories, description,
  address, lat, lng, image_url, tags, is_premium,
  highlights, best_season, access, admission, duration,
  opening_hours, tips
) VALUES
(
  'tobe-zoo',
  'Tobe Zoological Park',
  'Ehime',
  'shikoku',
  ARRAY['activity'],
  'Western Japan''s largest zoo with over 1,000 animals from around the world. Known for polar bears, elephants, and immersive habitat-style exhibits that make for an engaging half-day outing from Matsuyama.',
  '240 Kamiharamachi, Tobe-cho, Iyo-gun, Ehime 791-2191, Japan',
  33.7643, 132.7919,
  'https://images.unsplash.com/photo-1551316679-9c6ae9dec224?w=800&auto=format&fit=crop&q=80',
  ARRAY['zoo', 'wildlife', 'family-friendly', 'Matsuyama', 'animals', 'education', 'interactive'],
  false,
  ARRAY['Polar bear enclosure', 'Elephant habitat', 'Interactive feeding zones', 'Year-round operation'],
  'Year-round; spring and autumn are most comfortable for walking',
  'About 10 minutes by car from Matsuyama IC. By public transport: about 36 minutes by Iyotetsu bus from Matsuyama City Station to Tobe Dobutsuen-mae, then a short walk.',
  '¥600 (adults), ¥300 (children), preschool children free',
  '2–3 hours',
  '9:00–17:00 (closed Mondays); extended hours during holidays',
  'Wear comfortable shoes for walking the expansive grounds. Animal feeding times vary by species; check the official schedule. Peak season can be crowded, especially weekends.'
),
(
  'minetopia-besshi',
  'Minetopia Besshi',
  'Ehime',
  'shikoku',
  ARRAY['activity', 'history'],
  'A major industrial-heritage park celebrating the historic Besshi Copper Mine that powered Japan''s modernization. Visitors can ride a mine train deep underground, explore a sightseeing tunnel, and learn about mining history.',
  '707-3 Tatsukawacho, Niihama, Ehime 792-0846, Japan',
  33.9015, 133.3095,
  'https://images.unsplash.com/photo-1518567858389-a6c61d881565?w=800&auto=format&fit=crop&q=80',
  ARRAY['mining', 'industrial-heritage', 'history', 'underground', 'train-ride', 'unique-experience', 'Niihama'],
  false,
  ARRAY['Historic mine train', 'Underground sightseeing tunnel', 'Mining museum', 'Visitor facilities'],
  'Spring to autumn; outdoor scenery is especially pleasant in fresh greenery and autumn foliage',
  'About 15 minutes by car from Niihama IC. By public transport: take the Setouchi Bus Yamane/Minetopia Line toward Minetopia Besshi.',
  'Free entry to roadside station; mine sightseeing from ¥1,300 (varies by tour type)',
  '2–3 hours',
  '8:30–17:00 (closed Wednesdays; open during holiday periods)',
  'The mine tour involves descent into cool underground passages; bring a light jacket. Tours have weight and health restrictions; check in advance. Early arrival recommended during peak season.'
),
(
  'yawatahama-minatto',
  'Yawatahama Minatto',
  'Ehime',
  'shikoku',
  ARRAY['food'],
  'A bustling waterfront michi-no-eki (roadside station) that doubles as a seafood market and local-produce hub. Sample fresh catch from Yawatahama harbor, local citrus, and casual dining options in a lively harbor-side atmosphere.',
  '1581-23 Okishinden, Yawatahama, Ehime 796-0087, Japan',
  33.4582, 132.4183,
  'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&auto=format&fit=crop&q=80',
  ARRAY['food', 'seafood', 'local-produce', 'market', 'harbor', 'souvenir', 'Yawatahama'],
  false,
  ARRAY['Fresh seafood market', 'Local produce selection', 'Harbor-side dining', 'Regional specialties'],
  'Year-round; autumn to winter is best for local citrus and cold-season seafood',
  'About 5 minutes by car from JR Yawatahama Station. About 25 minutes from Ozu IC. About 3 minutes on foot from Yawatahama Ferry Terminal.',
  'Free entry; food prices vary by vendor',
  '1–2 hours',
  '9:00–18:00 (varies by vendor and season)',
  'Arrive early for the freshest seafood selection. Many vendors use cash only. The market is liveliest in early morning. Parking can fill during peak season, especially weekends.'
),
(
  'uwajima-kisaiya-hiroba',
  'Uwajima Kisaiya Hiroba',
  'Ehime',
  'shikoku',
  ARRAY['food'],
  'A celebrated waterfront michi-no-eki near Uwajima Port that showcases southern Ehime''s culinary identity. Try local specialties like taimeshi (sea bream rice) and jakoten (fish cake), plus regional souvenirs and seasonal produce.',
  '1-318-16 Bentencho, Uwajima, Ehime 798-0006, Japan',
  33.2223, 132.5584,
  'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&auto=format&fit=crop&q=80',
  ARRAY['food', 'local-cuisine', 'taimeshi', 'market', 'souvenirs', 'harbor', 'Uwajima'],
  false,
  ARRAY['Uwajima taimeshi specialty', 'Fresh jakoten (fish cake)', 'Local produce market', 'Harbor-side setting'],
  'Year-round; cooler months are ideal for seafood-focused meals',
  'Right off the Uwajima-Asahi IC area by car. About 12 minutes on foot from JR Uwajima Station.',
  'Free entry; meal and product prices vary',
  '1–2 hours',
  '9:00–18:00 (varies by vendor)',
  'Taimeshi bowls sell out quickly during lunch hours; arrive early or reserve ahead. The signature jakoten is a must-try local product. Parking available; note that peak season weekends attract crowds.'
),
(
  'nibukawa-seseragi-koryukan',
  'Nibukawa Seseragi Koryukan',
  'Ehime',
  'shikoku',
  ARRAY['onsen'],
  'A serene day-use bathhouse at the gateway to the historic Nibukawa Onsen valley. Known for alkaline beauty waters and surrounded by peaceful valley scenery, it offers a quieter onsen experience away from the crowded Dogo Onsen.',
  '218-1 Nibukawako, Tamagawa-cho, Imabari, Ehime 794-0121, Japan',
  33.9847, 132.9404,
  'https://images.unsplash.com/photo-1540932503986-1e3e8ac6efd2?w=800&auto=format&fit=crop&q=80',
  ARRAY['onsen', 'hot-spring', 'day-use', 'valley', 'beauty-bath', 'Nibukawa', 'relaxation'],
  false,
  ARRAY['Alkaline beauty waters', 'Valley scenery', 'Day-use facility', 'Quiet atmosphere'],
  'Autumn and winter; valley foliage and cool-weather bathing enhance the experience',
  'About 30 minutes by bus from JR Imabari Station; take the bus via Nibukawa Onsen to Seseragi Koryukan. About 20 minutes by car from Imabari IC.',
  '¥560 (adults), ¥280 (children)',
  '1.5–2 hours',
  '10:00–20:00 (closed second and fourth Thursdays)',
  'The alkaline waters are gentle on skin; stay hydrated. The facility is popular with locals; weekday mornings are quieter. Winter visits offer the best valley scenery and comfort.'
);
