INSERT INTO spots (
  id, name, prefecture, region, categories, description,
  address, lat, lng, image_url, tags, is_premium,
  highlights, best_season, access, admission, duration,
  opening_hours, tips
) VALUES
(
  'shikoku-aquarium',
  'Shikoku Aquarium',
  'Kagawa',
  'shikoku',
  ARRAY['activity'],
  'One of Kagawa''s highest-profile modern attractions, this major aquarium showcases roughly 400 species connected to Shikoku''s seas and rivers. Its sunset-facing dolphin pool and easy access from Utazu make it a mainstream stop for first-time visitors.',
  '4 Hama 1-bancho, Utazu-cho, Ayauta-gun, Kagawa 769-0201, Japan',
  34.3128, 133.8081,
  'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&auto=format&fit=crop&q=80',
  ARRAY['aquarium', 'marine-life', 'dolphins', 'Kagawa', 'Utazu', 'family-friendly', 'modern'],
  false,
  ARRAY['Roughly 400 marine and river species', 'Sunset-facing dolphin pool', 'Major modern facility', 'Year-round access from Utazu'],
  'Year-round; late afternoon is especially rewarding for the sunset deck',
  'About 12 minutes on foot from JR Utazu Station. About 10 minutes by car from Sakaide IC. About 40 minutes by car from Takamatsu Airport.',
  '¥2,600 (adults)',
  '2–3 hours',
  '9:00–17:00 (last entry 16:00)',
  'The sunset deck over the dolphin pool offers the best views in late afternoon. Plan to arrive early during peak season weekends and holidays.'
),
(
  'new-reoma-world',
  'NEW Reoma World',
  'Kagawa',
  'shikoku',
  ARRAY['activity'],
  'One of Shikoku''s largest theme parks, NEW Reoma World is a long-established leisure destination known for rides, seasonal flower displays, parades, and large-scale illuminations. It has stronger mainstream family appeal than smaller local attractions in inland Kagawa.',
  '40-1 Kurikuma Nishi, Ayautacho, Marugame, Kagawa 761-2405, Japan',
  34.2120, 133.8784,
  'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800&auto=format&fit=crop&q=80',
  ARRAY['theme-park', 'amusement-park', 'rides', 'Kagawa', 'Marugame', 'family-friendly', 'seasonal-events'],
  false,
  ARRAY['Amusement park rides and attractions', 'Seasonal flower displays and events', 'Large-scale illuminations', 'Year-round family destination'],
  'Spring and autumn; winter is also popular for illuminations',
  'About 25 minutes by car from Sakaide IC or Zentsuji IC. About 15 minutes from Fuchu Lake Smart IC. Free shuttle and local bus from JR Sakaide, JR Utazu, JR Kotohira stations, and Kotoden Okada Station.',
  'From ¥2,000 (adults) for park admission',
  '4–6 hours',
  '9:00–18:00 (hours vary seasonally and by attraction)',
  'Peak season weekends and Golden Week periods draw large crowds. Check the official website for seasonal event schedules and special illumination dates.'
),
(
  'sanuki-manno-park',
  'Sanuki Manno Park',
  'Kagawa',
  'shikoku',
  ARRAY['nature'],
  'Shikoku''s only national government park is one of Kagawa''s best-known flower and outdoor recreation destinations, with expansive grounds, cycling, playgrounds, and seasonal events. It is especially established as a repeat-visit spot for spring blooms, autumn kochia, and winter illumination.',
  '4243-12 Yoshino, Manno-cho, Nakatado-gun, Kagawa 766-0023, Japan',
  34.1669, 133.8798,
  'https://images.unsplash.com/photo-1469022563149-aa64dbd37dae?w=800&auto=format&fit=crop&q=80',
  ARRAY['park', 'nature', 'flowers', 'cycling', 'Kagawa', 'national-park', 'seasonal-events'],
  false,
  ARRAY['Expansive grounds and cycling paths', 'Spring cherry blossoms and flower displays', 'Autumn red kochia (burning bush)', 'Winter illumination events'],
  'Spring and autumn; winter is also popular during the illumination period',
  'About 35 minutes by car from Sakaide IC. About 25 minutes from Zentsuji IC. About 15 minutes by taxi from JR Kotohira Station, Kotoden Kotohira Station, or Kotoden Okada Station. Bus to Manno-Koen-Guchi plus a walk.',
  '¥450 (ages 15 and over)',
  '2.5–4 hours',
  '9:30–17:00 (closes earlier in winter; illumination runs until 20:00 during special periods)',
  'Spring brings vibrant cherry blossoms and tulips across the expansive grounds. Autumn features brilliant red kochia (burning bush). Bicycle rentals are available for exploring the park''s extensive paths.'
),
(
  'shikoku-mura-museum',
  'Shikoku Mura Museum',
  'Kagawa',
  'shikoku',
  ARRAY['history'],
  'This open-air museum at the foot of Yashima gathers traditional buildings from across Shikoku, making it one of Takamatsu area''s most established cultural sightseeing stops outside the better-known plateau itself. The grounds, relocated folk architecture, and Tadao Ando-designed gallery give it broad appeal.',
  '91 Yashima Nakamachi, Takamatsu, Kagawa 761-0112, Japan',
  34.3456, 134.1089,
  'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80',
  ARRAY['museum', 'open-air-museum', 'traditional-buildings', 'Kagawa', 'Takamatsu', 'cultural', 'architecture'],
  false,
  ARRAY['Traditional buildings from across Shikoku', 'Open-air museum grounds', 'Tadao Ando-designed modern gallery', 'Cultural heritage preservation'],
  'Spring and autumn, when walking the outdoor museum grounds is most comfortable',
  'About 5 minutes on foot from Kotoden Yashima Station. About 10 minutes on foot from JR Yashima Station. About 15 minutes by car from Takamatsu-chuo IC.',
  '¥1,600 (adults)',
  '2–3 hours',
  '9:00–17:00 (closed Mondays)',
  'The museum offers a comprehensive collection of folk architecture spanning Shikoku''s regions. The Tadao Ando-designed contemporary gallery contrasts beautifully with the traditional buildings. Wear comfortable shoes for walking the extensive grounds.'
),
(
  'zenigata-sand-coin',
  'Zenigata Sand Coin',
  'Kagawa',
  'shikoku',
  ARRAY['history'],
  'Kannonji''s giant Edo-period coin-shaped sand drawing is one of western Kagawa''s signature landmarks and a classic luck-themed sightseeing stop. Its scale, long-running local upkeep, and regular night illumination make it one of the prefecture''s most recognizable non-island photo spots.',
  '14 Ariake-cho, Kanonji, Kagawa 768-0062, Japan',
  34.1341, 133.6423,
  'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop&q=80',
  ARRAY['historic-site', 'sand-art', 'Edo-period', 'Kagawa', 'Kanonji', 'landmark', 'photography'],
  false,
  ARRAY['Giant coin-shaped sand drawing', 'Edo-period heritage', 'Night illumination displays', 'Symbol of good fortune'],
  'Year-round; spring and autumn are best for walking Kotohiki Park, and dusk is ideal for illumination views',
  'About 12 minutes by car from Onohara IC. About 15 minutes from Sanuki Toyonaka IC. About 5 minutes by taxi from JR Kanonji Station. Local shared bus to Kotohiki Park.',
  'Free',
  '45–90 minutes',
  'Open year-round (best viewed at sunset or during evening illumination)',
  'The sand coin is best appreciated from the elevated viewing platform. Night illumination runs year-round and creates a striking photo opportunity. The adjacent Kotohiki Park offers walking paths and seasonal flower displays.'
);
