import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: join(__dirname, '../.env.local') });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
);

const PH = 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&auto=format&fit=crop&q=80';

const spots = [

  // ── TOKYO (10) ────────────────────────────────────────────────────────────
  {
    id: 'yanaka-ginza',
    name: 'Yanaka Ginza',
    prefecture: 'Tokyo',
    region: 'kanto',
    categories: ['history', 'food'],
    description: 'Tokyo\'s best-preserved shitamachi (old town) neighbourhood — a gentle slope of 70 independent shops, tofu makers, and cat-filled alleyways that escaped wartime bombing and urban redevelopment. Yanaka Cemetery is one of Tokyo\'s most atmospheric cherry blossom spots, and the lanes connecting it to the shopping street are lined with century-old wooden machiya.',
    address: 'Yanaka, Taito-ku, Tokyo',
    lat: 35.7265, lng: 139.7700,
    image_url: PH, tags: ['shitamachi', 'old town', 'cats', 'shopping street'], is_premium: false,
    highlights: [
      'Tokyo\'s most intact Edo-era residential streetscape — wooden machiya, handmade tofu, and cat shrines',
      'Yanaka Cemetery has over 7,000 graves including Tokugawa Yoshinobu — and 200 cherry trees',
      'The area survived WWII bombing and the 1923 earthquake — rare genuine oldness in Tokyo',
    ],
    best_season: 'Year-round (cherry blossom March–April)', access: '5 min walk from Nippori Station (JR Yamanote Line)', admission: 'Free', duration: '2–3 hours',
  },
  {
    id: 'hamarikyu-gardens',
    name: 'Hamarikyu Gardens',
    prefecture: 'Tokyo',
    region: 'kanto',
    categories: ['nature', 'history'],
    description: 'A 300-year-old tidal garden in the middle of Tokyo\'s skyscraper district — the only garden in the city with saltwater ponds replenished by Tokyo Bay. Originally the shogunate\'s private duck-hunting grounds, it now offers extraordinary views of Shiodome towers reflected in ancient lotus ponds, with a teahouse on an island reached by wooden bridges.',
    address: '1-1 Hamarikyu Teien, Chuo-ku, Tokyo',
    lat: 35.6601, lng: 139.7641,
    image_url: PH, tags: ['tidal garden', 'shogunate', 'teahouse', 'skyscraper contrast'], is_premium: false,
    highlights: [
      'Saltwater ponds filled twice daily by Tokyo Bay tides — the only tidal garden in the city',
      'The island teahouse serves matcha with views of both ancient gardens and 40-storey towers simultaneously',
      'Ferry boats from here go directly to Asakusa — the best way to arrive in old Tokyo',
    ],
    best_season: 'Year-round (autumn foliage November, plum February)', access: '5 min walk from Shiodome Station (Yurikamome)', admission: '¥300', duration: '1–1.5 hours',
  },
  {
    id: 'nezu-shrine',
    name: 'Nezu Shrine',
    prefecture: 'Tokyo',
    region: 'kanto',
    categories: ['spiritual', 'nature'],
    description: 'Tokyo\'s alternative to Kyoto\'s Fushimi Inari — a serene 1,900-year-old shrine with a tunnel of 200 vermilion torii gates winding through a wooded hillside in Bunkyo. In April, the azalea garden (3,000 plants across 100 varieties) turns the shrine grounds into a labyrinth of pink and red. Usually crowd-free on weekdays.',
    address: '1-28-9 Nezu, Bunkyo-ku, Tokyo',
    lat: 35.7207, lng: 139.7624,
    image_url: PH, tags: ['torii gates', 'azalea', 'ancient shrine', 'tunnel'], is_premium: false,
    highlights: [
      'A 200-torii gate tunnel through a forested hillside — far less crowded than Fushimi Inari',
      '3,000 azalea plants bloom mid-April to early May — one of Tokyo\'s finest flower gardens',
      'Founded before Tokyo existed — one of the oldest continuously operating shrines in the Kanto region',
    ],
    best_season: 'Mid-April (azaleas), Year-round', access: '5 min walk from Nezu Station (Chiyoda Line)', admission: 'Free (azalea garden ¥500)', duration: '45–60 min',
  },
  {
    id: 'shimokitazawa',
    name: 'Shimokitazawa',
    prefecture: 'Tokyo',
    region: 'kanto',
    categories: ['activity', 'food'],
    description: 'Tokyo\'s indie culture neighbourhood — a maze of narrow lanes packed with vintage clothing shops, vinyl record stores, live music venues, and tiny theatre spaces. The area resisted a planned expressway through its heart and preserved its human-scale streetscape. Shimokitazawa is where Tokyo\'s creative class lives, plays, and performs.',
    address: 'Shimokitazawa, Setagaya-ku, Tokyo',
    lat: 35.6615, lng: 139.6682,
    image_url: PH, tags: ['vintage', 'live music', 'theatre', 'independent shops'], is_premium: false,
    highlights: [
      'Japan\'s densest concentration of independent theatres — over 20 stages in a 10-minute walk',
      'Shimokitazawa Record Fair (twice yearly) fills every venue with rare vinyl dealers',
      'The town fought and won a 30-year battle against an expressway — its lanes were preserved intact',
    ],
    best_season: 'Year-round', access: 'Shimokitazawa Station (Odakyu/Keio Inokashira Lines, 10 min from Shibuya)', admission: 'Free', duration: '2–4 hours',
  },
  {
    id: 'koenji-awa-odori',
    name: 'Koenji',
    prefecture: 'Tokyo',
    region: 'kanto',
    categories: ['activity', 'food'],
    description: 'An old shopping arcade town that gentrified into Tokyo\'s most eclectic neighbourhood — vintage shops, curry restaurants, and tiny jazz bars coexist with a 100-year-old covered shotengai. The Awa-Odori festival in late August fills the streets with over 10,000 dancers and a million spectators — the largest summer street festival in Tokyo.',
    address: 'Koenji, Suginami-ku, Tokyo',
    lat: 35.7056, lng: 139.6493,
    image_url: PH, tags: ['vintage', 'awa-odori', 'shotengai', 'jazz'], is_premium: false,
    highlights: [
      'Koenji Awa-Odori festival (late August) — 10,000 dancers, 1 million spectators, completely free',
      'Japan\'s highest concentration of vintage clothing shops per square metre',
      'The Heiwa-Fureai shopping arcade has barely changed since the 1960s',
    ],
    best_season: 'Late August (festival), Year-round', access: 'Koenji Station (JR Chuo Line, 10 min from Shinjuku)', admission: 'Free', duration: '2–3 hours',
  },
  {
    id: 'yoyogi-park',
    name: 'Yoyogi Park & Meiji Jingu',
    prefecture: 'Tokyo',
    region: 'kanto',
    categories: ['nature', 'spiritual'],
    description: 'Tokyo\'s most beloved park combines with the forested shrine of Emperor Meiji — a 700,000-square-metre urban forest created by planting 120,000 trees from across Japan in 1920. The combination of cherry-blossom picnics, festival markets, and the 100-year-old cedar avenue to the shrine gate makes this Tokyo\'s finest outdoor half-day.',
    address: '2-1 Yoyogi Kamizonocho, Shibuya-ku, Tokyo',
    lat: 35.6717, lng: 139.6944,
    image_url: PH, tags: ['forest shrine', 'cherry blossoms', 'meiji', 'picnic'], is_premium: false,
    highlights: [
      'Meiji Jingu Forest — 120,000 trees planted in 1920, now a self-sustaining old-growth urban forest',
      'The torii gate is Japan\'s largest wooden torii — 12 metres tall, made of 1,500-year-old cypress',
      'Cherry blossom season fills the park with 200 trees and Tokyo\'s most festive hanami crowds',
    ],
    best_season: 'March–April (cherry blossoms), Year-round', access: 'Harajuku Station (JR Yamanote Line)', admission: 'Free', duration: '1.5–2 hours',
  },
  {
    id: 'tsukiji-outer-market',
    name: 'Tsukiji Outer Market',
    prefecture: 'Tokyo',
    region: 'kanto',
    categories: ['food'],
    description: 'The working wholesale market may have moved to Toyosu, but Tsukiji\'s outer market — 400 shops and restaurants in a covered arcade — remains the finest place in the world to eat fresh seafood at breakfast. The tamagoyaki (rolled omelette) shops alone are worth the trip, and the uni (sea urchin) and tuna sashimi are served within hours of landing.',
    address: '4-16-2 Tsukiji, Chuo-ku, Tokyo',
    lat: 35.6655, lng: 139.7706,
    image_url: PH, tags: ['seafood', 'tuna', 'breakfast', 'market'], is_premium: false,
    highlights: [
      '400 specialist shops covering every marine ingredient imaginable — dashi kombu, katsuobushi, wasabi root',
      'The best tamagoyaki (rolled omelette) in Tokyo — try Tsukiji Tamagoyaki\'s freshly made sticks',
      'Arrive before 8am for the best sashimi breakfast — shops begin running out of prime cuts by 10am',
    ],
    best_season: 'Year-round (closed Sundays and market holidays)', access: '5 min walk from Tsukiji Station (Hibiya Line)', admission: 'Free', duration: '1.5–2 hours',
  },
  {
    id: 'tokyo-tower-shiba-park',
    name: 'Shiba Park & Zojo-ji Temple',
    prefecture: 'Tokyo',
    region: 'kanto',
    categories: ['spiritual', 'history'],
    description: 'The Tokugawa shogunate\'s family temple sits directly beneath Tokyo Tower — a juxtaposition of steel modernity and 400-year-old Edo grandeur. Zojo-ji was the mortuary temple for six Tokugawa shoguns, and their mausoleum gates (Sankeiden) are some of the finest surviving Edo-period architecture in Tokyo.',
    address: '4-7-35 Shiba-koen, Minato-ku, Tokyo',
    lat: 35.6561, lng: 139.7490,
    image_url: PH, tags: ['tokugawa temple', 'tokyo tower', 'mausoleum', 'zojoji'], is_premium: false,
    highlights: [
      'Six Tokugawa shoguns are entombed here — their mausoleum gates are National Important Cultural Properties',
      'The Tokyo Tower view from the main gate is one of the city\'s iconic compositions',
      'Over 1,200 Jizo statues in the temple garden — each dressed by a family who lost a child',
    ],
    best_season: 'Year-round (cherry blossoms in the park in April)', access: 'Shibakoen Station (Mita Line, 2 min)', admission: 'Free', duration: '45–60 min',
  },
  {
    id: 'kagurazaka',
    name: 'Kagurazaka',
    prefecture: 'Tokyo',
    region: 'kanto',
    categories: ['history', 'food'],
    description: 'Tokyo\'s most French neighbourhood with the most Japanese soul — a hillside former geisha district where ryotei (high-end kaiseki restaurants) hide behind unmarked wooden gates in cobblestone alleys. French bistros, Italian delis, and a French lycée coexist with ancient shrines and the last functioning geisha houses in central Tokyo.',
    address: 'Kagurazaka, Shinjuku-ku, Tokyo',
    lat: 35.7007, lng: 139.7406,
    image_url: PH, tags: ['geisha district', 'french quarter', 'cobblestone', 'ryotei'], is_premium: false,
    highlights: [
      'Hyogo-yokocho — a cobblestone flagstone alley lined with former geisha ochaya, untouched since the Taisho era',
      'French community has been here since the 1900s — French lycée, Alliance française, and bakeries on every corner',
      'Monthly Ura-Kagurazaka market on Sundays fills the back alleys with natural wine and local cheese',
    ],
    best_season: 'Year-round', access: 'Kagurazaka Station (Tozai Line, 15 min from Otemachi)', admission: 'Free', duration: '2–3 hours',
  },
  {
    id: 'todoroki-valley',
    name: 'Todoroki Valley',
    prefecture: 'Tokyo',
    region: 'kanto',
    categories: ['nature', 'spiritual'],
    description: 'Tokyo\'s only valley — a forested ravine running 1km through the middle of suburban Setagaya Ward, completely invisible from the surrounding streets until you descend the stone steps. A stream runs beneath a canopy of zelkova trees, passing the Fudo-do temple with its waterfall used for ascetic purification. Entirely free and usually quiet.',
    address: 'Todoroki, Setagaya-ku, Tokyo',
    lat: 35.6036, lng: 139.6566,
    image_url: PH, tags: ['valley', 'urban nature', 'hidden', 'stream'], is_premium: false,
    highlights: [
      'Tokyo\'s only valley walk — 1km of forested ravine completely hidden below the suburban street level',
      'The Fudo-do waterfall temple at the valley floor is used for mizugori (cold-water purification) practice',
      'Free, almost always quiet, and reachable in 20 minutes from Shibuya — Tokyo\'s best-kept secret',
    ],
    best_season: 'Year-round (summer is cool, autumn has foliage)', access: 'Todoroki Station (Tokyu Oimachi Line, 20 min from Shibuya)', admission: 'Free', duration: '1–1.5 hours',
  },

  // ── KANAGAWA (10) ─────────────────────────────────────────────────────────
  {
    id: 'kamakura-great-buddha',
    name: 'Kamakura — Great Buddha & Hase-dera',
    prefecture: 'Kanagawa',
    region: 'kanto',
    categories: ['spiritual', 'history'],
    description: 'Japan\'s second-largest bronze Buddha (13.35m) has sat in the open air since its covering hall collapsed in a 1498 tsunami — and the sea salt and centuries have given it extraordinary patina. Nearby Hase-dera temple has 10,000 hydrangeas on the hillside and a sea-view cave of Kannon statues that defines Kamakura.',
    address: '4-2-28 Hase, Kamakura City, Kanagawa',
    lat: 35.3167, lng: 139.5355,
    image_url: PH, tags: ['great buddha', 'kamakura', 'hydrangea', 'bronze'], is_premium: false,
    highlights: [
      'The Great Buddha has sat outdoors since 1498 when the tsunami washed away his hall — still serene',
      'Hase-dera\'s 10,000 hydrangeas bloom June–July along the hillside path overlooking the Pacific',
      'You can enter the Buddha\'s hollow body for ¥50 — see the rivets and ventilation windows inside',
    ],
    best_season: 'June (hydrangeas), March–April (cherry), Year-round', access: 'Hase Station on Enoden Line (40 min from Kamakura)', admission: '¥200 (Buddha)', duration: 'Half day',
  },
  {
    id: 'enoshima-island',
    name: 'Enoshima Island',
    prefecture: 'Kanagawa',
    region: 'kanto',
    categories: ['nature', 'spiritual'],
    description: 'A tidal island connected to the mainland by a 600-metre bridge, sacred to Benzaiten (the goddess of everything that flows — music, water, time). The island rises 60 metres with a pagoda, sea caves, and a lighthouse park offering Mt Fuji views on clear days. The approach street (Benzaiten Nakamise) is lined with shirasu (whitebait) restaurants.',
    address: 'Enoshima, Fujisawa City, Kanagawa',
    lat: 35.2996, lng: 139.4839,
    image_url: PH, tags: ['tidal island', 'benzaiten', 'mt fuji view', 'sea caves'], is_premium: false,
    highlights: [
      'Mt Fuji visible from the lighthouse observation deck on clear winter mornings',
      'The sea caves (Iwaya) at the base of the island have 1,500-year-old carvings and candle-lit passages',
      'Shirasu (raw whitebait) rice bowls are the island\'s signature dish — try them at the harbour restaurants',
    ],
    best_season: 'Year-round (winter for Fuji views)', access: 'Enoshima Station on Odakyu Enoshima Line (60 min from Shinjuku)', admission: 'Free (observation ¥500)', duration: '2–3 hours',
  },
  {
    id: 'yokohama-chinatown',
    name: 'Yokohama Chinatown',
    prefecture: 'Kanagawa',
    region: 'kanto',
    categories: ['food', 'history'],
    description: 'Japan\'s largest Chinatown — 600 restaurants and shops packed into 10 blocks founded in 1859 when Yokohama became the first port open to foreign trade. The four ornate gates mark each entrance, and the Kanteibyo (Guan Yu temple) at the centre blazes with incense. The weekend dim sum queues rival Hong Kong\'s finest.',
    address: 'Yamashita-cho, Naka-ku, Yokohama',
    lat: 35.4437, lng: 139.6492,
    image_url: PH, tags: ['chinatown', 'dim sum', 'temple', 'yokohama'], is_premium: false,
    highlights: [
      'Japan\'s largest and most authentic Chinatown — over 600 establishments in 0.2 square kilometres',
      'Kanteibyo temple burns so much incense the smoke is visible two blocks away',
      'The weekend pork bun (nikuman) tradition — shops sell 10,000 steamed buns daily from sidewalk steamers',
    ],
    best_season: 'Year-round (Chinese New Year January–February is spectacular)', access: 'Motomachi-Chukagai Station (Minato Mirai Line, 30 min from Shibuya)', admission: 'Free', duration: '2–3 hours',
  },
  {
    id: 'hakone-open-air-museum',
    name: 'Hakone Open Air Museum',
    prefecture: 'Kanagawa',
    region: 'kanto',
    categories: ['activity', 'nature'],
    description: 'Japan\'s first open-air art museum — 120 sculptures by Moore, Rodin, Picasso, and Miro displayed across 7 hectares of mountain landscape, with Mt Hakone visible behind. The Picasso Pavilion houses the world\'s largest Picasso collection outside Spain. An outdoor foot spa of volcanic hot spring water flows through the centre of the grounds.',
    address: '1121 Ninotaira, Hakone-machi, Ashigarashimo-gun, Kanagawa',
    lat: 35.2347, lng: 139.0427,
    image_url: PH, tags: ['open air museum', 'sculpture', 'picasso', 'foot spa'], is_premium: false,
    highlights: [
      '120 sculptures including Moore and Rodin displayed against volcanic mountain scenery',
      'The outdoor foot spa (ash-grey volcanic water) lets you soak while looking at modern art',
      'The Picasso Pavilion\'s 300 works is Japan\'s largest — and rivals European collections',
    ],
    best_season: 'Year-round', access: 'Chokoku no Mori Station on Hakone Tozan Railway (85 min from Shinjuku)', admission: '¥1,600', duration: '2–3 hours',
  },
  {
    id: 'hakone-ryokan',
    name: 'Hakone Onsen',
    prefecture: 'Kanagawa',
    region: 'kanto',
    categories: ['onsen', 'nature'],
    description: 'Japan\'s most popular weekend escape from Tokyo — 17 distinct hot spring areas around Lake Ashi and Mt Hakone with 100+ ryokan ranging from budget minshuku to legendary kaiseki establishments. The Hakone Free Pass covers the romance car train, ropeway, pirate ship on the lake, and open-air museum — all with Mt Fuji visible on clear days.',
    address: 'Hakone-machi, Ashigarashimo-gun, Kanagawa',
    lat: 35.2323, lng: 139.1069,
    image_url: PH, tags: ['onsen', 'ryokan', 'mt fuji', 'lake ashi'], is_premium: false,
    highlights: [
      'Lake Ashi views with Mt Fuji reflected at dawn — the classic Hakone photograph',
      '17 distinct onsen areas — each with different mineral content and character',
      'Hakone Free Pass covers every attraction including the romance car, ropeway, and lake cruise',
    ],
    best_season: 'Year-round (winter for Fuji, autumn for foliage)', access: 'Romance Car from Shinjuku (85 min) or Shinkansen to Odawara (35 min)', admission: 'Free Pass ¥5,000 (2 days)', duration: '1–2 days recommended',
  },
  {
    id: 'yokohama-minatomirai',
    name: 'Yokohama Minato Mirai',
    prefecture: 'Kanagawa',
    region: 'kanto',
    categories: ['history', 'activity'],
    description: 'Yokohama\'s waterfront district built on reclaimed land around the historic Red Brick Warehouse (Akarenga) — a 1911 customs facility turned shopping and event space. The Landmark Tower (Japan\'s second-tallest), Cup Noodle Museum, and Yamashita Park connect along a promenade with the best harbour skyline in Japan.',
    address: 'Minato Mirai, Nishi-ku, Yokohama',
    lat: 35.4560, lng: 139.6363,
    image_url: PH, tags: ['waterfront', 'red brick warehouse', 'cup noodle museum', 'skyline'], is_premium: false,
    highlights: [
      'The Cup Noodle Museum lets you design your own instant noodle cup and flavour combination',
      'Akarenga (Red Brick Warehouse) hosts seasonal markets and concerts in a 1911 customs building',
      'The Landmark Tower observation deck at 273m has a 360-degree view of Tokyo Bay and Mt Fuji',
    ],
    best_season: 'Year-round', access: 'Sakuragicho Station (JR Negishi Line, 30 min from Shibuya)', admission: 'Free (Cup Noodle Museum ¥500)', duration: '2–3 hours',
  },
  {
    id: 'kamakura-temples-trail',
    name: 'Kamakura Temple Trail',
    prefecture: 'Kanagawa',
    region: 'kanto',
    categories: ['spiritual', 'nature', 'activity'],
    description: 'The Kamakura Hiking Course connects Kencho-ji, Zuisen-ji, Egara-tenjin, and Kakuon-ji through forested ridgelines above the medieval city — a 10km trail with Mt Fuji views at the highest points. Kamakura was Japan\'s capital 1185–1333, and the trails pass genuine 13th-century stone Buddhas carved directly into cliff faces.',
    address: 'Kamakura City, Kanagawa Prefecture',
    lat: 35.3243, lng: 139.5467,
    image_url: PH, tags: ['hiking', 'medieval capital', 'cliff buddhas', 'ridge trail'], is_premium: false,
    highlights: [
      '13th-century Yagura (cliff-carved Buddhas) appear throughout the trail — rock tombs and carved reliefs',
      'The ridge-top Tenguyama section has Pacific Ocean views and bamboo groves simultaneously',
      'The trail connects temples that almost no day-trippers visit — Zuisen-ji\'s garden is extraordinary',
    ],
    best_season: 'March–May, September–November', access: 'Kamakura Station (JR Yokosuka Line, 55 min from Tokyo)', admission: 'Free (individual temples ¥200–400)', duration: 'Full day',
  },
  {
    id: 'odawara-castle',
    name: 'Odawara Castle',
    prefecture: 'Kanagawa',
    region: 'kanto',
    categories: ['history'],
    description: 'The castle that withstood Takeda Shingen, Uesugi Kenshin, and even Toyotomi Hideyoshi\'s massive invasion forces — only to surrender to Tokugawa Ieyasu without a battle. The Hojo clan\'s seat of power for 100 years, it has a beautifully reconstructed keep surrounded by 360 cherry trees visible from the Shinkansen.',
    address: '3-1-22 Jonai, Odawara City, Kanagawa',
    lat: 35.2557, lng: 139.1527,
    image_url: PH, tags: ['castle', 'hojo clan', 'cherry blossoms', 'shinkansen view'], is_premium: false,
    highlights: [
      'The Hojo clan held this castle against every rival daimyo for 100 years — a legend of medieval resilience',
      '360 cherry trees in the grounds — visible from the Shinkansen as it approaches',
      'The castle zoo and children\'s area make it a surprisingly lively family destination',
    ],
    best_season: 'March–April (cherry blossoms), Year-round', access: '5 min walk from Odawara Station (Shinkansen/Odakyu)', admission: '¥510', duration: '1–1.5 hours',
  },
  {
    id: 'miura-peninsula',
    name: 'Miura Peninsula Coastal Walk',
    prefecture: 'Kanagawa',
    region: 'kanto',
    categories: ['nature', 'food'],
    description: 'A rugged Pacific coastline an hour from Tokyo with cliffs, hidden coves, and the Aburatsubo Marine Park. Miura is Japan\'s top producer of daikon radish and one of the nation\'s finest sources of bluefin tuna — the tuna festival at Misakiko Port (October) is a rare chance to buy whole-fish portions at near-wholesale prices.',
    address: 'Miura City, Kanagawa Prefecture',
    lat: 35.1358, lng: 139.6109,
    image_url: PH, tags: ['coastal walk', 'tuna festival', 'daikon', 'cliffs'], is_premium: false,
    highlights: [
      'Misaki Tuna Festival (October) — the entire town is devoted to bluefin tuna at harbour prices',
      'Jogashima Island at the peninsula tip has dramatic basalt columns and lighthouse views of Sagami Bay',
      'Fresh tuna don (rice bowl) for ¥800 — the same quality costs ¥3,000 in Tokyo',
    ],
    best_season: 'Year-round (October for tuna festival, February for daikon harvest)', access: 'Misakiguchi Station on Keikyu Kurihama Line (60 min from Shinagawa)', admission: 'Free', duration: 'Half day',
  },
  {
    id: 'sankeien-garden',
    name: 'Sankeien Garden',
    prefecture: 'Kanagawa',
    region: 'kanto',
    categories: ['nature', 'history'],
    description: 'A 175,000-square-metre garden in Yokohama housing 10 historic buildings relocated from Kyoto, Kamakura, and Nara — including a genuine 500-year-old three-storey pagoda and a Rinshunkaku villa. Built by Yokohama silk merchant Hara Sankei in 1906, it remains the finest privately built garden in eastern Japan.',
    address: '58-1 Honmoku Sannotani, Naka-ku, Yokohama',
    lat: 35.4154, lng: 139.6599,
    image_url: PH, tags: ['garden', 'historic buildings', 'pagoda', 'yokohama'], is_premium: false,
    highlights: [
      'A 500-year-old three-storey pagoda from Tomyoji Temple in Kyoto — relocated plank by plank',
      '10 historic buildings including a Noh stage, farmhouse, and Edo-period villa in one garden',
      'The plum grove (200 trees) blooms in February — Yokohama\'s finest early spring garden',
    ],
    best_season: 'February (plum), April (cherry), November (foliage)', access: 'Bus from Yokohama Station (30 min)', admission: '¥700', duration: '1.5–2 hours',
  },

  // ── SAITAMA (10) ──────────────────────────────────────────────────────────
  {
    id: 'kawagoe-little-edo',
    name: 'Kawagoe — Little Edo',
    prefecture: 'Saitama',
    region: 'kanto',
    categories: ['history', 'food'],
    description: 'A well-preserved Edo-period merchant town 30km from Tokyo — nicknamed Koedo (Little Edo) for its kura-zukuri (black plastered storehouse) main street and the only surviving Toki no Kane (Time Bell Tower) in the Kanto region. Confectionery Street (Kashiya Yokocho) has sold traditional dagashi (cheap sweets) since the Meiji era.',
    address: 'Kawagoe City, Saitama Prefecture',
    lat: 35.9252, lng: 139.4858,
    image_url: PH, tags: ['little edo', 'kura-zukuri', 'sweets alley', 'bell tower'], is_premium: false,
    highlights: [
      'The Toki no Kane bell tower has rung four times daily since the 1600s — the only one left in Kanto',
      'Kashiya Yokocho (Confectionery Street) has 20 shops selling traditional dagashi sweets since Meiji era',
      'The kura-zukuri warehouses survived 1893 fire because thick clay walls are fireproof',
    ],
    best_season: 'Year-round (October for Kawagoe Festival)', access: 'Kawagoe Station on Tobu/JR Saikyo Lines (30 min from Ikebukuro)', admission: 'Free', duration: 'Half day',
  },
  {
    id: 'chichibu-shrine',
    name: 'Chichibu — Mountain Town & Shrine',
    prefecture: 'Saitama',
    region: 'kanto',
    categories: ['spiritual', 'nature'],
    description: 'A mountain basin town set among the Oku-Chichibu ranges, home to one of Japan\'s three great night festivals — the Chichibu Yomatsuri (December 3) where six ornate floats and two mikoshi parade through freezing winter streets with fireworks overhead. The Chichibu Shrine (2,100 years old) is a National Important Cultural Property.',
    address: 'Chichibu City, Saitama Prefecture',
    lat: 35.9920, lng: 139.0853,
    image_url: PH, tags: ['night festival', 'mountain town', 'ancient shrine', 'winter fireworks'], is_premium: false,
    highlights: [
      'Chichibu Night Festival (December 3) — one of Japan\'s three great festivals, fireworks over mountain snow',
      'The 34 Kannon temples of the Chichibu Pilgrimage form a 100km mountain circuit',
      'Nagatoro white-water rafting on the Arakawa River runs May–November in the mountain gorge',
    ],
    best_season: 'December (festival), May–November (outdoors)', access: 'Seibu Chichibu Line from Ikebukuro (70 min)', admission: 'Free (shrine)', duration: '1 day',
  },
  {
    id: 'omiya-bonsai-village',
    name: 'Omiya Bonsai Village',
    prefecture: 'Saitama',
    region: 'kanto',
    categories: ['history', 'nature'],
    description: 'The global capital of bonsai art — nine specialist bonsai nurseries clustered in Omiya, established by Tokyo bonsai masters who relocated here after the 1923 earthquake. The Omiya Bonsai Art Museum (world\'s first public bonsai museum) houses pieces 500–1,000 years old. The village hosts the Great Bonsai Festival in May.',
    address: 'Omiya Ward, Saitama City, Saitama',
    lat: 35.9335, lng: 139.6378,
    image_url: PH, tags: ['bonsai', 'nurseries', 'museum', 'ancient trees'], is_premium: false,
    highlights: [
      'World\'s first bonsai art museum — trees over 1,000 years old displayed as living national treasures',
      'Nine specialist nurseries within walking distance — masters will explain individual trees personally',
      'The Great Bonsai Festival in May opens private nursery collections to the public for two days',
    ],
    best_season: 'Year-round (May for festival)', access: 'Tobu Noda Line to Omiya-Koen Station (10 min from Omiya)', admission: 'Museum ¥300', duration: '2–3 hours',
  },
  {
    id: 'nagatoro-gorge',
    name: 'Nagatoro Gorge',
    prefecture: 'Saitama',
    region: 'kanto',
    categories: ['nature', 'activity'],
    description: 'A river gorge of naturally sculpted red and green rocks (Hitsujiyama Rhyolite) carved by the Arakawa River — officially designated Japan\'s first Special Natural Monument (1941). Traditional hand-poled river boats (yakatafune) float through the gorge between rhyolite formations while spring flowers and autumn foliage line the canyon walls.',
    address: 'Nagatoro-cho, Chichibu-gun, Saitama',
    lat: 36.0716, lng: 139.1112,
    image_url: PH, tags: ['gorge', 'river boat', 'rhyolite', 'natural monument'], is_premium: false,
    highlights: [
      'Japan\'s first Special Natural Monument — the red and green layered rock formations are geological wonders',
      'Traditional pole-boats navigate the gorge — the same vessels used for 300 years',
      'Hitsujiyama Park above the gorge has 400,000 moss phlox (shibazakura) blooming April–May',
    ],
    best_season: 'April–May (shibazakura), October–November (foliage)', access: 'Seibu Chichibu Line to Nagatoro Station (80 min from Ikebukuro)', admission: 'Free (boat ¥1,600)', duration: '2–3 hours',
  },
  {
    id: 'higashi-matsuyama-hike',
    name: 'Musashi Kyuryo National Government Park',
    prefecture: 'Saitama',
    region: 'kanto',
    categories: ['nature', 'activity'],
    description: 'Tokyo\'s nearest large national park — 304 hectares of rolling hills and forests in the Kanto Hills, blanketed in shibazakura (moss phlox) in spring and cosmos in autumn. The park sits on the old Musashi Plateau and has winding forest trails, bird-watching towers, and cycling courses that are almost empty on weekdays.',
    address: 'Ranzan-machi, Hiki-gun, Saitama',
    lat: 36.0622, lng: 139.3224,
    image_url: PH, tags: ['national park', 'shibazakura', 'cycling', 'forest'], is_premium: false,
    highlights: [
      'Shibazakura (moss phlox) covers entire hillsides in pink and white in late April',
      '304 hectares of managed forest completely free of crowds on weekdays',
      'Cycling rentals at the entrance allow full exploration without walking',
    ],
    best_season: 'Late April–May (shibazakura), September–October (cosmos)', access: 'Bus from Musashi-Ranzan Station (Tobu Tojo Line, 45 min from Ikebukuro)', admission: '¥450', duration: '2–3 hours',
  },
  {
    id: 'saitama-railway-museum',
    name: 'Saitama Railway Museum',
    prefecture: 'Saitama',
    region: 'kanto',
    categories: ['history', 'activity'],
    description: 'Japan\'s largest railway museum — 36 historic trains spanning from Meiji steam locomotives to bullet trains displayed in a vast hangar. The driving simulators, the miniature landscape layout (Japan\'s largest at 1:80 scale), and the rooftop observation deck over active Shinkansen tracks make this outstanding for all ages, not just train fans.',
    address: '3-47 Onari-cho, Omiya-ku, Saitama City',
    lat: 35.9278, lng: 139.6225,
    image_url: PH, tags: ['railway museum', 'shinkansen', 'steam locomotives', 'simulator'], is_premium: false,
    highlights: [
      'Japan\'s largest railway museum — 36 trains including the first-generation 0-series Shinkansen',
      'The rooftop observation deck overlooks live Shinkansen tracks — trains pass every few minutes',
      'The 1:80 landscape diorama (200 square metres) is the most detailed in Japan',
    ],
    best_season: 'Year-round', access: 'New Shuttle Tetsudo-Hakubutsukan Station (5 min from Omiya Station)', admission: '¥1,330', duration: '3–4 hours',
  },
  {
    id: 'yoshimi-caves',
    name: 'Yoshimi Hyakuana Caves',
    prefecture: 'Saitama',
    region: 'kanto',
    categories: ['history', 'nature'],
    description: 'A hillside riddled with 219 hand-carved burial chambers from the 7th–9th centuries — the largest cluster of ancient burial caves in eastern Japan. The caves were later used by Christian converts (forbidden under the Tokugawa shogunate) as underground meeting rooms, making this site simultaneously prehistoric and politically charged.',
    address: 'Yoshimi-cho, Hiki-gun, Saitama',
    lat: 36.0512, lng: 139.4356,
    image_url: PH, tags: ['burial caves', 'ancient', 'hidden christian', 'archaeology'], is_premium: false,
    highlights: [
      '219 burial chambers carved by hand in the 7th–9th centuries — entirely hollowed cliff faces',
      'Later used by hidden Christians as secret worship sites — a dual historical significance',
      'The site museum has recovered grave goods and explains how the chambers were lived in',
    ],
    best_season: 'Year-round', access: 'Higashi-Matsuyama Station on Tobu Tojo Line (15 min taxi)', admission: '¥300', duration: '1.5–2 hours',
  },
  {
    id: 'ranzan-gorge',
    name: 'Ranzan Gorge',
    prefecture: 'Saitama',
    region: 'kanto',
    categories: ['nature'],
    description: 'A narrow river gorge of crystalline water and autumn maples nicknamed "Little Arashiyama" by Edo-period intellectuals who visited from Tokyo. The hiking path along the canyon rim passes a suspension bridge over the gorge and connects to the Musashi Hills forest trail system. Peak foliage (mid-November) draws visitors from across the region.',
    address: 'Ranzan-machi, Hiki-gun, Saitama',
    lat: 36.0537, lng: 139.3192,
    image_url: PH, tags: ['gorge', 'autumn foliage', 'little arashiyama', 'maple'], is_premium: false,
    highlights: [
      'Called "Little Arashiyama" since the Edo period — Japanese maples over the river canyon',
      'The suspension bridge crossing gives a vertical view of the gorge floor 30 metres below',
      'Free, uncrowded, and within 10 minutes of Nagatoro and Chichibu for a one-day Saitama circuit',
    ],
    best_season: 'Mid-November (foliage)', access: 'Musashi-Ranzan Station on Tobu Tojo Line (45 min from Ikebukuro)', admission: 'Free', duration: '1–2 hours',
  },
  {
    id: 'washinomiya-shrine',
    name: 'Washinomiya Shrine',
    prefecture: 'Saitama',
    region: 'kanto',
    categories: ['spiritual', 'history'],
    description: 'One of the Kanto region\'s oldest and largest shrines — founded over 2,400 years ago and a major power spot for martial arts and archery. The shrine became famous internationally as the setting for the anime "Lucky Star," drawing anime pilgrims from around the world who found a genuinely ancient sacred site waiting for them.',
    address: '135-1 Washinomiya, Kuki City, Saitama',
    lat: 36.0693, lng: 139.6556,
    image_url: PH, tags: ['ancient shrine', 'kanto powerspot', 'anime pilgrimage', 'archery'], is_premium: false,
    highlights: [
      '2,400-year-old shrine with a forest of giant cedar trees — one of the oldest in Kanto',
      'New Year visits draw 500,000 people — "Lucky Star" anime fans now mix with traditional pilgrims',
      'The Kamo Festival in September re-enacts Heian court ceremonies with processions in ancient costume',
    ],
    best_season: 'Year-round (January for New Year)', access: 'Washinomiya Station on Tobu Isesaki Line (40 min from Asakusa)', admission: 'Free', duration: '30–60 min',
  },
  {
    id: 'hanno-tenran-mountain',
    name: 'Mt Tenran — Hanno',
    prefecture: 'Saitama',
    region: 'kanto',
    categories: ['nature', 'activity'],
    description: 'A gentle 305-metre mountain above the Iruma River valley — one of the most approachable peaks for Tokyo day-trippers, with a clear trail to the summit in 40 minutes. Emperor Hirohito walked this mountain in 1931, giving it the name "Tenran" (Emperor\'s View). The summit offers Chichibu mountain panoramas and city views simultaneously.',
    address: 'Hanno City, Saitama Prefecture',
    lat: 35.8478, lng: 139.3176,
    image_url: PH, tags: ['hiking', 'emperors mountain', 'day hike', 'panorama'], is_premium: false,
    highlights: [
      'Named by Emperor Hirohito who hiked here in 1931 — the imperial chrysanthemum marks the summit stone',
      '40-minute summit hike accessible to all ages — a perfect first Japanese mountain experience',
      'Hanno\'s craft sake breweries at the mountain base offer tastings after the descent',
    ],
    best_season: 'Year-round (autumn foliage October–November)', access: 'Hanno Station on Seibu Ikebukuro Line (55 min from Ikebukuro)', admission: 'Free', duration: '2–3 hours',
  },

  // ── CHIBA (10) ────────────────────────────────────────────────────────────
  {
    id: 'narita-san-temple',
    name: 'Naritasan Shinshoji Temple',
    prefecture: 'Chiba',
    region: 'kanto',
    categories: ['spiritual', 'history'],
    description: 'One of Japan\'s most visited temples — receiving 12 million visitors a year, more than Senso-ji. Founded in 940 CE, the Shingon temple complex covers 165,000 square metres with seven buildings of National Treasure status. The old town (Omotesando approach) still has unagi (eel) restaurants that have served travellers since the Edo period.',
    address: '1 Narita, Narita City, Chiba',
    lat: 35.7942, lng: 140.3189,
    image_url: PH, tags: ['shingon temple', 'eel restaurants', 'narita', 'national treasure'], is_premium: false,
    highlights: [
      'Narita\'s main draw beyond the airport — 12 million annual visitors to this 1,000-year-old temple',
      'The Omotesando approach has 20+ unagi (eel) restaurants that have served travellers since Edo times',
      'The three-storey pagoda and main hall are National Important Cultural Properties',
    ],
    best_season: 'Year-round (New Year draws 3 million visitors)', access: 'Narita Station on JR Narita Line (from Tokyo Station, 75 min)', admission: 'Free', duration: '1.5–2 hours',
  },
  {
    id: 'nokogiri-mountain',
    name: 'Mt Nokogiri — Rock Buddha',
    prefecture: 'Chiba',
    region: 'kanto',
    categories: ['spiritual', 'nature', 'activity'],
    description: 'A 329-metre mountain on the Boso Peninsula whose summit ridge is jagged like a saw blade (nokogiri = saw). The mountain is covered in over 1,000 stone Buddhist carvings, a giant Daibutsu (31.5m — taller than Nara\'s), and a cliff-edge viewpoint called Jigoku-nozoki (Hell-gazing Overhang) where visitors are photographed dangling over a 100-metre drop.',
    address: 'Kominato-machi, Awa-gun, Chiba',
    lat: 35.1539, lng: 139.8256,
    image_url: PH, tags: ['jigoku nozoki', 'saw mountain', 'giant buddha', 'cliff overhang'], is_premium: false,
    highlights: [
      'Jigoku-nozoki — a rock ledge that juts 100m over the cliff with zero barrier, the "Hell Peep" viewpoint',
      'A 31.5-metre Daibutsu carved in 1783 — Japan\'s largest stone Buddhist statue',
      'The ropeway ascent takes 4 minutes; 1,522 stone Rakan figures line the descent path',
    ],
    best_season: 'Year-round (avoid typhoon season August–September)', access: 'Hamakanaya Station on JR Uchibo Line (90 min from Tokyo)', admission: '¥700 (ropeway)', duration: '2–3 hours',
  },
  {
    id: 'boso-fureai-trail',
    name: 'Cape Inubosaki & Choshi Port',
    prefecture: 'Chiba',
    region: 'kanto',
    categories: ['nature', 'food'],
    description: 'The easternmost point of the Kanto region — a lighthouse-topped cape where the Kuroshio Current meets the Oyashio Current, creating Japan\'s richest inshore fishing waters. Choshi Port is Japan\'s #1 sardine and saury landing port; the morning market sells fresh-grilled aji (horse mackerel) from open braziers on the harbour quay.',
    address: 'Choshi City, Chiba Prefecture',
    lat: 35.7044, lng: 140.8657,
    image_url: PH, tags: ['lighthouse', 'sardines', 'pacific sunrise', 'fishing port'], is_premium: false,
    highlights: [
      'Japan\'s #1 sardine landing port — the morning market grills whole fish on harbour-side braziers',
      'The lighthouse marks where the Kuroshio and Oyashio currents meet — creating the best fishing in Japan',
      'Choshi\'s soy sauce (Yamasa) has been brewed here since 1645 — brewery tours available',
    ],
    best_season: 'Year-round (autumn for saury season)', access: 'Choshi Station on JR Sobu Honsen/Choshi Electric Railway (90 min from Tokyo)', admission: 'Free', duration: 'Half day',
  },
  {
    id: 'kujukurihama-beach',
    name: 'Kujukuri Beach',
    prefecture: 'Chiba',
    region: 'kanto',
    categories: ['nature', 'activity'],
    description: 'A 66km straight sandy beach — Japan\'s second longest — facing the Pacific Ocean on the Boso Peninsula\'s eastern coast. The consistent surfable waves, the wide open beach with no buildings on the ocean side, and the inoshishi (wild boar) that occasionally wander down from the coastal forest make this a wild Pacific experience.',
    address: 'Kujukuri-machi, Sammu-gun, Chiba',
    lat: 35.5236, lng: 140.5048,
    image_url: PH, tags: ['long beach', 'surfing', 'pacific ocean', 'wild coast'], is_premium: false,
    highlights: [
      'Japan\'s second-longest beach at 66km — wide, largely undeveloped, facing open Pacific',
      'Consistent beach-break surf year-round — Ichinomiya area is the most famous surfing spot',
      'The beach is largely undeveloped — dune grass and pine forest rather than hotels and shops',
    ],
    best_season: 'Year-round (surf), July–August (swimming)', access: 'Bus from Oami Station (JR Sobu Honsen, 30 min)', admission: 'Free', duration: 'Half day–full day',
  },
  {
    id: 'sakura-castle-ruins',
    name: 'Sakura City & Castle Ruins',
    prefecture: 'Chiba',
    region: 'kanto',
    categories: ['history', 'nature'],
    description: 'An old castle town whose park-covered earthworks contain Japan\'s finest local history museum (National Museum of Japanese History — the largest in Japan, covering everything from Jomon to Meiji). The surrounding moat area has the best non-Kyoto cherry blossom walk in eastern Japan — 3,000 trees along 4km of moat-side paths.',
    address: 'Sakura City, Chiba Prefecture',
    lat: 35.7161, lng: 140.2240,
    image_url: PH, tags: ['national museum', 'cherry blossoms', 'castle ruins', 'moat'], is_premium: false,
    highlights: [
      'National Museum of Japanese History — Japan\'s largest history museum covering 12,000 years',
      '3,000 cherry trees along the old castle moat — one of eastern Japan\'s finest blossom walks',
      'The Takei family samurai residence (Edo period) in the castle grounds is the best in Kanto',
    ],
    best_season: 'March–April (cherry blossoms), Year-round (museum)', access: 'Keisei-Sakura Station on Keisei Main Line (30 min from Ueno)', admission: 'Museum ¥600', duration: '2–3 hours',
  },
  {
    id: 'mother-farm',
    name: 'Mother Farm — Boso Hills',
    prefecture: 'Chiba',
    region: 'kanto',
    categories: ['nature', 'activity'],
    description: 'A 250-hectare working farm on the Boso Hills overlooking Tokyo Bay — famous for its seasonal flower spectacles: tulips in spring, sunflowers in summer, cosmos in autumn. The farm also keeps Jersey cows, Berkshire pigs, and sheep (shearing shows daily), making it the finest agricultural experience accessible from Tokyo.',
    address: '940-3 Onjuku, Futtsu City, Chiba',
    lat: 35.2559, lng: 139.9164,
    image_url: PH, tags: ['farm', 'flower fields', 'jersey cows', 'family'], is_premium: false,
    highlights: [
      '250 hectares of flower fields visible from the approach road — tulips carpet entire hillsides in April',
      'The Jersey cow ice cream is made from afternoon milk each day — served warm from the dairy',
      'Tokyo Bay is visible behind the flower fields on clear days',
    ],
    best_season: 'April (tulips), July (sunflowers), October (cosmos)', access: 'Bus from Kimitsu Station (JR Uchibo Line, 30 min)', admission: '¥1,500', duration: '2–3 hours',
  },
  {
    id: 'onjuku-beach',
    name: 'Onjuku Beach & Town',
    prefecture: 'Chiba',
    region: 'kanto',
    categories: ['nature', 'food'],
    description: 'A fishing port and surf town on the Pacific coast of the Boso Peninsula with genuinely good swimming beaches, fresh local lobster (ise-ebi), and an arts community that moved here from Tokyo. The mural-covered old town streets and the fishing harbour where lobster boats return at dawn give it an authenticity missing from better-known beaches.',
    address: 'Onjuku-cho, Isumi-gun, Chiba',
    lat: 35.1253, lng: 140.3927,
    image_url: PH, tags: ['surf town', 'lobster', 'fishing port', 'murals'], is_premium: false,
    highlights: [
      'Ise-ebi (Japanese spiny lobster) caught locally in season (October–April) — grilled at harbour restaurants',
      'Dawn at the fishing harbour: lobster boats return as the Pacific turns orange',
      'The arts murals throughout the old town are commissioned from Tokyo and international artists',
    ],
    best_season: 'July–August (beach), October–April (lobster season)', access: 'Onjuku Station on Isumi Railway (90 min from Chiba)', admission: 'Free', duration: 'Half day',
  },
  {
    id: 'chiba-makuhari-sea',
    name: 'Makuhari Seaside Park',
    prefecture: 'Chiba',
    region: 'kanto',
    categories: ['nature'],
    description: 'A 85-hectare waterfront park on Tokyo Bay with the finest cosmos flower fields (autumn) and spring tulip gardens in the greater Tokyo area. The seaside promenade with distant Fuji views and the contrast of flower fields against the bay and Makuhari convention towers makes for surprisingly photogenic scenery in an otherwise suburban area.',
    address: 'Mihama-ku, Chiba City, Chiba',
    lat: 35.6452, lng: 140.0336,
    image_url: PH, tags: ['cosmos', 'waterfront park', 'tokyo bay', 'flower fields'], is_premium: false,
    highlights: [
      'Japan\'s finest large-scale cosmos field (1 million flowers) from late September to late October',
      'Tokyo Bay views with the Fuji silhouette on clear winter mornings',
      'Free entry on non-event days — the most affordable flower spectacle near Tokyo',
    ],
    best_season: 'Late September–October (cosmos), April (tulips)', access: 'Kaihin-Makuhari Station on JR Keiyo Line (20 min from Tokyo Station)', admission: 'Free', duration: '1.5–2 hours',
  },
  {
    id: 'isumi-railway',
    name: 'Isumi Railway — Rapeseed Blossom Line',
    prefecture: 'Chiba',
    region: 'kanto',
    categories: ['nature', 'activity'],
    description: 'A tiny rural railway of 26km running through the rice paddies and cedar valleys of inland Boso Peninsula. In spring, the entire right-of-way is lined with rapeseed (nanohana) blossoms between the stations. Heritage diesel cars painted in vivid colours pass cherry trees and plum orchards — the finest spring countryside train ride near Tokyo.',
    address: 'Kazusa-Nakano to Ohara, Chiba',
    lat: 35.2441, lng: 140.2853,
    image_url: PH, tags: ['rural railway', 'rapeseed blossom', 'heritage train', 'rice paddies'], is_premium: false,
    highlights: [
      'In spring, the entire 26km track is flanked by rapeseed flowers — a yellow corridor through green rice fields',
      'The diesel railcars are colourfully decorated with local characters — a popular photography subject',
      'The slowest train near Tokyo — 26km takes 43 minutes, giving long views into the countryside',
    ],
    best_season: 'Late March–April (rapeseed)', access: 'Ohara Station on JR Sotobo Line (90 min from Tokyo)', admission: 'Train ticket ¥860 (full route)', duration: '2–3 hours',
  },
  {
    id: 'nokogiriyama-ropeway',
    name: '鋸山 Ropeway',
    prefecture: 'Chiba',
    region: 'kanto',
    categories: ['nature'],
    description: 'A 4-minute gondola ascent over the Uraga Channel to the summit of Mt Nokogiri with views stretching from Tokyo Bay to the Izu Peninsula, the Miura Peninsula, and on clear days, Mt Fuji directly west. The western slope is covered in former quarry walls of cut stone — a dramatic industrial landscape now being reclaimed by moss and fern.',
    address: 'Hamakanaya, Futtsu City, Chiba',
    lat: 35.1595, lng: 139.8221,
    image_url: PH, tags: ['ropeway', 'tokyo bay panorama', 'quarry walls', 'fuji view'], is_premium: false,
    highlights: [
      'Summit panorama: Tokyo Bay, Izu Peninsula, Miura coast, and Mt Fuji all visible simultaneously',
      'The quarry walls of hand-cut stone blocks create an accidental sculpture garden of industrial heritage',
      'Combined with Nihon-ji Temple (at the summit) for the complete Nokogiri-yama experience',
    ],
    best_season: 'Year-round (winter for clearest Fuji views)', access: 'Hamakanaya Station on JR Uchibo Line (ferry from Yokosuka, 35 min)', admission: '¥950 (ropeway)', duration: '2–3 hours',
  },

  // ── IBARAKI (10) ──────────────────────────────────────────────────────────
  {
    id: 'kairakuen-plum',
    name: 'Kairakuen Garden',
    prefecture: 'Ibaraki',
    region: 'kanto',
    categories: ['nature', 'history'],
    description: 'One of Japan\'s three great gardens (with Kenroku-en and Korakuen) — a 13-hectare public garden opened by Lord Nariaki Tokugawa in 1842 with 3,000 plum trees of 100 varieties. The plum blossom festival (February–March) turns the garden into a fragrant pink-and-white landscape and is the largest plum festival in Japan.',
    address: '3-3-6 Tokiwa-cho, Mito City, Ibaraki',
    lat: 36.3702, lng: 140.4587,
    image_url: PH, tags: ['three great gardens', 'plum blossom', 'tokugawa', 'mito'], is_premium: false,
    highlights: [
      'One of Japan\'s three great gardens — 3,000 plum trees of 100 varieties in a Tokugawa lord\'s garden',
      'The Plum Festival (February 20–March 31) is Japan\'s largest plum blossom festival',
      'The attached Kobuntei villa was the retreat of Tokugawa Nariaki — original 1841 interiors intact',
    ],
    best_season: 'Late February–late March (plum)', access: 'Kairakuen Station on JR Joban Line (direct from Ueno, 65 min) — seasonal stop in plum season', admission: '¥300', duration: '1.5–2 hours',
  },
  {
    id: 'hitachi-seaside-park',
    name: 'Hitachi Seaside Park',
    prefecture: 'Ibaraki',
    region: 'kanto',
    categories: ['nature'],
    description: 'Japan\'s most photographed seasonal landscape — 4.5 million nemophila (baby blue eyes) covering an entire hillside in mid-May, turning it an ocean-like blue that contrasts with the Pacific behind. The same hill turns scarlet with 30,000 kochia (fireweed) bushes in October. One of the top flower spectacles in Asia.',
    address: '605-4 Onuma, Hitachinaka City, Ibaraki',
    lat: 36.3951, lng: 140.6077,
    image_url: PH, tags: ['nemophila', 'blue flowers', 'kochia', 'seasonal flowers'], is_premium: false,
    highlights: [
      '4.5 million nemophila flowers cover Miharashi Hill in mid-May — one of Asia\'s great flower spectacles',
      'The same hill turns completely scarlet with 30,000 kochia bushes in mid-October',
      'The Pacific Ocean visible behind the flower hill creates an extraordinary blue-on-blue composition in May',
    ],
    best_season: 'Mid-May (nemophila), Mid-October (kochia)', access: 'Bus from Katsuta Station (JR Joban Line, 15 min)', admission: '¥450', duration: '2–3 hours',
  },
  {
    id: 'tsukuba-mountain',
    name: 'Mt Tsukuba',
    prefecture: 'Ibaraki',
    region: 'kanto',
    categories: ['nature', 'spiritual'],
    description: 'One of Japan\'s 100 Famous Mountains and the most climbed peak in the Kanto region — a twin-peaked mountain (877m) with a rope-way on each peak, a 360-degree viewing deck, and ancient Tsukuba Shrine at the base. The mountain appears in Man\'yoshu poetry from the 8th century and is considered one of Japan\'s most sacred peaks.',
    address: 'Tsukuba City, Ibaraki Prefecture',
    lat: 36.2254, lng: 140.1023,
    image_url: PH, tags: ['twin peaks', '100 famous mountains', 'ropeway', 'manyoshu'], is_premium: false,
    highlights: [
      'One of Japan\'s 100 Famous Mountains — praised in Man\'yoshu poetry 1,300 years ago',
      'Twin peaks (Nantai and Nyotai) each with its own ropeway — connected by a ridge trail',
      'Summit views encompass all of the Kanto Plain, Tokyo, and Mt Fuji simultaneously on clear days',
    ],
    best_season: 'Year-round (winter dawn views of Fuji are best)', access: 'Bus from Tsukuba Station (Tsukuba Express, 40 min from Akihabara)', admission: 'Ropeway ¥1,050', duration: '3–4 hours',
  },
  {
    id: 'kashima-shrine',
    name: 'Kashima Jingu',
    prefecture: 'Ibaraki',
    region: 'kanto',
    categories: ['spiritual', 'history'],
    description: 'One of the oldest and most important shrines in eastern Japan — the patron deity of martial arts and military victory, Kashima Shinkage-ryu (Japan\'s oldest surviving sword school) was born here. The approach through the Kashima Forest is 2km of cedar trees 500–1,000 years old, and the ancient stone lanterns lining it are covered in centuries of moss.',
    address: '2306-1 Kyuga, Kashima City, Ibaraki',
    lat: 35.9671, lng: 140.6329,
    image_url: PH, tags: ['martial arts shrine', 'cedar forest', 'ancient', 'sword school'], is_premium: false,
    highlights: [
      'Birthplace of Kashima Shinkage-ryu — Japan\'s oldest surviving sword martial art',
      '2km cedar forest approach with lanterns covered in 500 years of moss',
      'The deer park beside the shrine — the deer are sacred messengers of the war deity',
    ],
    best_season: 'Year-round', access: 'Kashima Jingu Station on Kashima Rinkai Railway (60 min from Mito)', admission: 'Free', duration: '1–1.5 hours',
  },
  {
    id: 'fukuroda-falls',
    name: 'Fukuroda Falls',
    prefecture: 'Ibaraki',
    region: 'kanto',
    categories: ['nature'],
    description: 'One of Japan\'s three great waterfalls — a four-tiered cascade of 120 metres total height in a narrow gorge accessible through a 110-metre observation tunnel bored directly into the cliff face. Each season transforms the falls: spring snowmelt rages white, summer shows the full green gorge, autumn turns the cliff trees red, and winter freezes the tiers into blue ice columns.',
    address: 'Daigo-machi, Kuji-gun, Ibaraki',
    lat: 36.7567, lng: 140.3768,
    image_url: PH, tags: ['three great waterfalls', 'tunnel viewpoint', 'frozen falls', 'four tiers'], is_premium: false,
    highlights: [
      'One of Japan\'s three great waterfalls — four tiers visible through a dramatic cliff observation tunnel',
      'Winter freezing (January–February) turns the falls into enormous blue ice columns',
      'The tunnel was blasted through the cliff face — you emerge directly opposite the falls at mid-height',
    ],
    best_season: 'January–February (frozen), November (foliage), Year-round', access: 'Bus from Daigo Station (JR Suigun Line, 20 min)', admission: '¥300', duration: '1–1.5 hours',
  },
  {
    id: 'ushiku-daibutsu',
    name: 'Ushiku Daibutsu',
    prefecture: 'Ibaraki',
    region: 'kanto',
    categories: ['spiritual'],
    description: 'The world\'s third-tallest statue at 120 metres (including the 10m lotus base) — a bronze Amitabha Buddha you can enter and ascend to chest level (at 85m) for panoramic Kanto Plain views. The approach through a flower-lined garden contrasts strikingly with the sheer scale of the figure, which is visible from 20km away.',
    address: '2083 Kuridamachi, Ushiku City, Ibaraki',
    lat: 35.9704, lng: 140.1573,
    image_url: PH, tags: ['giant buddha', 'tallest statue', 'bronze', 'observation deck'], is_premium: false,
    highlights: [
      'World\'s 3rd tallest statue at 120m — you can enter and ride an elevator to the chest level at 85m',
      'The approach garden has 100,000 flowers arranged around a reflecting pond with the statue behind',
      'Visible from 20km in all directions — a surreal landmark rising from Ibaraki\'s rice paddies',
    ],
    best_season: 'Year-round (cherry blossom season April is most beautiful)', access: 'Shuttle bus from Ushiku Station (JR Joban Line, 15 min)', admission: '¥1,000', duration: '1.5–2 hours',
  },
  {
    id: 'tsukuba-science-city',
    name: 'JAXA Space Center — Tsukuba',
    prefecture: 'Ibaraki',
    region: 'kanto',
    categories: ['activity', 'history'],
    description: 'Japan\'s main space mission control and astronaut training facility — free tours show the ISS operations control room, a full-size replica of the Japanese Kibo module, space suits, and recovered rocket components. The exhibit building includes hands-on simulations and genuine JAXA mission footage.',
    address: '2-1-1 Sengen, Tsukuba City, Ibaraki',
    lat: 36.0524, lng: 140.1248,
    image_url: PH, tags: ['JAXA', 'space center', 'ISS', 'astronaut training'], is_premium: false,
    highlights: [
      'Free entry to Japan\'s space mission control — the same room that operates the ISS Kibo module',
      'Full-size Kibo module replica you can walk through — identical to the one orbiting Earth right now',
      'Guided tours available in English on request — book one week in advance online',
    ],
    best_season: 'Year-round', access: 'Bus from Tsukuba Station (Tsukuba Express, 20 min)', admission: 'Free', duration: '2–3 hours',
  },
  {
    id: 'ibaraki-aqua-world',
    name: 'Aqua World Ibaraki — Oarai',
    prefecture: 'Ibaraki',
    region: 'kanto',
    categories: ['activity', 'nature'],
    description: 'Japan\'s largest aquarium by number of shark species — 58 varieties of shark in a massive open-ocean tank, including whale sharks and sand tiger sharks. The facility\'s research programs are conducted in collaboration with Hitachi marine science and the exhibits explain the Pacific Current ecosystems of Ibaraki\'s coastline.',
    address: '8252-3 Isohama, Oarai-machi, Higashi-Ibaraki-gun, Ibaraki',
    lat: 36.3063, lng: 140.5780,
    image_url: PH, tags: ['aquarium', 'sharks', 'whale shark', 'oarai'], is_premium: false,
    highlights: [
      'Japan\'s largest shark collection — 58 species including hammerheads, whale sharks, and threshers',
      'The 3-floor ocean tank has daily feeding dives at 11am where divers hand-feed the sharks',
      'The Oarai coast outside is one of Ibaraki\'s best seafood destinations — anglerfish hot pot in winter',
    ],
    best_season: 'Year-round', access: 'Bus from Mito Station (JR Joban Line, 45 min)', admission: '¥1,850', duration: '2–3 hours',
  },
  {
    id: 'taito-museum-nature',
    name: 'Ibaraki Nature Museum',
    prefecture: 'Ibaraki',
    region: 'kanto',
    categories: ['activity', 'nature'],
    description: 'A vast natural history museum surrounded by wetland nature reserves — the museum\'s dinosaur fossils, mammoth skeletons, and diorama ecosystems rival Tokyo\'s National Museum of Nature and Science at a fraction of the price. The attached Satoyama (rural landscape) trail through wetland and oak forest is one of the finest easy nature walks in Kanto.',
    address: '700 Osaki, Bando City, Ibaraki',
    lat: 36.0484, lng: 139.8867,
    image_url: PH, tags: ['natural history museum', 'dinosaurs', 'wetland trail', 'fossils'], is_premium: false,
    highlights: [
      'Mammoth and dinosaur skeletons rivalling Tokyo\'s national museum at ¥540 admission',
      'The 4km Satoyama trail through wetlands is home to 150+ bird species and wild orchids',
      'One of the least-crowded natural history museums in the country despite excellent quality',
    ],
    best_season: 'Year-round (spring for migratory birds)', access: 'Bus from Iwai Station (Kanto Railway, 20 min)', admission: '¥540', duration: '2–3 hours',
  },
  {
    id: 'oarai-isosaki-shrine',
    name: 'Oarai Isosaki Shrine — Sea Torii',
    prefecture: 'Ibaraki',
    region: 'kanto',
    categories: ['spiritual', 'nature'],
    description: 'A coastal shrine with a torii gate standing directly in the Pacific surf — one of Japan\'s top 10 most photographed shrine gates. The shrine has guarded the sea since the 9th century, and the rocks around the torii gate are rich in tidal pools. The Pacific sunrise over the gate (particularly at New Year and summer solstice) is extraordinary.',
    address: '6890 Isohama, Oarai-machi, Ibaraki',
    lat: 36.3091, lng: 140.5871,
    image_url: PH, tags: ['sea torii', 'pacific sunrise', 'tidal rocks', 'coastal shrine'], is_premium: false,
    highlights: [
      'One of Japan\'s most photographed torii gates — standing in the Pacific surf on black volcanic rocks',
      'New Year sunrise from the rocks draws 10,000 visitors annually — the gate frames the rising sun',
      'The tidal pools around the rocks have sea anemones, sea urchins, and edible abalone',
    ],
    best_season: 'Year-round (New Year for sunrise)', access: 'Bus from Mito Station (45 min) or walk from Oarai Station (20 min)', admission: 'Free', duration: '30–60 min',
  },

  // ── TOCHIGI (10) ──────────────────────────────────────────────────────────
  {
    id: 'nikko-toshogu',
    name: 'Nikko Tosho-gu',
    prefecture: 'Tochigi',
    region: 'kanto',
    categories: ['history', 'spiritual'],
    description: 'Japan\'s most ornate shrine — built by the third Tokugawa shogun in 1634 to enshrine the deified Ieyasu. Every surface is covered in lacquer, gold leaf, and carved animals in dazzling profusion — the antithesis of Japanese minimalism. A UNESCO World Heritage site with 103 buildings in a cedar forest, including the famous sleeping cat (Nemuri-neko) carving.',
    address: '2301 Sannai, Nikko City, Tochigi',
    lat: 36.7581, lng: 139.5990,
    image_url: PH, tags: ['UNESCO', 'tokugawa', 'gold leaf', 'ornate shrine'], is_premium: false,
    highlights: [
      'Japan\'s most extravagant shrine — every surface carved and gilded by 15,000 craftsmen over 2 years',
      'The Nemuri-neko (sleeping cat) carving above the gate is Japan\'s most famous woodcarving',
      '103 buildings in a 400-year-old cedar forest — a UNESCO World Heritage site since 1999',
    ],
    best_season: 'Year-round (autumn foliage October–November exceptional)', access: '2 hours from Asakusa by Tobu Nikko Line Limited Express', admission: '¥1,300', duration: '2–3 hours',
  },
  {
    id: 'nikko-kegon-falls',
    name: 'Kegon Falls & Lake Chuzenji',
    prefecture: 'Tochigi',
    region: 'kanto',
    categories: ['nature'],
    description: 'Japan\'s most famous waterfall — a 97-metre drop from the overflow of Lake Chuzenji into the Daiya River gorge. Lake Chuzenji itself sits in a volcanic caldera at 1,269 metres with mountain views of Nantai Volcano. In autumn, the colours of the lake\'s surrounding beech and maple forests rival any in Japan.',
    address: 'Chugushi, Nikko City, Tochigi',
    lat: 36.7491, lng: 139.4975,
    image_url: PH, tags: ['waterfall', 'lake chuzenji', 'volcanic lake', 'autumn foliage'], is_premium: false,
    highlights: [
      '97-metre drop — Japan\'s most photographed waterfall, especially in October when maples surround it',
      'An underground elevator descends to a second viewpoint at the base of the falls',
      'Lake Chuzenji at the top was formed when a Nantai eruption dammed the valley — crystal clear',
    ],
    best_season: 'Late October (peak foliage), May–June (snowmelt flow)', access: 'Bus from Nikko Station (40 min)', admission: '¥550 (elevator)', duration: '2–3 hours',
  },
  {
    id: 'nikko-national-park-hiking',
    name: 'Nikko National Park Hikes',
    prefecture: 'Tochigi',
    region: 'kanto',
    categories: ['nature', 'activity'],
    description: 'One of Japan\'s oldest national parks with trails ranging from the flat Senjogahara marshland boardwalk to the demanding ascent of Mt Nantai (2,486m). The Yuno-ko lake area connects via forest trail to Yumoto Onsen — a steaming, sulphurous alpine spring above the treeline that has been used for pilgrimage bathing since the 9th century.',
    address: 'Nikko City, Tochigi Prefecture',
    lat: 36.8132, lng: 139.4658,
    image_url: PH, tags: ['national park', 'marshland', 'mt nantai', 'alpine onsen'], is_premium: false,
    highlights: [
      'Senjogahara Marshland boardwalk (3km) — flat, wheelchair-accessible, surrounded by volcanic mountains',
      'Yumoto Onsen — an alpine hot spring at 1,478m, the highest in Tochigi, with natural sulphur pools',
      'Mt Nantai ascent (6h round trip) via the ancient pilgrimage trail lined with stone Buddhas',
    ],
    best_season: 'July–October (hiking), November (foliage)', access: 'Bus from Nikko Station (60–90 min)', admission: 'Free (trails)', duration: 'Half day–full day',
  },
  {
    id: 'mashiko-pottery',
    name: 'Mashiko — Living Pottery Village',
    prefecture: 'Tochigi',
    region: 'kanto',
    categories: ['history', 'activity'],
    description: 'The village where ceramics master Hamada Shoji helped launch the Mingei (folk crafts) movement alongside Bernard Leach. Over 300 kilns and galleries cover the hills, producing Mashiko-yaki — earthy, unpretentious stoneware. The Mashiko Reference Collection Museum houses Hamada\'s original workshop and kiln exactly as he left it.',
    address: 'Mashiko-machi, Haga-gun, Tochigi',
    lat: 36.4680, lng: 140.0964,
    image_url: PH, tags: ['mashiko ware', 'pottery', 'mingei', 'hamada shoji'], is_premium: false,
    highlights: [
      'Hamada Shoji\'s original workshop and Noborigama kiln preserved exactly as he left them in 1977',
      '300+ kilns and galleries cover the hills — most offer studio visits and wheel-throwing experiences',
      'The Mashiko Pottery Fair (May and November) opens private kilns and attracts 200,000 visitors',
    ],
    best_season: 'Year-round (May and November for fairs)', access: 'Bus from Utsunomiya Station (JR Tohoku Shinkansen, 55 min)', admission: 'Museum ¥800', duration: 'Half day',
  },
  {
    id: 'utsunomiya-gyoza',
    name: 'Utsunomiya Gyoza Town',
    prefecture: 'Tochigi',
    region: 'kanto',
    categories: ['food'],
    description: 'Japan\'s self-proclaimed gyoza (pan-fried dumpling) capital — the city has 200+ dedicated gyoza restaurants and holds an annual gyoza consumption record. The rivalry with Hamamatsu for the national title is passionately contested. Minmin and Masashi are the institution restaurants, but dozens of smaller joints make the Gyoza Dori (Gyoza Street) in front of the station the best dumpling crawl in Japan.',
    address: 'Utsunomiya City, Tochigi Prefecture',
    lat: 36.5545, lng: 139.8836,
    image_url: PH, tags: ['gyoza', 'dumplings', 'food town', 'gyoza street'], is_premium: false,
    highlights: [
      '200+ gyoza restaurants in one city — Japan\'s highest concentration of dumpling specialists',
      'Utsunomiya gyoza are thinner-skinned with more vegetable filling than other regional styles',
      'The Gyoza Shrine (Gyoza Jinja) is dedicated to the god of gyoza — offerings include raw dumplings',
    ],
    best_season: 'Year-round', access: 'Utsunomiya Station (JR Tohoku Shinkansen, 50 min from Tokyo)', admission: 'Free (restaurant costs vary)', duration: '2–3 hours',
  },
  {
    id: 'kinugawa-onsen',
    name: 'Kinugawa Onsen',
    prefecture: 'Tochigi',
    region: 'kanto',
    categories: ['onsen', 'nature'],
    description: 'The closest large onsen resort to Tokyo — a river gorge resort 2 hours from Asakusa with riverside ryokan, outdoor baths above the Kinugawa River, and a gentle bamboo-and-maple canyon that turns orange in November. The Tobu World Square nearby has 1:25 scale replicas of 102 world heritage sites.',
    address: 'Nikko City, Tochigi Prefecture',
    lat: 36.7977, lng: 139.6740,
    image_url: PH, tags: ['onsen', 'river gorge', 'ryokan', 'autumn foliage'], is_premium: false,
    highlights: [
      'Riverside ryokan with open-air baths directly above the Kinugawa gorge — rocks and water below',
      'The canyon autumn foliage (October–November) frames the river in orange and gold',
      'Tobu World Square nearby has 1:25 miniature replicas of Eiffel Tower, Taj Mahal, and 100 others',
    ],
    best_season: 'October–November (foliage), Year-round', access: 'Tobu Kinugawa Line Limited Express from Asakusa (2 hours)', admission: 'Ryokan day bath from ¥1,000', duration: '1–2 days recommended',
  },
  {
    id: 'nasu-highland',
    name: 'Nasu Highland',
    prefecture: 'Tochigi',
    region: 'kanto',
    categories: ['nature', 'onsen'],
    description: 'A volcanic highland plateau at 1,000m+ elevation where the Imperial Family has its summer villa — the scenery of Mt Chausu, active volcanic vents at Nasu-dake, and the open grazing lands of Nasu Ranch combine with over 50 hot spring inns for one of the most complete countryside retreats near Tokyo.',
    address: 'Nasu-machi, Nasu-gun, Tochigi',
    lat: 37.1079, lng: 139.9747,
    image_url: PH, tags: ['highland', 'volcanic', 'imperial villa', 'onsen'], is_premium: false,
    highlights: [
      'Active volcanic vents at Nasu-dake hiss and steam — hikers wear gas masks above the Yunishigawa zone',
      'The Imperial Family\'s summer villa is closed but the surrounding highland is public walking territory',
      'Nasu Ranch has 50+ cheese and dairy shops — the Miruku Rando facility makes its own camembert',
    ],
    best_season: 'Year-round (July–August for highland escape, October for foliage)', access: 'Bus from Nasu-Shiobara Station (Tohoku Shinkansen, 45 min)', admission: 'Free (hiking)', duration: '1–2 days',
  },
  {
    id: 'ashikaga-flower-park',
    name: 'Ashikaga Flower Park',
    prefecture: 'Tochigi',
    region: 'kanto',
    categories: ['nature'],
    description: 'Japan\'s most spectacular wisteria garden — eight ancient wisteria trees, the largest over 150 years old and spanning 1,000 square metres, create tunnels and waterfalls of hanging purple and white blossoms in late April. The park also has white wisteria, yellow banksia rose, and a carpet of blue wisteria — each with its own photographic composition.',
    address: '607 Kodakucho, Ashikaga City, Tochigi',
    lat: 36.3176, lng: 139.5218,
    image_url: PH, tags: ['wisteria', 'ancient trees', 'flower tunnel', 'purple'], is_premium: false,
    highlights: [
      'The 150-year-old Ohfuji wisteria covers 1,000 square metres — Japan\'s largest wisteria tree',
      'Selected by CNN as one of the world\'s 10 most beautiful wisteria gardens',
      'The white wisteria and yellow banksia rose tunnels bloom alongside — a multi-colour spectacular',
    ],
    best_season: 'Late April–early May (wisteria)', access: 'Ashikaga Flower Park Station on JR Ryomo Line (90 min from Shinjuku)', admission: '¥300–2,000 (seasonal pricing)', duration: '2–3 hours',
  },
  {
    id: 'tochigi-city-canal',
    name: 'Tochigi City — Edo Canal Town',
    prefecture: 'Tochigi',
    region: 'kanto',
    categories: ['history'],
    description: 'A perfectly preserved Edo-period canal town nicknamed "Little Kyoto of the Kanto Region" — kura-zukuri storehouses, daidai-colored walls, and 400-year-old willow trees line the Uzuma River, still navigable by traditional flat-bottom boats. The town centre has more preserved Edo buildings per block than almost anywhere in Japan.',
    address: 'Tochigi City, Tochigi Prefecture',
    lat: 36.3829, lng: 139.7302,
    image_url: PH, tags: ['canal town', 'kura-zukuri', 'boat ride', 'willow trees'], is_premium: false,
    highlights: [
      'Traditional flat-bottom boats poled along the Uzuma River canal — identical to Edo-period transport',
      'Over 20 kura-zukuri buildings in two blocks — the highest concentration outside Kawagoe',
      'The annual Doll Festival (Hina Matsuri, February–March) fills the storehouses with thousands of dolls',
    ],
    best_season: 'Year-round (February–March for Hina Matsuri)', access: 'Tochigi Station on Tobu Nikko Line (55 min from Asakusa)', admission: 'Free (boat ride ¥1,200)', duration: 'Half day',
  },
  {
    id: 'sano-outlet',
    name: 'Sano Premium Outlets',
    prefecture: 'Tochigi',
    region: 'kanto',
    categories: ['activity'],
    description: 'Japan\'s largest premium outlet mall — 210 brand shops in an American village-style complex near the Tohoku Expressway. The shopping aside, the surrounding area has excellent ramen (Sano-ramen uses locally produced springwater), and the Kumagaya Uchiwa Festival in July is one of the Kanto region\'s top summer festivals.',
    address: '2353 Higashitsurugaoka, Sano City, Tochigi',
    lat: 36.3448, lng: 139.6114,
    image_url: PH, tags: ['outlet mall', 'premium shopping', 'sano ramen', 'bargain'], is_premium: false,
    highlights: [
      'Japan\'s largest premium outlet at 210 shops — brands at 30–70% off retail prices',
      'Sano ramen uses springwater from the Sano basin — thin noodles, clear shoyu broth, a local institution',
      'Easy Shinkansen access — 50 min from Tokyo, making it a popular day trip even without a car',
    ],
    best_season: 'Year-round', access: 'Sano Station on Tobu Sano Line + free shuttle (90 min from Asakusa)', admission: 'Free', duration: 'Half day–full day',
  },

  // ── GUNMA (10) ────────────────────────────────────────────────────────────
  {
    id: 'kusatsu-onsen',
    name: 'Kusatsu Onsen',
    prefecture: 'Gunma',
    region: 'kanto',
    categories: ['onsen', 'history'],
    description: 'Japan\'s most celebrated hot spring resort — producing 32,000 litres of acidic sulphurous water per minute from the Yubatake (hot water field) at its centre. The water is so acidic (pH 2.0) that it kills almost all bacteria, giving rise to the local saying "the only thing Kusatsu water can\'t cure is a broken heart." The Yubatake at night is extraordinary.',
    address: 'Kusatsu-machi, Agatsuma-gun, Gunma',
    lat: 36.6199, lng: 138.5970,
    image_url: PH, tags: ['top onsen resort', 'yubatake', 'sulphurous', 'nighttime illumination'], is_premium: false,
    highlights: [
      'The Yubatake (hot water field) produces 32,000 litres of steaming water per minute — illuminated at night',
      'pH 2.0 water kills virtually all bacteria and viruses — Japan\'s most powerful therapeutic spring',
      'The Netsunoyu yumomi performance — wooden paddles stir the 98°C water to cool it for bathing',
    ],
    best_season: 'Year-round (winter snow + steam is magical)', access: 'Bus from Naganohara-Kusatsuguchi Station (JR Agatsuma Line, 25 min from Takasaki)', admission: 'Public baths ¥700 (Netsunoyu ¥600)', duration: '1–2 days recommended',
  },
  {
    id: 'ikaho-onsen',
    name: 'Ikaho Onsen',
    prefecture: 'Gunma',
    region: 'kanto',
    categories: ['onsen', 'history'],
    description: 'An ancient resort town built up a single stone staircase of 365 steps — each step flanked by traditional wooden inns, souvenir shops, and bathhouses. The brown iron-rich water (chakki-yu) has been praised since the Manyoshu (8th century) and stains baths and tiles a distinct dark orange. The town was a favourite retreat of writers and artists throughout the Meiji era.',
    address: 'Ikaho-machi, Shibukawa City, Gunma',
    lat: 36.4771, lng: 139.0190,
    image_url: PH, tags: ['365 stone steps', 'brown water onsen', 'meiji resort', 'historic inn town'], is_premium: false,
    highlights: [
      '365 stone steps — each one flanked by wooden inns and souvenir shops in an Edo townscape',
      'The iron-rich brown water stains everything it touches — unlike any other hot spring in Japan',
      'Praised in the Man\'yoshu anthology (8th century) — one of Japan\'s oldest recorded onsen',
    ],
    best_season: 'Year-round (autumn foliage on the stone steps in October)', access: 'Bus from Shibukawa Station (JR Joetsu Line, 25 min)', admission: 'Public bath ¥400', duration: '1 day recommended',
  },
  {
    id: 'tomioka-silk-mill',
    name: 'Tomioka Silk Mill',
    prefecture: 'Gunma',
    region: 'kanto',
    categories: ['history'],
    description: 'A UNESCO World Heritage site — Japan\'s first modern industrial factory, built in 1872 to process silk using French Jacquard machinery. The vast brick and timber-frame reeling halls are the best-preserved 19th-century industrial buildings in Asia. Tomioka launched Japan\'s industrial revolution and made silk Japan\'s most valuable export for 70 years.',
    address: '1-1 Tomiokacho, Tomioka City, Gunma',
    lat: 36.2579, lng: 138.8907,
    image_url: PH, tags: ['UNESCO', 'silk mill', 'meiji industrialisation', 'french architecture'], is_premium: false,
    highlights: [
      'UNESCO World Heritage since 2014 — Japan\'s first modern factory, built using French engineering in 1872',
      'The brick and timber-frame reeling halls are the largest and best-preserved in Asia',
      'Guided tours explain how Japanese women operated French silk machinery to industrialise the nation',
    ],
    best_season: 'Year-round', access: 'Joshu-Tomioka Station on Joshiden Railway (45 min from Takasaki)', admission: '¥1,000', duration: '1.5–2 hours',
  },
  {
    id: 'haruna-lake',
    name: 'Lake Haruna',
    prefecture: 'Gunma',
    region: 'kanto',
    categories: ['nature', 'activity'],
    description: 'A caldera lake at 1,084 metres on the volcano Mt Haruna — the largest caldera lake in the Kanto region. The lake is famous for its winter ice fishing (smelt) when the surface freezes solid enough to walk on, its summer wakasagi fishing from boats, and the horse-drawn sleighs that cross the frozen surface in February.',
    address: 'Haruna-ko, Takasaki City, Gunma',
    lat: 36.4784, lng: 138.8639,
    image_url: PH, tags: ['caldera lake', 'ice fishing', 'horse sleigh', 'volcanic'], is_premium: false,
    highlights: [
      'In winter, the frozen lake surface is thick enough for ice fishing tents and horse-drawn sleighs',
      'Ice fishing for wakasagi (smelt) is open to anyone with a rental rod — over 1,000 fish per session is common',
      'Mt Haruna\'s summit ring of peaks creates a wind-protected caldera — snow piles 2m+ without blowing away',
    ],
    best_season: 'January–February (ice fishing), June–September (summer)', access: 'Bus from Takasaki Station (JR Joetsu Shinkansen, 60 min)', admission: 'Free (fishing permit ¥700)', duration: 'Half day',
  },
  {
    id: 'akagi-mountain',
    name: 'Mt Akagi',
    prefecture: 'Gunma',
    region: 'kanto',
    categories: ['nature', 'activity'],
    description: 'A broad volcanic mountain at 1,828m above the Kanto Plain with a caldera lake (Onuma) at the summit — one of Gunma\'s three famous mountains. The mountain is known for its extensive beech and oak forests that turn extraordinary gold and crimson in October, and for its connection to the legendary Akagi-san swordsman tradition in Japanese folklore.',
    address: 'Maebashi City, Gunma Prefecture',
    lat: 36.5471, lng: 139.1829,
    image_url: PH, tags: ['volcanic mountain', 'caldera lake', 'autumn foliage', 'swordsman legend'], is_premium: false,
    highlights: [
      'Onuma caldera lake at the summit — fishing for silver carp (funa) in summer, skating in winter',
      'October beech forest colours rival Nikko — and with far fewer visitors',
      'Akagi is one of Gunma\'s "Three Sacred Mountains" with ancient shrine at the summit',
    ],
    best_season: 'October (foliage), July–August (summit walks)', access: 'Bus from Maebashi Station (JR Ryomo Line, 60 min)', admission: 'Free', duration: 'Half day–full day',
  },
  {
    id: 'minakami-outdoor',
    name: 'Minakami — Outdoor Sports Capital',
    prefecture: 'Gunma',
    region: 'kanto',
    categories: ['activity', 'onsen'],
    description: 'The Tone River gorge town that is Japan\'s outdoor sports capital — white-water rafting, bungee jumping, canyoning, and hot air ballooning all operate year-round. Minakami is also the gateway to the Tanigawa mountain range (the Japanese Alps\' most lethal peak) and to Tanigawadake Onsen, a cable car onsen above the snowline.',
    address: 'Minakami-machi, Tone-gun, Gunma',
    lat: 36.6779, lng: 138.9931,
    image_url: PH, tags: ['white water rafting', 'outdoor adventure', 'onsen', 'tanigawa'], is_premium: false,
    highlights: [
      'Grade 3–4 Tone River white-water rafting: 14km through mountain gorge in spring snowmelt season',
      'Tanigawadake cable car connects to skiing, hiking, and the Tenjindaira onsen above the clouds',
      'Bungee jumping from the 42m Akaya Dam with mountain views — the country\'s most scenic bungee',
    ],
    best_season: 'April–June (rafting), December–March (skiing)', access: 'Minakami Station on JR Joetsu Line (90 min from Ueno)', admission: 'Rafting from ¥8,000', duration: '1–2 days',
  },
  {
    id: 'numata-castle-town',
    name: 'Numata Castle Ruins & Town',
    prefecture: 'Gunma',
    region: 'kanto',
    categories: ['history', 'nature'],
    description: 'A castle town perched on a mesa above the Tone and Usui Rivers confluence — the flat-topped plateau creates dramatic views of the surrounding valleys. The town was the domain of Sanada Masayuki (the same commander of Ueda Castle) and holds the Kenmachi shopping street of Edo-period earthen-wall merchant buildings.',
    address: 'Numata City, Gunma Prefecture',
    lat: 36.6457, lng: 139.0427,
    image_url: PH, tags: ['mesa castle', 'sanada clan', 'river confluence', 'merchant street'], is_premium: false,
    highlights: [
      'The castle plateau offers 360-degree views of Tone and Usui river valleys far below',
      'Sanada Masayuki (of Ueda Castle fame) also ruled from here — the same family, two castles',
      'The Kenmachi historic streetscape has preserved earthen-wall merchant buildings from the Edo period',
    ],
    best_season: 'April (cherry blossoms), October–November (autumn)', access: 'Numata Station on JR Joetsu Line (80 min from Ueno)', admission: 'Free (park)', duration: '1.5–2 hours',
  },
  {
    id: 'shima-onsen',
    name: 'Shima Onsen',
    prefecture: 'Gunma',
    region: 'kanto',
    categories: ['onsen', 'nature'],
    description: 'A remote, mist-filled mountain onsen town said to have inspired the setting of Spirited Away — a narrow valley with ryokan stacked up both sides above a rushing river, cable cars crossing between inn buildings, and a communal bath (Kashiwaya-no-yu) in the forest that has been used for 1,300 years.',
    address: 'Nakanojo-machi, Agatsuma-gun, Gunma',
    lat: 36.5863, lng: 138.7345,
    image_url: PH, tags: ['spirited away', 'remote onsen', 'mist valley', 'ancient bath'], is_premium: false,
    highlights: [
      'Said to be one of the inspirations for Spirited Away\'s Aburaya bathhouse — valley and architecture match',
      'Kashiwaya-no-yu communal bath is free and has been open continuously for 1,300 years',
      'The valley ryokan are accessible only by footbridge — no cars beyond the entrance',
    ],
    best_season: 'Year-round (winter snow is most Spirited Away-like)', access: 'Bus from Nakanojo Station (JR Agatsuma Line, 30 min)', admission: 'Ryokan from ¥15,000/night', duration: '1 night recommended',
  },
  {
    id: 'tatebayashi-castle-park',
    name: 'Tatebayashi Castle Park — Azalea Hill',
    prefecture: 'Gunma',
    region: 'kanto',
    categories: ['nature', 'history'],
    description: 'A castle park best known for 10,000 azalea plants (50 varieties) cascading down the old earthwork ramparts in late April — one of Japan\'s top azalea spectacles. The park also has 1,100 cherry trees and the reconstructed castle tower. In autumn, the earthwork moats fill with reflected maple colour.',
    address: 'Tatebayashi City, Gunma Prefecture',
    lat: 36.2391, lng: 139.5425,
    image_url: PH, tags: ['azalea', 'castle park', 'cherry blossoms', 'earthwork ramparts'], is_premium: false,
    highlights: [
      '10,000 azalea plants in 50 varieties cascade down the old castle earthworks in late April',
      '1,100 cherry trees in the park — one of the finest sakura displays in the Kanto region',
      'The earthwork ramparts are the best-preserved in Gunma — no concrete, just original soil banks',
    ],
    best_season: 'Late April (azaleas), late March (cherry)', access: 'Tatebayashi Station on Tobu Isesaki Line (60 min from Asakusa)', admission: 'Free', duration: '1–2 hours',
  },
  {
    id: 'oze-marshland',
    name: 'Oze National Park',
    prefecture: 'Gunma',
    region: 'kanto',
    categories: ['nature', 'activity'],
    description: 'Japan\'s largest highland marshland (2,000m elevation) — a UNESCO Ramsar wetland of ancient peat bogs, alpine ponds, and rare mizubasho (skunk cabbage) lilies that bloom in May when snow still covers the mountain ridges around the plateau. Boardwalk trails cross 280 square kilometres of protected wetland habitat.',
    address: 'Katashina-mura, Tone-gun, Gunma',
    lat: 36.9051, lng: 139.1950,
    image_url: PH, tags: ['highland marsh', 'mizubasho', 'ramsar wetland', 'boardwalk'], is_premium: false,
    highlights: [
      'Mizubasho (skunk cabbage) blooms in May against snow-covered peaks — Japan\'s most dramatic flower hike',
      'UNESCO Ramsar Wetland — a peat bog ecosystem formed over 10,000 years of volcanic activity',
      '280 square kilometres of protected boardwalk trails reachable from three mountain passes',
    ],
    best_season: 'Late May–early June (mizubasho), August (alpine hiking)', access: 'Bus from Numata Station to Oshimizu Trailhead (90 min)', admission: 'Conservation fee ¥500', duration: 'Full day',
  },
];

async function main() {
  const normalized = spots.map((s) => ({ website_url: '', ...s }));

  console.log(`Inserting ${normalized.length} Kanto spots…`);

  const { error } = await supabase
    .from('spots')
    .upsert(normalized, { onConflict: 'id' });

  if (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }

  console.log('Done! All Kanto spots inserted successfully.');

  const counts = {};
  for (const s of normalized) {
    counts[s.prefecture] = (counts[s.prefecture] ?? 0) + 1;
  }
  console.table(counts);
}

main();
